- README.md
> add Privacy Statement

- Makefile
- src/nni_manager/common/utils.ts
- test/naive/run.py
> support travis CI and installing in python virtual environment

- src/nni_manager/core/nniDataStore.ts
Add start time for failed trial jobs
> Add start time for failed trial jobs

- install.sh
- setup.py
add .local/bin to PATH when installing from source code and installing from pip
>  add .local/bin to PATH when installing

- README.md
- docs/GetStarted.md
add tutorial details to homepage
> Edit readme.md

- examples/trials/ga_squad/data.py
- examples/trials/ga_squad/download.sh
- examples/trials/ga_squad/evaluate.py
- examples/trials/ga_squad/graph.py
- examples/trials/ga_squad/readme.md
- examples/trials/ga_squad/train_model.py
- examples/trials/ga_squad/trial.py
This pull request fix bugs prevent SQuAD QA model from running. It also fixes some of pylint warnings.
> Bugfix and partial pylint fix for SQuAD QA model.

- .travis.yml
- Makefile
- deployment/Dockerfile.build.base
- docs/HowToContribute.md
- docs/ToContribute.md
Go through the steps and fix issues, then write a document to introduce how to setup debug environment
> Add document for setting up debug environment

- examples/trials/ga_squad/README.md
Update SQuAD example documentation for users, and adding more technical details.
> Update SQuAD example documentation.

- src/sdk/pynni/nni/smac_tuner/convert_ss_to_scenario.py
fix a bug when converting nni's search space to smac's search space
> fix convert from ss to pcs

- examples/trials/auto-gbdt/config.yml
- examples/trials/mnist-annotation/config.yml
- examples/trials/mnist-batch-tune-keras/config.yml
- examples/trials/mnist-keras/config.yml
- examples/trials/mnist-smartparam/config.yml
- examples/trials/mnist/config.yml
- examples/trials/mnist/config_assessor.yml
- examples/trials/pytorch_cifar10/config.yml
- src/sdk/pynni/nni/README.md
update the comments in config.yml of example trials
update the doc of nni builtin tuner
> update doc for smac tuner

- src/webui/src/components/Sessionpro.tsx
- src/webui/src/components/TrialStatus.tsx
time as number to sort, still show string.
> Fix bug of table sort

- examples/tuners/ga_customer_tuner/customer_tuner.py
This should fix the bug that the tuner crashes after initial population is all trained.
> Bug fix for SQuAD example tuner.

- src/webui/src/components/SlideBar.tsx
> Update slidebar icon

- src/sdk/pynni/nni/README.md
> Typos on paragraph #28.

- docs/CONTRIBUTING.md
My bad, sorry !! I just realized that I might have made this error while writing documentation for some other project.
- Fixed the broken links in CONTRIBUTING
:hatching_chick:
> Hotfix: Fix links - Contributing.md

- src/webui/src/components/Para.tsx
- src/webui/src/components/Sessionpro.tsx
- src/webui/src/components/TrialStatus.tsx
1. Rename hyper graph's button into 'Confirm'
2. Format trial duration, show as '1min 30s'.
> Format trial duration and rename button name

- src/nni_manager/core/nnimanager.ts
fix bug 1: execDuration increases even when experiment is done
fix bug 2: endTime is not created and stored after experiment is done
> fix bug about execDuration and endTime

- docs/StartExperiment.md
> Typo on #12

- src/nni_manager/core/nnimanager.ts
After experiment resume, the experiment's endtime is delete because the experiment is started again
> fix endtime when resume

- src/nni_manager/core/nnimanager.ts
fix the bug: nnimanager does not send TRIAL_END to msgdispatcher when a trial job is finished
> fix bug in nnimanager

- src/sdk/pynni/nni/platform/local.py
Merge v0.2 branch back to master, because PR https://github.com/Microsoft/nni/pull/273 is not merged back to master
> Merge v0.2 branch back to master for PR #273

- src/webui/package.json
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/SearchSpace.tsx
- src/webui/src/components/overview/TrialProfile.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/const.ts
- src/webui/src/static/style/logPath.scss
- src/webui/src/static/style/overview.scss
1. Remove intermediate result in trial deatil table
2. show line number in search space and trial profile
3. modify default metric tooltip position
> Remove intermediate results

- docs/KubeflowMode.md
Update KubeflowMode.md, add kubectl installation guideline link
> Update KubeflowMode.md, add kubectl installation guideline link

- examples/trials/ga_squad/README.md
Fix a spelling bug that may cause confuse
> Delete unnecessary letter 'a'

- README.md
- docs/Installation.md
Below are the minimum system requirements for NNI on Linux. Due to potential programming changes, the minimum system requirements for NNI may change over time.
||Minimum Requirements|Recommended Specifications|
|---|---|---|
|**Operating System**|Ubuntu 16.04 or above|Ubuntu 16.04 or above|
|**CPU**|Intel® Core™ i3 or AMD Phenom™ X3 8650|Intel® Core™ i5 or AMD Phenom™ II X3 or better|
|**GPU**|NVIDIA® GeForce® GTX 460|NVIDIA® GeForce® GTX 660 or better|
|**Memory**|4 GB RAM|6 GB RAM|
|**Storage**|30 GB available hare drive space|
|**Internet**|Boardband internet connection|
|**Resolution**|1024 x 768 minimum display resolution|
Below are the minimum system requirements for NNI on macOS. Due to potential programming changes, the minimum system requirements for NNI may change over time. …
> Add system requirements for NNI Installation

- src/webui/src/components/Overview.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/BasicInfo.tsx
- src/webui/src/components/overview/Progress.tsx
- src/webui/src/components/overview/SearchSpace.tsx
- src/webui/src/components/overview/TrialProfile.tsx
- src/webui/src/static/function.ts
- src/webui/src/static/style/button.scss
- src/webui/src/static/style/overview.scss
- src/webui/src/static/style/progress.scss
1. change font-color
2. add edit concurrency btn
3. fix bug of Yan: parameters is string rather than obj
> [WebUI] Close timer in 'DONE | STOPPED | ERROR' status and add edit concurrency btn

- Makefile
- deployment/pypi/Makefile
- deployment/pypi/setup.py
- setup.py
- src/nni_manager/package.json
- src/nni_manager/rest_server/restHandler.ts
- src/sdk/pynni/setup.py
- tools/nni_cmd/nnictl.py
- tools/setup.py
Support version number provided by `nnictl --version` and webAPI
> Integrate version number of NNI

- README.md
- docs/NNICTLDOC.md
- tools/nni_cmd/launcher_utils.py
1. change the warning level to info level when expand relative path
2. add nnictl --version log
3. update readme.md
> Change WARNING to INFO

- src/webui/src/App.css
- src/webui/src/components/logPath/PaiTrialChild.tsx
- src/webui/src/components/logPath/PaiTrialLog.tsx
- src/webui/src/components/overview/SuccessTable.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/const.ts
1. table column name
2. nni background
> [WebUI] Fix bug

- src/sdk/pynni/nni/hyperband_advisor/README.md
- src/sdk/pynni/nni/hyperband_advisor/hyperband_advisor.py
1. fix the bug that hyperband does not support final/intermediate metric data in `dict` format.
2. make hyperband also use final metric data, not only intermediate metric data.
> Fix hyperband

- src/webui/src/components/SlideBar.tsx
- src/webui/src/components/overview/BasicInfo.tsx
1. feedback link add labels
2. logPath -> Log Directory
> [WebUI] Update feedback link and rename logPath

- src/nni_manager/common/log.ts
- src/nni_manager/core/nniDataStore.ts
- src/nni_manager/rest_server/restHandler.ts
1. Fix log format issue
2. Fix datastore init log info
> Fix db init log and log format issue

- src/sdk/pynni/nni/metis_tuner/metis_tuner.py
* fix bug for https://github.com/Microsoft/nni/issues/726 
* fix logging error
> fix metis bug

- src/webui/src/components/SlideBar.tsx
> [WebUI] change version in feeback link

- src/webui/src/components/TrialsDetail.tsx
> [WebUI] default metrc -> default metric

- deployment/deployment-pipelines.yml
- deployment/pypi/Makefile
> Update build pipeline

- examples/trials/mnist-annotation/mnist.py
- examples/trials/mnist-cascading-search-space/mnist.py
- examples/trials/mnist-distributed/dist_mnist.py
- examples/trials/mnist-hyperband/mnist.py
- examples/trials/mnist/mnist.py
- examples/trials/mnist/mnist_before.py
- test/config_test/examples/mnist-annotation.test.yml
- test/config_test/examples/mnist.test.yml
- tools/nni_annotation/examples/mnist_generated.py
- tools/nni_annotation/examples/mnist_with_annotation.py
- tools/nni_annotation/examples/mnist_without_annotation.py
> Fix tensorflow MNIST dataset download bug in multiple trials

- src/webui/src/components/trial-detail/TableList.tsx
> [WebUI] Support intermediate is dict

- docs/en_US/Trials.md
dropout_rate should be in range [0, 1]
> fix dropout_rate's range

- Makefile
- setup.py
> Fix installation

- src/webui/src/components/SlideBar.tsx
> [Fix-bug] The format of the experimental results "experiment.json" is not an valid json file

- src/nni_manager/core/nnimanager.ts
> Wrong spell

- src/webui/src/components/Overview.tsx
- src/webui/src/components/SlideBar.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/Title1.tsx
- src/webui/src/components/trial-detail/DefaultMetricPoint.tsx
- src/webui/src/components/trial-detail/Duration.tsx
- src/webui/src/components/trial-detail/Intermeidate.tsx
- src/webui/src/components/trial-detail/Para.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/interface.ts
- src/webui/src/static/style/overviewTitle.scss
- src/webui/src/static/style/para.scss
> [WebUI] Add intermediate result and optimize hyper-parameter graph

- src/webui/src/components/Overview.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/SuccessTable.tsx
- src/webui/src/components/overview/TrialProfile.tsx
- src/webui/src/components/public-child/DefaultMetrc.tsx
- src/webui/src/components/public-child/IntermediateVal.tsx
- src/webui/src/components/public-child/LogPathChild.tsx
- src/webui/src/components/public-child/OpenRow.tsx
- src/webui/src/components/public-child/PaiTrialChild.tsx
- src/webui/src/components/public-child/PaiTrialLog.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/const.ts
- src/webui/src/static/interface.ts
In trial detail's table, default metric's value is trial's final result when trial's status is succeed, default metric's value is intermediate result's latest val when trial's status isn't succeed.
when user set logCollection, according value to decide to show log address or anchor.
> [WebUI] Default metric is latest or final result, !local, show trial log hyperlink or address

- src/webui/src/components/Overview.tsx
- src/webui/src/components/overview/TrialProfile.tsx
> Fix issue #927: show experiment profile more accurately in the Overview page

- src/webui/package.json
- src/webui/src/components/overview/SuccessTable.tsx
- src/webui/src/components/public-child/OpenRow.tsx
copy parameters to clipboard in form of python dict.
将超参数以python dict的形式导出到剪贴板。
Closes #904
> copy parameters  to clipboard in form of python dict.

- docs/en_US/NNICTLDOC.md
> Fix bug in NNICTLDOC and add several examples

- .github/ISSUE_TEMPLATE/bug-report.md
Add document message in issue template
> Add document message in issue template

- docs/en_US/NNICTLDOC.md
- setup.py
- tools/nni_cmd/nnictl.py
- tools/nni_cmd/nnictl_utils.py
using `nnictl trial export xxxxxxxx -f hello.csv`
test code pending discussion with @chicm-ms
> export trial status to csv

- src/webui/src/components/overview/Progress.tsx
- src/webui/src/static/style/probar.scss
> show error message more friendly

- docs/en_US/NNICTLDOC.md
The indent is changed after add color at title of each list, get whole content aligned with this change.
> fix doc format for translated content.

- src/sdk/pynni/nni/hyperopt_tuner/hyperopt_tuner.py
> Fix IndexError bug

- src/webui/src/components/Overview.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/Progress.tsx
- src/webui/src/components/trial-detail/Para.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/style/progress.scss
1. Decimal format of metrics other than default on the Web UI #984 
2. fix hyper-parameter graph upper limit and randint upper limit [0-value)
3. help user choose maximal or minimal if he set it in tuner classArgs optimize_mode field
4. remaining field > 0, too long set ...
> Format other final keys and fix bugs in hyper-parameter graph

- src/nni_manager/training_service/remote_machine/gpuScheduler.ts
Check gpuIndices range for remote machine training service.
> Check gpuIndices range for remote machine training service

- deployment/deployment-pipelines.yml
set $( ) to use secret variable in pipeline.
have tested in cloned upload pipeline.
> Fix Windows upload pipeline

- tools/nni_annotation/search_space_generator.py
fix the bug reported in https://github.com/Microsoft/nni/issues/1031
> fix bug that annotation cannot deal with negative numbers

- src/webui/src/components/Overview.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/trial-detail/DefaultMetricPoint.tsx
- src/webui/src/components/trial-detail/Duration.tsx
- src/webui/src/components/trial-detail/Intermeidate.tsx
- src/webui/src/components/trial-detail/Para.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/function.ts
- src/webui/src/static/interface.ts
also, use this._isMounted to check the component status.
For issue #1024
> Use scu to avoid unnecessary rendering

- src/webui/src/components/public-child/IntermediateVal.tsx
> fix bug of default metric decimal

- tools/nni_cmd/launcher.py
> Remind user to change PowerShell execution policy

- tools/nni_cmd/launcher.py
- tools/nni_cmd/tensorboard_utils.py
> Changed file opening syntax to use with open(filename, mode)

- src/webui/src/components/public-child/OpenRow.tsx
- src/webui/src/components/trial-detail/Para.tsx
ensure that hyper-parameter graph render latest data even if you select top percent.
Copy as python rename that Copy as json
> fix bug of hyper-parameter update

- src/webui/src/components/SlideBar.tsx
rename downloaded log file: nnimanager.log & dispatcher.log, before: .json
> download log file

- README.md
> update v0.8 tag

- src/nni_manager/training_service/pai/paiTrainingService.ts
#1076
When submitting job to pai throw error, nni will catch it in pai training service and set trial job status to failed without retry.
> Fix failed to connect to PAI with http code:500

- src/webui/src/components/trial-detail/Para.tsx
- src/webui/src/static/interface.ts
> Show default metric in hyper-parameter

- tools/nni_cmd/launcher.py
> Quick fix for NAS to pass ut

- src/sdk/pynni/nni/networkmorphism_tuner/bayesian.py
Imports `OptimizeMode` from the right place.
Related to #1267
> Fix class wrong import bug

- docs/en_US/BuiltinTuner.md
Add requirements link for NetworkMorphism in BuiltinTuner.md.
> Add requirements link for NetworkMorphism

- docs/requirements.txt
previous failed w/ https://readthedocs.org/projects/nni/builds/9343596/
> withdraw change of requirement.txt

- tools/nni_cmd/url_utils.py
> Fix nnictl trial kill

- src/webui/src/App.css
- src/webui/src/components/Modal/ExperimentDrawer.tsx
- src/webui/src/components/Modal/LogDrawer.tsx
- src/webui/src/components/SlideBar.tsx
- src/webui/src/components/overview/Progress.tsx
- src/webui/src/components/public-child/MonacoEditor.tsx
- src/webui/src/static/const.ts
- src/webui/src/static/function.ts
- src/webui/src/static/style/button.scss
- src/webui/src/static/style/compare.scss
- src/webui/src/static/style/control.scss
- src/webui/src/static/style/logDrawer.scss
- src/webui/src/static/style/openRow.scss
- src/webui/src/static/style/overviewTitle.scss
- src/webui/src/static/style/progress.scss
- src/webui/src/static/style/slideBar.scss
- src/webui/src/static/style/table.scss
> [Fix issue#1173] UX improvement for showing Error log

- src/sdk/pynni/nni/bohb_advisor/requirements.txt
- tools/nni_cmd/nnictl_utils.py
…rsion to v0.9.1.1 (#1297)
* update statsmodel for bohb
* fix nnictl stop experiment bug
* fix nnictl stop experiment bug
* fix nnictl stop experiment bug
> merge v0.9.1.1 back to master w/ cleaned file change

- src/webui/src/components/public-child/IntermediateVal.tsx
- src/webui/src/components/trial-detail/Para.tsx
> [fix issue#1332] Double check for trial does not have final result in webui

- test/naive_test.py
- test/tuner_test.py
- test/utils.py
Including `nnictl stop`, `nnictl stop id` and `nnictl stop all`
> Add test code for `nnictl stop` command

- src/webui/src/components/trial-detail/DefaultMetricPoint.tsx
> [Fix issue#1360] Modify default metric graph

- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/style/search.scss
http://10.172.36.41:3000/detail
#1208
> [Fix issue#1208] Support search parameters

- src/webui/src/components/trial-detail/DefaultMetricPoint.tsx
bug：Trial No. 不连续，图可能会出现多条线
fix之后：
> Fix bug of optimization curve when trial sequenceId is not continuously

- tools/nni_cmd/launcher.py
https://github.com/microsoft/nni/issues/1443
> Fix command line hint

- tools/nni_cmd/nnictl_utils.py
Currently nnictl uses UTC time in `nnictl experiment show`
issue #1447
> Show local time in nnictl

- src/webui/src/App.tsx
- src/webui/src/components/Modal/ExperimentDrawer.tsx
- src/webui/src/components/Overview.tsx
- src/webui/src/components/SlideBar.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/Progress.tsx
- src/webui/src/components/public-child/OpenRow.tsx
- src/webui/src/components/trial-detail/DefaultMetricPoint.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/interface.ts
- default metric column sort [issue](https://github.com/microsoft/nni/issues/1427)
- rename: optimization -> Optimization, Download -> View
- detail table: column保持选过的状态
- update concurrency: linux-数字闪现，windows-更新的是上一次的数值 ( Windows&Linux测过 ) [issue](https://github.com/microsoft/nni/issues/1440)
multiphase： 
- current phase在succeed table同步 [issue](https://github.com/microsoft/nni/issues/1437)
- download exp results bug
> fix bugs, sort, concurrency, multi

- docs/en_US/conf.py
Can we make this process automatic?
> Fix release version in docs

- docs/en_US/CommunitySharings/SptagAutoTune.md
- docs/en_US/CommunitySharings/community_sharings.rst
- docs/en_US/Tuner/BuiltinTuner.md
resolve conflict before merge back v1.0 to master
> merge master to v1.0

- src/webui/src/components/Modal/Compare.tsx
- src/webui/src/components/SlideBar.tsx
- src/webui/src/static/style/slideBar.scss
This PR fixed issue #1282 #1466
> Add Trial No. message in compare modal and add a button to link webui document

- src/nni_manager/common/manager.ts
- src/nni_manager/common/utils.ts
- src/nni_manager/core/nnimanager.ts
- src/nni_manager/core/test/dataStore.test.ts
- src/nni_manager/core/test/sqlDatabase.test.ts
This PR https://github.com/microsoft/nni/pull/1556  break NNI windows version.
> Fix dispatcher CUDA_VISIBLE_DEVICES envvar for windows

- README.md
- deployment/pypi/setup.py
- setup.py
- src/sdk/pynni/requirements.txt
- src/sdk/pynni/setup.py
Potential problem: there are too many `setup.py`s.
> Fix hyperopt and tensorflow version

- src/webui/src/components/Modal/LogDrawer.tsx
- src/webui/src/components/SlideBar.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/Progress.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/model/trial.ts
Fixed bugs:
- Dispatcher log does not refresh automatically
- "Add column" button is not functional on initializing
- Empty search result breaks detail page
- Trials fail before sending first metric will not be listed
> Fix web UI bugs found in bug bash

- docs/en_US/Tuner/BuiltinTuner.md
> Clarify population size needs to be at least concurrency

- src/sdk/pynni/nni/platform/__init__.py
- src/sdk/pynni/nni/platform/standalone.py
> Print INFO log in "standalone" mode

- src/nni_manager/training_service/kubernetes/kubernetesTrainingService.ts
Fix for '[Suggestion: Allow gpuNum: 0 to be run on kubernetes](https://github.com/microsoft/nni/issues/1818)'
> Add support for zero gpuNum in kubernetes

- src/nni_manager/core/ipcInterface.ts
- src/nni_manager/core/nnimanager.ts
Unhandled error event will crash node.
> Catch dispatcher stream error event

- src/nni_manager/config/kubeflow/tfjob-crd-v1.json
- src/nni_manager/training_service/kubernetes/kubeflow/kubeflowApiClient.ts
Kubeflow 0.7 supports apiVersion v1 for tf-operator
> Added support for kubeflow 0.7

- src/sdk/pynni/nni/nas/pytorch/classic_nas/mutator.py
- src/sdk/pynni/nni/nas/pytorch/fixed.py
1. Fixed architecture doesn't handle device any more.
2. Add support for MutableScope in classic NAS.
3. Fix support for InputChoice (validation) in classic NAS.
> Fix a few issues related to fixed arc and from-tuner arc

- azure-pipelines.yml
- docs/en_US/Compressor/Pruner.md
- docs/en_US/Compressor/Quantizer.md
- docs/en_US/Release.md
- docs/en_US/TrainingService/PaiYarnMode.md
- docs/en_US/conf.py
- docs/en_US/examples.rst
- docs/en_US/model_compression.rst
- docs/en_US/training_services.rst
- src/sdk/pynni/nni/ppo_tuner/ppo_tuner.py
add test for sphinx using `-W` (Warning-as-Error)
fix all warnings to pass test.
> Add test for documentation build

- README.md
> Bugfix for nnictl, issue #1949 

- docs/requirements.txt
works on [Build #10262796](https://readthedocs.org/projects/nni/builds/10262796/)
> Fix doc build OOM on readthedocs

- README.md
- tools/nni_cmd/nnictl_utils.py
- tools/nni_cmd/ssh_utils.py
- tools/nni_cmd/tensorboard_utils.py
> support create ssh connection by using sshkey (issue #1950)

- docs/en_US/Compressor/Overview.md
> fix dead link for compressor doc

- src/nni_manager/common/observableTimer.ts
> fix invalid typeof check in ObservableTimer#unsubscribe (closes #2100)

- src/webui/src/components/trial-detail/TableList.tsx
intermediate dict | normal 都测过
> fix bug of dropdown val and graph data dismatch question in the intermeidate graph

- src/webui/src/static/function.ts
- src/webui/src/static/model/trial.ts
https://github.com/microsoft/nni/issues/1918
https://github.com/microsoft/nni/issues/2087
> fix bug of !(object) !(number) metris

- tools/nni_cmd/launcher.py
fix https://github.com/microsoft/nni/issues/2124
> Increase the default heapsize of node to 4GB

- src/webui/src/components/trial-detail/TableList.tsx
- tools/nni_cmd/launcher.py
fix bug of intermeidate dict's intermediate graph
Increase the default heapsize of node to 4GB
> keep removing final val when click other intermeidate keys and Increase the default heapsize of node to 4GB 

- src/webui/src/components/trial-detail/Intermediate.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/function.ts
- src/webui/src/static/style/trialsDetail.scss
> Rename x-axis label of Intermediate result "#Intermediate result"

- src/webui/src/components/Modals/LogDrawer.tsx
> fix issue 2148

- README.md
Document format has been unified with reference to markdownlint.
> Apply markdownlint

- examples/trials/mnist-pbt-tuner-pytorch/mnist.py
- src/sdk/pynni/nni/pbt_tuner/pbt_tuner.py
Enable PBT tuner to perturb any type of hyperparameters
> Add supported data types for PBT tuner

- deployment/docker/Dockerfile
- test/pipelines/pipelines-it-frameworkcontroller.yml
- test/pipelines/pipelines-it-kubeflow.yml
- test/pipelines/pipelines-it-pai-windows.yml
- test/pipelines/pipelines-it-pai.yml
Fix issue #2319 
TODO: Refactor docker image build part in pipelines to eliminate dup code in another PR.
> Fix build docker image problem

- src/webui/src/components/overview/Progress.tsx
- src/webui/src/static/const.ts
- src/webui/src/static/style/progress.scss
- src/webui/src/static/style/tableStatus.css
- change waiting trial status color to `#FDC401`
- ![image](https://user-images.githubusercontent.com/61399850/79733440-b614c880-8327-11ea-8d9e-1660c76762a7.png)
> Overview concurrency tooltip

- src/sdk/pynni/nni/nas/pytorch/base_mutator.py
- src/sdk/pynni/nni/nas/pytorch/mutables.py
- src/sdk/pynni/nni/nas/pytorch/mutator.py
- src/sdk/pynni/nni/nas/pytorch/proxylessnas/mutator.py
> Allow kwargs in layer choice

- examples/nas/spos/network.py
> Fix SPOS's bug on loading checkpoints without state_dict

- src/webui/src/App.scss
- src/webui/src/App.tsx
- src/webui/src/components/Overview.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/BasicInfo.tsx
- src/webui/src/components/overview/Title1.tsx
- src/webui/src/static/style/overview.scss
- src/webui/src/static/style/overviewTitle.scss
- src/webui/src/static/style/trialsDetail.scss
> Refactor overview's best trials module

- src/nni_manager/training_service/local/localTrainingService.ts
- test/config/integration_tests.yml
- test/config/metrics_test/config_failure.yml
- tools/nni_cmd/nnictl_utils.py
* fix empty trial results issue on windows
* return error when `nnictl trial export` with no trial results, along with test case
> Fix it local windows

- test/config/integration_tests.yml
fix https://msrasrg.visualstudio.com/NNIOpenSource/_build/results?buildId=10600&view=results
> delete zero trial test case for IT

- docs/static/css/custom.css
"Lato", segoe ui, "proxima-nova","Helvetica Neue",Arial,sans-serif
> chang font-family

- src/webui/src/components/trial-detail/Para.tsx
This PR is for issue https://github.com/microsoft/nni/issues/2432
> show top trials for hyper-parameter graph

- src/webui/src/components/trial-detail/TableList.tsx
This PR is for `detail table` sort.
- support undefined type(show as --)
- fix bug: table data will not sort when this page refresh
PR里的代码是解决以下两个问题
- 支持排序的这一列数据是undefined;
- 页面正常刷新数据依然是排序过的
> [WebUI] fix table sort issue

- examples/nas/enas-tf/datasets.py
- examples/nas/enas-tf/macro.py
- examples/nas/enas-tf/micro.py
- examples/nas/enas-tf/search.py
- examples/nas/enas-tf/utils.py
- pylintrc
- src/sdk/pynni/nni/nas/tensorflow/enas/mutator.py
- src/sdk/pynni/nni/nas/tensorflow/enas/trainer.py
- src/sdk/pynni/nni/nas/tensorflow/mutables.py
- src/sdk/pynni/nni/nas/tensorflow/mutator.py
- src/sdk/pynni/nni/nas/tensorflow/utils.py
- src/webui/yarn.lock
> TF2 ENAS example

- Makefile
- README.md
- deployment/pypi/Makefile
- deployment/pypi/install.ps1
Test packages:
- [win](https://test.pypi.org/project/nni/0.0.9.2005250219/#files)
- [linux](https://test.pypi.org/project/nni/0.0.9.2005250217/#files)
> Remove leading letter "v" from version string

- examples/trials/mnist-pbt-tuner-pytorch/mnist.py
- examples/trials/mnist-pbt-tuner-pytorch/search_space.json
1.  remove hidden_size in search space
2. change ./tmp  to /tmp in data_dir
> update pbt example

- examples/trials/mnist-pbt-tuner-pytorch/mnist.py
- examples/trials/mnist-pbt-tuner-pytorch/search_space.json
> Revert "update pbt example"

- docs/en_US/_templates/index.html
- docs/static/css/custom.css
- 添加 中文文档 连接
- 表格屏幕适配
- 调整侧边栏version颜色
> add chinese doc link

- docs/en_US/_templates/index.html
`简体中文` link https://nni.readthedocs.io/zh/latest/
> change link

- src/webui/package.json
> Increase heap size for building web UI

- src/webui/src/App.scss
- src/webui/src/components/trial-detail/Duration.tsx
- src/webui/src/static/function.ts
- src/webui/src/static/model/experiment.ts
- src/webui/src/static/model/trialmanager.ts
> [WebUI] fix issue#1489: Enhancement to trial duration display

- src/webui/src/components/Modals/CustomizedTrial.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/SuccessTable.tsx
- src/webui/src/components/trial-detail/Duration.tsx
- src/webui/src/components/trial-detail/Intermediate.tsx
- src/webui/src/components/trial-detail/Para.tsx
- src/webui/src/components/trial-detail/TableList.tsx
> [WebUI] fix issue#2530: duration and intermediate results pictures don't update

- docs/en_US/Tutorial/ExperimentConfig.md
- src/nni_manager/rest_server/restValidationSchemas.ts
> Allow host name as remote server IP

- docs/en_US/Compressor/Overview.md
add the description of taylorfoweight into Overview.md
> add taylorfoweight into supported algo

- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/style/table.scss
> fix metric style

- docs/en_US/Tuner/CustomizeTuner.md
refer to [tuner.py](https://github.com/microsoft/nni/blob/587dd3af02e191906d9e267e206a0d8a86cbf962/src/sdk/pynni/nni/tuner.py#L182)
> add description about update_search_space and format doc

- src/sdk/pynni/nni/compression/torch/pruning/structured_pruning.py
Should remove the forward hooks before the return function.
> [bug bash] fix a small bug.

- src/nni_manager/yarn.lock
https://github.com/microsoft/nni/blob/master/src/nni_manager/package.json#L22 (PR #2615)
> Fix yarn.lock

- docs/en_US/Overview.md
- docs/en_US/Tutorial/ExperimentConfig.md
other minor changes:
1. update `maxTrialNumPerGpu` typo value
> update the NNI architecture figure

- azure-pipelines.yml
* https://github.com/PyCQA/pylint/blob/master/ChangeLog
* https://github.com/PyCQA/astroid/blob/master/ChangeLog
> azure-pipelines.yml: Upgrade pylint and astroid

- src/nni_manager/training_service/reusable/commandChannel.ts
- src/nni_manager/training_service/reusable/environment.ts
- src/nni_manager/training_service/reusable/environments/amlEnvironmentService.ts
- src/nni_manager/training_service/reusable/trial.ts
- src/nni_manager/training_service/reusable/trialDispatcher.ts
> Fix some spelling

- examples/nas/naive-tf/train.py
I forgot to update the example after last refactor.
> Fix TF NAS naive example

- src/webui/src/components/overview/table/SuccessTable.tsx
- src/webui/src/static/style/succTable.scss
> [v1.9 bug bash] fix no-data mode table tooltip align center question

- nni/retiarii/__init__.py
- nni/retiarii/debug_configs.py
- nni/retiarii/graph.py
- nni/retiarii/mutator.py
- nni/retiarii/operation.py
- nni/retiarii/operation_def/__init__.py
- nni/retiarii/operation_def/tf_op_def.py
- nni/retiarii/operation_def/torch_op_def.py
- test/ut/retiarii/mnist-tensorflow.json
- test/ut/retiarii/test_graph.py
- test/ut/retiarii/test_mutator.py
TrainingConfig is commented because I don't have time to add it to test case for now.
graph.py line 144 & 149
> [Retiarii] Graph Representation and Mutation

- examples/trials/ga_squad/trial.py
- examples/trials/mnist-pbt-tuner-pytorch/mnist.py
- examples/trials/sklearn/classification/main.py
- examples/trials/sklearn/regression/main.py
- examples/trials/systems_auto_tuning/opevo/src/algorithms/opevo.py
- examples/trials/weight_sharing/ga_squad/trial.py
- test/async_sharing_test/simple_tuner.py
- test/config/naive_test/naive_assessor.py
- test/config/naive_test/naive_tuner.py
- test/ut/tools/annotation/testcase/annotated/mnist.py
- test/ut/tools/annotation/testcase/usercode/mnist.py
This Pull Request passes string format arguments as logging method parameters.
The Issue seems to be very minor but it improves the readability of the Code and fixes the lazy logging issue in Python 3 which happens to be a standard.
I'm a First-Time Contributor to Microsoft Open-Source so it would be helpful for me understanding how PR workflow works and help me step up in future contributions as well.
> Fix Lazy Logging

- nni/algorithms/compression/pytorch/pruning/structured_pruning.py
Fix a small bug in the dependency_aware mode.
> Fix a small bug in the dependency_aware mode.

- ts/webui/package.json
- ts/webui/scripts/start.js
- ts/webui/src/App.scss
- ts/webui/src/components/NavCon.tsx
- ts/webui/src/components/Overview.tsx
- ts/webui/src/components/modals/ExperimentSummaryPanel.tsx
- ts/webui/src/components/overview/command/Command1.tsx
- ts/webui/src/components/overview/command/Command2.tsx
- ts/webui/src/components/overview/count/EditExperimentParam.tsx
- ts/webui/src/components/overview/count/ExpDuration.tsx
- ts/webui/src/components/overview/count/TrialCount.tsx
- ts/webui/src/components/overview/count/commonStyle.ts
- ts/webui/src/components/overview/experiment/BasicInfo.tsx
- ts/webui/src/components/overview/table/SuccessTable.tsx
- ts/webui/src/components/slideNav/SlideNavBtns.tsx
- ts/webui/src/static/const.ts
- ts/webui/src/static/model/trialmanager.ts
- ts/webui/src/static/style/overview/command.scss
- ts/webui/src/static/style/overview/count.scss
- ts/webui/src/static/style/overview/overview.scss
- ts/webui/src/static/style/overview/panel.scss
- ts/webui/src/static/style/succTable.scss
- ts/webui/yarn.lock
> [webui] update the layout of overview page

- setup.py
1. Fix incorrect conditional dependency
2. Support mypy
3. Add config `develop --skip-ts` to reinstall without compiling ts
> Several improvements of setup.py

- nni/compression/pytorch/speedup/compress_modules.py
- nni/compression/pytorch/speedup/infer_shape.py
- nni/compression/pytorch/utils/mask_conflict.py
- nni/compression/pytorch/utils/shape_dependency.py
- test/ut/sdk/test_model_speedup.py
Support the ConvTranspose2d for speedup in this PR. The pruning of convtranspose2d will be supported in the future.
> Add support for convtranspose 2d

- pipelines/fast-test.yml
- setup.py
Pipeline failed due to scipy upgrade. Latest scipy drops support for Python 3.6.
During debugging I found a new issue, pylint cannot pass on Python 3.7+. I cannot reproduce this issue locally.
TODO: Upgrade Python version of "ubuntu-latest" to 3.8 or 3.9
> Hotfix UT pipeline

- .gitignore
- nni/__init__.py
- pipelines/release.yml
- setup.py
Known issue: pypi's security policy forbids dependencies outside pypi. Therefore SMAC is disabled in this build.
Candidate solution: upload patched SMAC to pypi.
> Fix releasing

- nni/retiarii/__init__.py
- nni/retiarii/codegen/pytorch.py
- nni/retiarii/converter/graph_gen.py
- nni/retiarii/experiment.py
- nni/retiarii/nn/pytorch/nn.py
- nni/retiarii/trainer/pytorch/base.py
- nni/retiarii/utils.py
- test/.gitignore
- test/retiarii_test/darts/darts_model.py
- test/retiarii_test/darts/ops.py
- test/retiarii_test/darts/test.py
- test/retiarii_test/darts/test_oneshot.py
- test/retiarii_test/mnasnet/base_mnasnet.py
- test/retiarii_test/mnasnet/test.py
- test/retiarii_test/mnist/test.py
~~TODO: update graph gen to stop parsing when blackbox is encountered.~~
This PR updates register_module to blackbox_module, which makes the graph converter stop parsing and see the subgraph as one single node.
@blackbox_trainer looks a little weird. ~~Any better suggestions?~~ Use @register_trainer per Quanlu's suggestion.
> Refactor wrap module as "blackbox_module"

- ts/webui/src/components/managementExp/ExperimentManager.tsx
- ts/webui/src/components/overview/params/BasicInfo.tsx
- ts/webui/src/static/model/experimentsManager.ts
- ts/webui/src/static/style/experiment/experiment.scss
- ts/webui/src/static/style/overview/basic.scss
- ts/webui/src/static/style/overview/overview.scss
**main issue:**
1. like this picture, error message is null because its color is white. And this icon's position needs to adjust.
2. These title(`Training platform`, `Best metric`) is **bold** , but don't need this style. 
**After fix:**
**The cause of the problem**
The color of error message is white because the class of `status` and `color` is not nested when render:
> fix some issues about webui overview page

- examples/nas/cdarts/utils.py
- examples/nas/classic_nas-tf/train.py
- examples/nas/enas-tf/search.py
- examples/nas/naive-tf/train.py
- examples/nas/proxylessnas/main.py
- examples/nas/proxylessnas/putils.py
- examples/nas/search_space_zoo/darts_example.py
- examples/nas/search_space_zoo/enas_macro_example.py
- examples/nas/search_space_zoo/enas_micro_example.py
- examples/nas/search_space_zoo/nasbench201.py
- examples/nas/spos/utils.py
- examples/nas/textnas/run_retrain.sh
- examples/nas/textnas/utils.py
To be compatible with latest changes on PyTorch and NNI code hierarchy.
> Fixes for crashed NAS examples

- docs/requirements.txt
> Add new and upgrade dependencies for docs

- pipelines/release.yml
Add back leading letter "v".
https://hub.docker.com/r/msranni/nni/tags
> Fix docker image tag

- docs/en_US/Release.rst
Shall we update the section headers because of the strange sidebar in readthedocs?
> Add release note for v2.0

- docs/en_US/Release.rst
- docs/en_US/contents.rst
> Update wrong date and section headers in ChangeLog

- nni/retiarii/nn/pytorch/nn.py
- nni/retiarii/utils.py
- pipelines/fast-test.yml
Missing del on destruction causes the pipeline to fail sometimes (a lot of times) for ubuntu-legacy. I'm guessing it's related to python version or pytorch version somehow.
Therefore, don't forget to call del accompanying add, symmetrically.
> [Retiarii] Fix record conflicts

- examples/trials/network_morphism/cifar10/cifar10_keras.py
- examples/trials/network_morphism/cifar10/cifar10_pytorch.py
- examples/trials/network_morphism/requirements.txt
I notice the problem when reproducing #3324, but it doesn't fix the issue directly.
> Fix import path of network morphism example

- nni/retiarii/trainer/pytorch/base.py
It seems that the current process only calculates the loss and gradient, and does not use the optimizer for optimization. Therefore, the model is not actually trained, and its accuracy on the Web UI remains unchanged.
> Fix PyTorchImageClassificationTrainer's training

- dependencies/recommended.txt
- dependencies/recommended_legacy.txt
- dependencies/required_extra.txt
- pipelines/fast-test.yml
- setup.py
This PR refactored the dependencies on unittests and will speedup the pipeline across platforms.
> [CI] Fast-test cross-platform speedup

- dependencies/recommended.txt
- dependencies/recommended_legacy.txt
- dependencies/required.txt
- pipelines/fast-test.yml
https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/549
This is a temporary fix. Let's wait for upstream for a long-term solution.
> Pin PyTorch-lightning version to less than 1.2

- examples/trials/cifar10_pytorch/config_adl.yml
- examples/trials/mnist-pytorch/config_adl.yml
* Add the docker images from public docker hubs for the examples in AdaptDL mode
* Add more detailed comments and explanation in the configuration file
> Update the Example Configuration File in AdaptDL Mode

- CONTRIBUTING.md
- Update bad links.
- Fix grammar.
> docs: update en contributing

- nni/tools/trial_tool/trial.py
- ts/nni_manager/training_service/reusable/environments/localEnvironmentService.ts
- ts/nni_manager/training_service/reusable/trialDispatcher.ts
NOTE: the meaning of `gpuNum=0`?
> fix reuse local and trial

- nni/assessor.py
- nni/experiment/config/common.py
> rename accessor to assessor

- nni/common/graph_utils.py
corner case: the input tensor of Cat operator may also be the input tensor of the whole model.
> Fix a bug raised by issue 3372.

- nni/retiarii/converter/graph_gen.py
- nni/retiarii/experiment/pytorch.py
- nni/retiarii/graph.py
- nni/retiarii/integration.py
- nni/retiarii/serializer.py
- nni/retiarii/utils.py
- test/ut/retiarii/test_serializer.py
This PR fixes:
* Support function object in serializer.
* Show no more trial status when strategy exits.
Will defer the error handling of serializer to follow-up PRs (as it's still too difficult/messy for me). Therefore, serializer is still not confident whether it can correctly handle one case or not.
> [Retiarii] Serializer and experiment status fixes

- ts/webui/package.json
- ts/webui/yarn.lock
Reverts microsoft/nni#3449
See #3474 for reasons.
> Revert "Bump react-dev-utils from 9.1.0 to 11.0.4 in /ts/webui"

- nni/nas/pytorch/mutator.py
fix: fix the bug in nni/nas/pytorch/mutator, line no. 87 issue#3525
> fix: fix the bug in nni/nas/pytorch/mutator, line no. 87 issue#3525

- nni/compression/pytorch/speedup/infer_shape.py
fix the bug in nni/compression/pytorch/speedup/infer_shape.py, line no. 625-626
#3562
> fix the bug in nni/compression/pytorch/speedup/infer_shape.py, line no. 625-626

- .github/ISSUE_TEMPLATE/bug-report.md
- add `Describe the bug` at the issue beginning, in this item, could summary the question and upload related image bug message
- bold `NNI version` `nnimanager.log | dispatcher.log | nnictl stdout and stderr`
- `How to reproduce it?` : some people will write something in this plate, and it's beneficial to us so I don't want to delete it.
> update issue bug report template

- ts/nni_manager/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.ts
- ts/nni_manager/training_service/kubernetes/kubeflow/kubeflowTrainingService.ts
Delete redundant code in:
ts/nni_manager/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.ts
ts/nni_manager/training_service/kubernetes/kubeflow/kubeflowTrainingService.ts
These lines will never be reached
> Delete redundant code

- nni/algorithms/compression/pytorch/pruning/amc/channel_pruning_env.py
Modify the comments of supporting resnet in channel_pruning_env.py.
> modify the comments of supporting resnet in channel_pruning_env.py

- examples/model_compress/pruning/naive_prune_tf.py
Update example for slim pruner
> update tf pruner example

- docs/en_US/Tutorial/python_api_start.ipynb
- examples/trials/sklearn/classification/python_api_start.ipynb
- nni/experiment/launcher.py
> Fix typo in nni/experiment/launcher.py

- Dockerfile
- pipelines/release.yml
Turns out that scipy 1.6 is not available for python 3.6.
> Fix docker image version

- ts/webui/src/static/model/experiment.ts
fix issue: https://github.com/microsoft/nni/issues/3710
> fix optimize_mode issue 

- nni/retiarii/nn/pytorch/mutator.py
- test/ut/retiarii/test_highlevel_apis.py
Thanks @hzhua for reporting this issue.
> Fix hidden nodes' remove in Retiarii

- nni/retiarii/graph.py
Fix an issue that will cause excessive memory usage.
> Remove deepcopy in Retiarii evaluator

- .gitignore
- dependencies/develop.txt
- dependencies/recommended.txt
- nni/algorithms/compression/pytorch/auto_compress/experiment.py
- nni/algorithms/compression/pytorch/auto_compress/utils.py
- nni/algorithms/compression/pytorch/pruning/iterative_pruner.py
- nni/algorithms/compression/pytorch/pruning/sensitivity_pruner.py
- nni/algorithms/compression/pytorch/quantization/quantizers.py
- nni/algorithms/hpo/dngo_tuner.py
- nni/algorithms/hpo/hyperband_advisor.py
- nni/algorithms/hpo/metis_tuner/metis_tuner.py
- nni/algorithms/hpo/networkmorphism_tuner/networkmorphism_tuner.py
- nni/algorithms/nas/pytorch/cream/trainer.py
- nni/algorithms/nas/pytorch/fbnet/trainer.py
- nni/algorithms/nas/pytorch/fbnet/utils.py
- nni/algorithms/nas/tensorflow/classic_nas/mutator.py
- nni/algorithms/nas/tensorflow/enas/mutator.py
- nni/experiment/launcher.py
- nni/runtime/log.py
- nni/runtime/msg_dispatcher.py
- nni/runtime/platform/local.py
- nni/runtime/platform/standalone.py
- nni/tools/nnictl/launcher.py
- nni/tools/nnictl/nnictl_utils.py
- pipelines/fast-test.yml
- test/.coveragerc
- test/pytest.ini
- ts/nni_manager/.gitignore
- ts/nni_manager/package.json
Fixed lint issues as some packages are never scanned because of missing `__init__.py`.
> Integrate coverage report into CI

- ts/webui/config/webpack.config.js
- ts/webui/src/components/stateless-component/NNItabs.tsx
- ts/webui/src/index.tsx
> Support prefix for webui static files

- examples/model_compress/pruning/basic_pruners_torch.py
`optimizer` used in pruner might be patched, so need a new `optimizer` in finetuning stage.
> update pruning example

- pipelines/integration-test-trt.yml
This PR is a complement to PR #3862 .
> [Quantization Speedup] Add integration-test-trt.yml for TensorRT integration test

- ts/nni_manager/common/utils.ts
- ts/nni_manager/training_service/kubernetes/kubernetesTrainingService.ts
- ts/nni_manager/training_service/pai/paiTrainingService.ts
- ts/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
- ts/nni_manager/training_service/reusable/trialDispatcher.ts
The connection might not ready when it tries to fetch IP. Make the function async to wait the OS initializing connection.
Reported by Zhenhua.
> Fix a bug in IP detection

- ts/webui/src/components/trial-detail/search/Search.tsx
- ts/webui/src/static/const.ts
fix the **issue**: in search box, input the message look like `Trial id` and then click `enter`, page will be broken
**This PR tip:**
when you input `Trial id` or `Trial id:` or `conv_size>` these incomplete filter, ui will do nothing for this search 
**related ui layout:**
> fix search broken bug with incomplete filter 

- docs/en_US/Compression/ModelSpeedup.rst
- examples/model_compress/pruning/speedup/model_speedup.py
- test/scripts/model_compression.sh
Fix the IT pipeline.
The https://github.com/microsoft/nni/pull/3880 breaks integration pipeline.
> [Bugbash] for speedup example

- nni/runtime/config.py
> Allow for environment variable to set NNI configuration directory

- nni/compression/pytorch/speedup/compressor.py
Remove duplicated log message.
> Remove duplicated log message.

- ts/nni_manager/common/utils.ts
- ts/nni_manager/test/common/getIpv4Address.test.ts
This is a follow up of #3934
The yield method was not strong enough. In certain cases it will not trigger the OS scheduler. So change to setTimeout(1ms) instead.
> Fix bug in IP detection

- nni/compression/pytorch/speedup/jit_translate.py
Support `unsqueeze` requested by https://github.com/microsoft/nni/issues/3944.
> Support UnSqueeze

- examples/model_compress/pruning/speedup/speedup_nanodet.py
- examples/model_compress/pruning/speedup/speedup_yolov3.py
Set the default device for the model.
> Bugbash for speedup example.

- docs/en_US/Compression/Pruner.rst
- examples/model_compress/pruning/transformers/transformer_pruning.py
Fixes:
- config list indentation in example and docs
- example formatting 
- introduce example in the docs
> Fix transformer pruning example

- ts/webui/src/components/trial-detail/search/Search.tsx
in search box, if i input Trial id: xxx, page will be broken.
In this PR, ui support search this format `Trial id: xxx` and `search space: [x]`
> fix id/No. input space bug also support space in search space

- dependencies/recommended.txt
- dependencies/recommended_gpu.txt
hot fix.
@hzhua please investigate the support of cgo on latest lightning.
> Pin PyTorch-lightning < 1.4.2

- pipelines/integration-test-aml.yml
- pipelines/integration-test-kubeflow.yml
> add client az login in pipeline

- nni/algorithms/compression/pytorch/pruning/dependency_aware_pruner.py
- nni/compression/pytorch/utils/__init__.py
- nni/compression/pytorch/utils/mask_conflict.py
- nni/compression/pytorch/utils/shape_dependency.py
- nni/compression/pytorch/utils/utils.py
- test/ut/sdk/test_model_speedup.py
Depth-wise conv will not introduce group dependency. So we loose the group dependency for the depth-wise conv.
> Loose the group dependency

- nni/retiarii/converter/graph_gen.py
Remove useless try catch and pdb. 
It is better to directly crash at graph.add_edge rather than hang indefinitely.
> remove pdb

- dependencies/recommended_gpu.txt
- examples/nas/multi-trial/nasbench101/network.py
- examples/nas/multi-trial/nasbench201/network.py
- nni/nas/benchmarks/constants.py
- nni/retiarii/execution/benchmark.py
- nni/retiarii/execution/python.py
- nni/retiarii/experiment/pytorch.py
- nni/retiarii/nn/pytorch/component.py
- nni/retiarii/nn/pytorch/nasbench101.py
- nni/retiarii/trial_entry.py
This PR will integrate NAS-Bench-101 and 201 benchmark data into Retiarii search space, to enable query "real" architectures on-the-fly.
> NAS Benchmark integration (stage 1)

- ts/jupyter_extension/src/index.ts
@Johnsonms Please check if this works for JupyterLab v2.
> Add NNI icon in JupyterLab extension

- ts/webui/config/webpack.config.js
- ts/webui/package.json
- ts/webui/yarn.lock
related nni PR：https://github.com/microsoft/nni/pull/4175
fix bug of pr 4175, as this picture:
(follow this issue: https://github.com/webpack/changelog-v5/issues/19)
> upgrade axios version

- nni/algorithms/compression/v2/pytorch/pruning/basic_scheduler.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/__init__.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/task_generator.py
> [Model Compression] Add more Task Generator

- .github/pull_request_template.md
add PR template
It's no need test case and doc
could create a new PR to test
> [v1] add PR template 

- nni/retiarii/graph.py
> Fix model reference for pylint

- docs/en_US/Tuner/BatchTuner.rst
- docs/en_US/Tuner/BohbAdvisor.rst
- docs/en_US/Tuner/BuiltinTuner.rst
- docs/en_US/Tuner/DngoTuner.rst
- docs/en_US/Tuner/EvolutionTuner.rst
- docs/en_US/Tuner/GPTuner.rst
- docs/en_US/Tuner/GridsearchTuner.rst
- docs/en_US/Tuner/HyperbandAdvisor.rst
- docs/en_US/Tuner/HyperoptTuner.rst
- docs/en_US/Tuner/MetisTuner.rst
- docs/en_US/Tuner/NetworkmorphismTuner.rst
- docs/en_US/Tuner/PBTTuner.rst
- docs/en_US/Tuner/SmacTuner.rst
- docs/en_US/builtin_tuner.rst
Update Tuner docs
The detailed description is moved to each Tuner's own page, only a simple description is left on the overview page.
> update tuner doc

- README_zh_CN.md
> Readme 中文翻译更新

- CITATION.cff
Add citation link: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
I don't know how to test it before it merges. Therefore I don't even know whether it works.
> Add citation link

- CITATION.cff
The previous author field in citation cff doesn't work as expected. I re-read the manual and believe/hope the following is correct. https://citation-file-format.github.io/assets/pdf/cff-specifications-1.0.0.pdf
Still no way to test.
> Fix author field in citation cff

- docs/en_US/Tuner/BatchTuner.rst
- docs/en_US/Tuner/BohbAdvisor.rst
- docs/en_US/Tuner/BuiltinTuner.rst
- docs/en_US/Tuner/CustomizeAdvisor.rst
- docs/en_US/Tuner/DngoTuner.rst
- docs/en_US/Tuner/EvolutionTuner.rst
- docs/en_US/Tuner/GPTuner.rst
- docs/en_US/Tuner/GridsearchTuner.rst
- docs/en_US/Tuner/HyperbandAdvisor.rst
- docs/en_US/Tuner/HyperoptTuner.rst
- docs/en_US/Tuner/MetisTuner.rst
- docs/en_US/Tuner/NetworkmorphismTuner.rst
- docs/en_US/Tuner/PBTTuner.rst
- docs/en_US/Tuner/RandomTuner.rst
- docs/en_US/Tuner/SmacTuner.rst
- docs/en_US/Tuner/TpeTuner.rst
- docs/en_US/autotune_ref.rst
- docs/en_US/builtin_tuner.rst
- docs/requirements.txt
> Update random & tpe & grid search tuner doc

- README.md
update contributor list in time. [more info](https://contrib.rocks/preview?repo=microsoft%2Fnni)
Loading image from the generation service based on the current contributor list
in `Readme.md` preview
> load contributor image from external service

- Dockerfile
- interim_patch.py
- pipelines/fast-test.yml
- pipelines/integration-test-hybrid.yml
- pipelines/integration-test-remote-l2l.yml
- test/vso_tools/interim_patch.py
> update interim patch

- nni/retiarii/oneshot/pytorch/darts.py
There is a bug in 2nd order. It seems that the tests haven't covered such case.
As we are planning a refactor for one-shot trainers, I lean to add comprehensive tests later.
Run DARTS with unrolled backward.
> Fix DARTS 2nd order

- examples/model_compress/pruning/amc/amc_train.py
- examples/model_compress/pruning/auto_pruners_torch.py
- examples/model_compress/pruning/basic_pruners_torch.py
- examples/model_compress/pruning/finetune_kd_torch.py
- examples/model_compress/pruning/mobilenetv2_end2end/utils.py
- examples/model_compress/pruning/speedup/model_speedup.py
- examples/model_compress/pruning/v2/activation_pruning_torch.py
- examples/model_compress/pruning/v2/admm_pruning_torch.py
- examples/model_compress/pruning/v2/amc_pruning_torch.py
- examples/model_compress/pruning/v2/auto_compress_pruner.py
- examples/model_compress/pruning/v2/fpgm_pruning_torch.py
- examples/model_compress/pruning/v2/iterative_pruning_torch.py
- examples/model_compress/pruning/v2/level_pruning_torch.py
- examples/model_compress/pruning/v2/norm_pruning_torch.py
- examples/model_compress/pruning/v2/scheduler_torch.py
- examples/model_compress/pruning/v2/simple_pruning_torch.py
- examples/model_compress/pruning/v2/simulated_anealing_pruning_torch.py
- examples/model_compress/pruning/v2/slim_pruning_torch.py
- examples/model_compress/pruning/v2/taylorfo_pruning_torch.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/sparsity_allocator.py
~1. update the error message for user-friendly~
1. update the compression example models import
> [Bugbash] update example import path

- examples/model_compress/pruning/v2/activation_pruning_torch.py
- examples/model_compress/pruning/v2/admm_pruning_torch.py
- examples/model_compress/pruning/v2/fpgm_pruning_torch.py
- examples/model_compress/pruning/v2/level_pruning_torch.py
- examples/model_compress/pruning/v2/norm_pruning_torch.py
- examples/model_compress/pruning/v2/slim_pruning_torch.py
- examples/model_compress/pruning/v2/taylorfo_pruning_torch.py
- nni/algorithms/compression/v2/pytorch/pruning/basic_pruner.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/metrics_calculator.py
- test/ut/compression/v2/test_pruning_tools_torch.py
Optimize memory usage in TaylorFO Pruner and Activation-base Pruner.
Fix example bug.
> fix pruning examples & pruner memory usage optimize

- nni/algorithms/compression/v2/pytorch/pruning/tools/sparsity_allocator.py
Split from pr #4423 
e.g., if we set fine-grained pre-masks to a channel-wise pruner, then the generated masks will be channel-wise masks and may not inherit the fine-grained pre-masks. This pr is for inheriting the pre-maks.
> [Bugbash] fix pre-masks inherit

- nni/compression/pytorch/speedup/compressor.py
> add pathlib

- nni/experiment/config/__init__.py
- nni/experiment/config/base.py
- nni/experiment/config/experiment_config.py
- nni/experiment/experiment.py
- nni/tools/nnictl/launcher.py
- test/ut/experiment/test_config_base.py
1. print a link to reference in “nnictl create”
2. rename `exp_config.py` to `experiment_config.py`
3. use more accurate exception type in config class
4. improve docstr
> Some string changes around experiment module

- nni/retiarii/evaluator/pytorch/lightning.py
- test/ut/retiarii/test_lightning_trainer.py
Lightning type is incorrectly handled for function.
> Fix model type in lightning

- docs/zh_CN/TrialExample/Trials.rst
TODO: consider introducing launch from python, or simply mentioning this launching style when the doc of launching from python is ready.
> update chinese doc of writing trial

- nni/common/serializer.py
- test/ut/sdk/test_serializer.py
Add support for generator in serializer. For #4464.
This solution is not perfect. Details in comments of code.
> Add support for generator in serializer

- docs/en_US/Compression/v2_pruning_algo.rst
- examples/model_compress/pruning/v2/activation_pruning_torch.py
- examples/model_compress/pruning/v2/admm_pruning_torch.py
- examples/model_compress/pruning/v2/auto_compress_pruner.py
- examples/model_compress/pruning/v2/movement_pruning_glue.py
- examples/model_compress/pruning/v2/slim_pruning_torch.py
- examples/model_compress/pruning/v2/taylorfo_pruning_torch.py
- nni/algorithms/compression/v2/pytorch/pruning/auto_compress_pruner.py
- nni/algorithms/compression/v2/pytorch/pruning/basic_pruner.py
- nni/algorithms/compression/v2/pytorch/pruning/movement_pruner.py
- nni/algorithms/compression/v2/pytorch/utils/constructor_helper.py
- test/ut/compression/v2/test_iterative_pruner_torch.py
- test/ut/compression/v2/test_pruner_torch.py
- test/ut/compression/v2/test_pruning_tools_torch.py
align nni.trace & del trace_parameters
Just using traced_optimizer based pruner.
> align nni.trace

- README.md
- README_zh_CN.md
- docs/en_US/Release.rst
- docs/en_US/Tutorial/InstallationLinux.rst
- docs/en_US/Tutorial/InstallationWin.rst
- docs/en_US/_templates/index.html
- docs/en_US/conf.py
- docs/zh_CN/Tutorial/InstallationLinux.rst
- docs/zh_CN/Tutorial/InstallationWin.rst
- examples/model_compress/pruning/v2/simulated_anealing_pruning_torch.py
- nni/algorithms/compression/v2/pytorch/pruning/auto_compress_pruner.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/task_generator.py
- test/ut/compression/v2/test_iterative_pruner_torch.py
> Merge v2.6 to master

- pipelines/fast-test.yml
- pipelines/templates/install-dependencies.yml
Set pipeline variable USE_CACHE to false will disable the cache.
So it does not block PRs when the cache is corrupted.
> [pipeline] Add a variable to toggle cache

- pipelines/fast-test.yml
- ts/webui/package.json
> Add web UI sanity-check command

- nni/retiarii/strategy/_rl_impl.py
tianshou has updated its interface of EnvWorker, which breaks our pipeline.
In ut/retiarii,
```bash
pytest test_strategy.py
```
> Up-to-date with send/recv API change of tianshou

- docs/source/experiment/tensorboard.rst
- docs/source/experiment/webui.rst
- docs/source/experiment/webui_zh.rst
- update tensorboard content
- remove tensorboard from webui.rst and webui_zh.rst
> update tensorboard and webui

- README_zh_CN.md
remove redundant Chinese document
> [doc] remove redundant Chinese document

- nni/compression/pytorch/speedup/compress_modules.py
> support flatten

- README.md
> update contrib.rocks url

- nni/algorithms/hpo/evolution_tuner.py
Add doc for evolution tuner.  The doc is copied to the code in doc string. I'm not sure if I need to add more details.
> [WIP] add doc for evolution

- README.md
> improve contributor img

- setup.py
> Fix install script for hello templates

- nni/retiarii/oneshot/pytorch/random.py
> [Fix] shuffle is set to True in train_loader of SinglePathTrainer

- nni/common/hpo_utils/dedup.py
- nni/runtime/env_vars.py
- nni/tools/gpu_tool/gpu_metrics_collector.py
- pipelines/fast-test.yml
#4679 was created before enabling type checking in pipeline.
> Fix typehint

- nni/compression/pytorch/speedup/compress_modules.py
- nni/compression/pytorch/speedup/jit_translate.py
fix issue #4636
fix issue #4687
fix issue #4688
> [Compression] support aten::sub & aten::constant_pad_nd in speedup

- ts/nni_manager/common/experimentStartupInfo.ts
- ts/nni_manager/common/utils.ts
- ts/nni_manager/main.ts
- ts/nni_manager/rest_server/index.ts
- ts/nni_manager/test/rest_server/nni_manager_handlers.test.ts
- ts/nni_manager/test/rest_server/rest_server.test.ts
Refactor NNI manager `main.ts` to make it cleaner and readable.
Run ordinary HPO experiment.
Don't mention.
> Refactor NNI manager globals (step 2) - main.ts

- pipelines/fast-test.yml
- pipelines/templates/cache-dependencies-template.yml
- pipelines/templates/install-dependencies.yml
- test/vso_tools/pack_dependencies.py
- test/vso_tools/unpack_dependencies.py
The previous attempt basing on VSO artifact does not work.
Let's try Azure blob.
> Move pipeline cache to azure blob

- dependencies/develop.txt
- ts/jupyter_extension/package.json
- ts/jupyter_extension/yarn.lock
> lock version to remove es5-ext

- ts/webui/README.md
- ts/webui/package.json
- ts/webui/src/static/const.ts
- ts/webui/src/static/style/experiment/trialdetail/search.scss
- ts/webui/src/static/style/openRow.scss
- ts/webui/yarn.lock
- fix stylelint bug by https://github.com/stylelint/stylelint/issues/5998#issuecomment-1082567955 also close [Remove stylelint](https://github.com/microsoft/nni/pull/4713) because bug had been fixed.
- update webui nav bar link
- update webui dev doc
run command: 
`cd ts/webui`
`yarn stylelint --fix`
I had test these.  It works.
> fix stylelint bug and update WEBUIDOC link

- README.md
**1. top part**
**2. contributor part**
>  contributor count

- docs/source/installation_zh.rst
- docs/source/notes/build_from_source.rst
- ts/webui/package.json
- ts/webui/yarn.lock
1. Upgrade a webui dependency so it can build on M1
2. Add some missing information in building guide
3. Installation guide translation
> Update installation doc and M1 support

- docs/source/hpo/advanced_toctree.rst
- docs/source/hpo/custom_algorithm.rst
- docs/source/hpo/hpo_benchmark.rst
- docs/source/hpo/nni_annotation.rst
- docs/source/reference/experiment_config.rst
- docs/source/sharings/hpo_comparison.rst
- docs/source/sharings/rocksdb_examples.rst
> Fix doc links

- ts/nni_manager/common/globals/index.ts
- ts/nni_manager/common/globals/shutdown.ts
- ts/nni_manager/common/globals/unittest.ts
- ts/nni_manager/common/log.ts
- ts/nni_manager/common/manager.ts
- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/main.ts
- ts/nni_manager/rest_server/index.ts
- ts/nni_manager/rest_server/restHandler.ts
- ts/nni_manager/test/common/globals_log_stream.test.ts
- ts/nni_manager/test/common/globals_shutdown.test.ts
- ts/nni_manager/test/common/logging.test.ts
- ts/nni_manager/test/core/nnimanager.test.ts
Add a global shutdown manager.
Run experiments and stop them in different ways.
Then check the end of nnimanager.log to see if there is anything strange.
No need to mention.
> Refactor NNI manager globals (step 5) - shutdown

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/studentProgram.md
- nni/tools/nnictl/launcher.py
> fix nnictl doc link 

- docs/source/conf.py
- test/pytest.ini
Let's see who wrote the slow test cases. 🙂
> Show duration of each UT case

- nni/retiarii/oneshot/pytorch/base_lightning.py
- nni/retiarii/oneshot/pytorch/darts.py
- nni/retiarii/oneshot/pytorch/differentiable.py
- nni/retiarii/oneshot/pytorch/enas.py
- nni/retiarii/oneshot/pytorch/proxyless.py
- nni/retiarii/oneshot/pytorch/random.py
- nni/retiarii/oneshot/pytorch/sampling.py
- nni/retiarii/oneshot/pytorch/strategy.py
- nni/retiarii/oneshot/pytorch/supermodule/_operation_utils.py
- nni/retiarii/oneshot/pytorch/supermodule/_singlepathnas.py
- nni/retiarii/oneshot/pytorch/supermodule/_valuechoice_utils.py
- nni/retiarii/oneshot/pytorch/supermodule/base.py
- nni/retiarii/oneshot/pytorch/supermodule/differentiable.py
- nni/retiarii/oneshot/pytorch/supermodule/operation.py
- nni/retiarii/oneshot/pytorch/supermodule/proxyless.py
- nni/retiarii/oneshot/pytorch/supermodule/sampling.py
- nni/retiarii/oneshot/pytorch/utils.py
- pyrightconfig.json
- test/ut/retiarii/test_lightning_trainer.py
- test/ut/retiarii/test_oneshot.py
Fix typehint for oneshot NAS.
There are a few minor bug fixes.
1. Make the optimizer types supported clear.
2. ENAS is now reading from callback metrics rather than computing metrics on its own.
3. Fix some mis-spelling issues in call optimizer/lr-scheduler.
4. Support lightning v1.6.
> Typehint for oneshot NAS

- docs/source/experiment/web_portal/web_portal.rst
- docs/source/experiment/web_portal/web_portal_zh.rst
click image in web_portal doc, get 404 link, look like this: https://nni.readthedocs.io/en/img/webui-img/summary.png
> fix webui doc image click issue

- test/ut/sdk/imported/_test_serializer_main.py
> Fix a corrupted test in serializer

- ts/webui/src/components/experiment/trialdetail/table/tableFunction/search/GeneralSearch.tsx
- ts/webui/src/components/experiment/trialdetail/table/tableFunction/search/Search.tsx
- ts/webui/src/components/experiment/trialdetail/table/tableFunction/search/SearchDefaultMetric.tsx
- ts/webui/src/components/experiment/trialdetail/table/tableFunction/search/SearchParameterConditions.tsx
- ts/webui/src/components/experiment/trialdetail/table/tableFunction/search/searchFunction.ts
- PR title, support search look like `10`(trial No.) and `nj`(trial id) string in search input
- add filter trial `Default metric` in filter `button`
> support searching customized string in the search box

- ts/webui/src/components/experiment/trialdetail/TrialsDetail.tsx
- ts/webui/src/components/experiment/trialdetail/chart/Para.tsx
- ts/webui/src/static/style/loading.scss
**fix issue:** https://github.com/microsoft/nni/issues/4839#issue-1225632543
backend PR: https://github.com/microsoft/nni/pull/4856
**content:** 
- add `maximize` and 'minimize' 
- make loading image more small
Run experiments to use these buttons in hyper-parameter graph
> [fix issue] add dropdown:`maximize` and `minimize` for hyper-parameter top trials

- nni/compression/pytorch/speedup/compressor.py
This pr enable customizing the replace function accordingly.
> enable customizing the replace function

- nni/__init__.py
- nni/experiment/experiment.py
- nni/experiment/launcher.py
- nni/retiarii/experiment/pytorch.py
- nni/runtime/log.py
- nni/tools/nnictl/launcher.py
Refactor logging system according to plan #4499
> Logging refactor (step 1) - experiment handlers

- ts/nni_manager/package.json
- ts/nni_manager/yarn.lock
A new security alert this morning.
> Fix new security alert

- dependencies/develop.txt
- dependencies/recommended_legacy.txt
- nni/algorithms/compression/v2/pytorch/pruning/amc_pruner.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/rl_env/amc_env.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/rl_env/memory.py
- nni/common/serializer.py
- nni/retiarii/execution/interface.py
- nni/retiarii/execution/python.py
- nni/retiarii/experiment/pytorch.py
- nni/retiarii/graph.py
- nni/retiarii/integration_api.py
- nni/retiarii/strategy/_rl_impl.py
- nni/tools/package_utils/tuner_factory.py
Almost every pyright upgrade causes new issues. We decide to pin pyright, and upgrade it at every release.
> Pin pyright version

- ts/nni_manager/config/aml/amlUtil.py
- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/training_service/reusable/aml/amlClient.ts
- ts/nni_manager/training_service/reusable/environments/amlEnvironmentService.ts
This PR address two issues in AML:
1. The InteractiveLoginAuthentication no longer automatically falls back to AzureCliAuthentication in a new version of AzureML SDK. It needs to be done manually.
2. Refine the exception handling so that users can see what's wrong in log when AML client throws error.
> Refactor integration test (step 2) - AML authentication and debuggability

- docs/source/nas/evaluator.rst
- docs/source/nas/execution_engine.rst
- docs/source/nas/exploration_strategy.rst
- docs/source/nas/serialization.rst
- docs/static/css/material_custom.css
- nni/retiarii/nn/pytorch/component.py
- nni/retiarii/oneshot/pytorch/differentiable.py
- nni/retiarii/oneshot/pytorch/supermodule/operation.py
- test/ut/retiarii/test_oneshot_supermodules.py
Fix some miscellaneous issues in v2.8 one-shot NAS documentation.
> One-shot documentation (more imprv.)

- ts/webui/src/components/experiment/trialdetail/chart/DefaultMetricPoint.tsx
- ts/webui/src/components/experiment/trialdetail/chart/Intermediate.tsx
- ts/webui/src/static/style/experiment/trialdetail/para.scss
- ts/webui/src/static/style/experiment/trialdetail/trialsDetail.scss
> Add optimized_mode dropdown for Default metric chart in detail page

- .github/pull_request_template.md
- pipelines/fast-test.yml
- pipelines/full-test-compression.yml
- pipelines/full-test-hpo.yml
- pipelines/full-test-nas.yml
- pipelines/templates/stage-filter.yml
The filter will check the files setting in `filter.modified.globs`, if the files are modified, the following `stage: test` will run.
> [Pipeline] filter trigger

- docs/source/experiment/training_service/paidlc.rst
- examples/trials/mnist-pytorch/config_dlc.yml
- nni/experiment/config/training_services/dlc.py
- ts/nni_manager/common/experimentConfig.ts
- ts/nni_manager/config/dlc/dlcUtil.py
- ts/nni_manager/training_service/reusable/dlc/dlcClient.ts
- ts/nni_manager/training_service/reusable/environments/dlcEnvironmentService.ts
add a workspace_id as DLC api updated.
- [] test case
verified on Alibaba PAI DLC
- [] doc
doc updated
open alibaba pai DSW, follow the docs to create a file for testing.
> [DLC]: pai-dlc api update & log folder update

- pipelines/fast-test.yml
- pipelines/full-test-compression.yml
- pipelines/full-test-hpo.yml
- pipelines/full-test-nas.yml
- pipelines/integration-test-aml.yml
- pipelines/integration-test-frameworkcontroller.yml
- pipelines/integration-test-hybrid.yml
- pipelines/integration-test-kubeflow.yml
- pipelines/integration-test-local-linux.yml
- pipelines/integration-test-local-windows.yml
- pipelines/integration-test-openpai-linux.yml
- pipelines/integration-test-remote-l2l.yml
- pipelines/integration-test-remote-w2w.yml
Add a schedule for pipelines to trigger them every night.
> Nightly trigger

- examples/trials/benchmarking/automlbenchmark/nni/extensions/NNI/architectures/run_mlp.py
- examples/trials/benchmarking/automlbenchmark/nni/extensions/NNI/architectures/run_random_forest.py
- examples/trials/kaggle-tgs-salt/metrics.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/task_generator.py
- nni/algorithms/hpo/ppo_tuner/ppo_tuner.py
Hi Maintainers of this repo,
Thank you very much for your excellent work,
I am new to this repository.
I am a researcher studying the best practices of evolving data science codes. According to our findings after examining 1000 data science repositories, migrating to **Numpy** is a widespread evolution practice among developers since it improves performance and code quality. I noticed in this PR's code that it might make better use of NumPy functions and avoid unnecessary loops, and APIs.
This PR is a minor contribution compared to all the hard work that you have done in this repo. However, I am hoping that it will enhance code quality and, hopefully, performance.
This is refactoring. Therefore, none of the below is updated
This is a refactoring
> Few optimizations with numpy

- README.md
Seems that the original link is broken now.
> Update link of Pruner

- nni/common/version.py
info level "not installed" msg is a bit annoying, discovered by @QuanluZhang
> [Common] change version utils log level

- ts/nni_manager/config/dlc/dlcUtil.py
- ts/nni_manager/training_service/reusable/dlc/dlcClient.ts
- ts/nni_manager/training_service/reusable/environments/dlcEnvironmentService.ts
solve the failed job reject
slove the dlclient request failed
slove the user flow control (sleep)
verified on Alibaba PAI DLC
open alibaba pai DSW or use ECS ,follow the docs to create a file for testing.
> [DLC] update the failed job and dlcclient request and user flow control

- pipelines/full-test-compression.yml
> pin lightning version in full compression test

- ts/nni_manager/config/dlc/dlcUtil.py
Compatible with internal-dlc：endpoint
the interal-dlc can use workspace_id=None
verified on Alibaba PAI DLC
open alibaba pai DSW or use ECS ,follow the docs to create a file for testing.
> 【dlc】Compatible with internal-dlc and none-workspace_id

- nni/algorithms/compression/v2/pytorch/pruning/tools/sparsity_allocator.py
Use parallel operations instead of loops in `BankSparsityAllocator`
> [Compression] Improve bank sparse execution efficiency

- nni/nas/hub/pytorch/nasnet.py
- nni/nas/hub/pytorch/shufflenet.py
* Support drop path in NASNet.
* Fix auxiliary loss implementation in NASNet.
* Fix typecheck issues in ShuffleNet.
In future PR.
> Model space hub enhancements (v2.9)

- setup_ts.py
I'm not sure whether this works. We can have a try.
> Attempt to fix sqlite3 on Windows

- pipelines/fast-test.yml
- pipelines/full-test-compression.yml
- pipelines/full-test-hpo.yml
- pipelines/full-test-nas.yml
- pipelines/integration-test-aml.yml
- pipelines/integration-test-hybrid.yml
- pipelines/integration-test-local-linux.yml
- pipelines/integration-test-local-windows.yml
- pipelines/integration-test-remote-l2l.yml
- pipelines/integration-test-remote-w2w.yml
Always run pipeline everyday, so that we can aware of pipeline breaks as soon as possible.
> Run pipeline everyday regardless of code change

- ts/nni_manager/common/deferred.ts
- ts/nni_manager/common/training_service_v3.ts
- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/training_service/v3/compat.ts
- ts/nni_manager/training_service/v3/factory.ts
This is the preparation of training service v3.
It contains the new interface and one-side compatibility layer.
The compat layer allows to use a v3 training service as a v1 training service, so we can test new training services without modifying NNI manager.
> [TSv3] Step 0 - Compat layer for using v3 training service as v1

- examples/trials/mnist-pytorch/config_dlc_resource.yml
- ts/nni_manager/config/dlc/dlcUtil.py
Description
add resource_config support
ecsSpec: "{'resource_id':'rg19d2oleg252kke','cpu':2,'memory':8,'gpu':0,'gputype':'','shared_memory':''}"
Checklist
verified on Alibaba PAI DLC
How to test
open alibaba pai DSW or use ECS ,follow the docs to create a file for testing.
> [dlc] add resource prepare support

- dependencies/develop.txt
Related issue: https://github.com/PyCQA/pylint/issues/7375
> Pin pylint < 2.15

- ts/webui/src/components/experiment/overview/table/SuccessTable.tsx
- ts/webui/src/components/experiment/trialdetail/table/TableList.tsx
- ts/webui/src/components/experiment/trialdetail/table/tableFunction/CompareIndex.tsx
- ts/webui/src/static/model/searchspace.ts
- ts/webui/src/static/style/common/common.scss
- ts/webui/src/static/style/experiment/overview/count.scss
- ts/webui/src/static/style/nav/nav.scss
- ts/webui/src/static/style/nav/slideNavBtns.scss
- ts/webui/src/static/style/table.scss
- improve checkbox style
- improve expand icon style
- improve error dialog style
- some changes by `yarn stylelint --fix`
> [Ready for review] bug bash

- nni/nas/evaluator/pytorch/lightning.py
- nni/nas/fixed.py
- nni/nas/hub/pytorch/autoformer.py
- nni/nas/oneshot/pytorch/base_lightning.py
- nni/nas/oneshot/pytorch/strategy.py
- nni/nas/utils/misc.py
1. Add `no_fixed_arch()`.
2. Add `validate()` to lightning evaluator.
> Support loading supernet checkpoint in lightning

- nni/algorithms/hpo/tpe_tuner.py
- nni/common/hpo_utils/dedup.py
- nni/runtime/msg_dispatcher.py
- nni/tuner.py
- test/ut/sdk/test_builtin_tuners.py
- ts/nni_manager/common/datastore.ts
- ts/nni_manager/common/trainingService.ts
- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/test/mock/datastore.ts
- ts/nni_manager/training_service/kubernetes/adl/adlTrainingService.ts
- ts/nni_manager/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.ts
- ts/nni_manager/training_service/kubernetes/kubeflow/kubeflowTrainingService.ts
- ts/nni_manager/training_service/local/localTrainingService.ts
- ts/nni_manager/training_service/pai/paiTrainingService.ts
- ts/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
- ts/nni_manager/training_service/reusable/trialDispatcher.ts
> Revert "[FEAT]: resume waiting/running, dedup on tuner side (TPE-only)"

- docs/source/reference/nas/others.rst
- docs/source/reference/nas/strategy.rst
- docs/source/tutorials/index.rst
- nni/nas/hub/pytorch/autoformer.py
- nni/nas/nn/pytorch/mutation_utils.py
- nni/nas/oneshot/pytorch/strategy.py
Resolves some issues of documentation: some docs are missing.
> Fix missing docs (v2.9)

- README.md
- docs/source/conf.py
- docs/source/reference/nas/others.rst
- docs/source/reference/nas/strategy.rst
- docs/source/release.rst
- docs/source/tutorials/index.rst
- nni/nas/hub/pytorch/autoformer.py
- nni/nas/nn/pytorch/mutation_utils.py
- nni/nas/oneshot/pytorch/strategy.py
Cherry picked #5113 and #5114. #5111 is skipped.
> [DO NOT SQUASH] Cherry-pick commits from v2.9 branch

- nni/algorithms/compression/v2/pytorch/pruning/tools/sparsity_allocator.py
- test/algo/compression/assets/common.py
- test/algo/compression/assets/simple_mnist/simple_torch_model.py
change dependency-aware mask generation logic to generate exact sparsity and enlarge the model size.
> [Test] fix compression ut

- nni/nas/strategy/_rl_impl.py
> Fix the racing issue in RL strategy submit model

- nni/nas/evaluator/pytorch/__init__.py
> Fix import error in Lightning

- pipelines/fast-test.yml
- pipelines/full-test-compression.yml
- pipelines/full-test-hpo.yml
- pipelines/full-test-nas.yml
- pipelines/templates/stage-filter.yml
Directly install azure-pipeline-filter from github.
> [Pipeline] fix filter resource

- ts/nni_manager/common/shellUtils.ts
- ts/nni_manager/test/common/shell_utils.test.ts
- ts/nni_manager/training_service/local/localTrainingService.ts
- ts/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
- ts/nni_manager/training_service/reusable/environments/localEnvironmentService.ts
- ts/nni_manager/training_service/reusable/environments/remoteEnvironmentService.ts
Run HPO experiment on Chinese Windows. Set trial code directory to Chinese characters.
Ideally also run remote experiment using Chinese Windows server.
> Add BOM to support non-English characters in PowerShell scripts

- docs/source/conf.py
- pipelines/release.yml
- pipelines/templates/stage-filter.yml
> support sub release version > 9

- nni/mutable/symbol.py
- test/ut/sdk/mutable/test_symbol.py
This PR migrates the symbolic execution engine, which is previously embedded in NAS, to mutable, and also makes it a general utility.
> Mutable V3 (Stage 2) - Symbolic execution engine

- README.md
- docs/source/conf.py
- docs/source/release.rst
> [Do not squash] merge v2.10 back to master

- pipelines/templates/cache-dependencies-template.yml
> Fix cache dependencies pipeline

- nni/compression/pytorch/base/compressor.py
- nni/compression/pytorch/pruning/basic_pruner.py
- nni/compression/pytorch/pruning/tools/data_collector.py
- nni/compression/pytorch/speedup/compressor.py
- nni/compression/pytorch/utils/__init__.py
- nni/compression/pytorch/utils/check_ddp.py
- nni/compression/pytorch/utils/evaluator.py
Use TaylorFOWeightPruner, ActivationMeanRankPruner and ActivationAPoZRankPrune to prune a ddp model to detect whether masks on different GPUs are the same after pruning.
> fix ddp problem in ddp instead of compressor

- nni/nas/evaluator/pytorch/cgo/evaluator.py
- nni/nas/evaluator/pytorch/lightning.py
- nni/nas/oneshot/pytorch/strategy.py
- test/algo/nas/test_cgo_engine.py
- test/algo/nas/test_lightning_trainer.py
- test/algo/nas/test_oneshot.py
- test/algo/nas/test_space_hub.py
- test/algo/nas/test_space_hub_oneshot.py
- test/ut/nas/test_experiment.py
- test/ut/nas/test_nn.py
Accuracy has API change in torchmetrics 0.11.0.
> Support torchmetrics 0.11.0

- nni/contrib/compression/utils/__init__.py
- nni/contrib/compression/utils/check_ddp.py
- nni/contrib/compression/utils/constructor_helper.py
- nni/contrib/compression/utils/evaluator.py
- nni/contrib/compression/utils/scaling.py
Can be directly merge, just copy.
> [Compression] v2.5 stage 0: copy useful utils from old version

- dependencies/develop.txt
- test/ut/tools/nnictl/test_kill_command.py
> Rerun flaky tests

- examples/model_compress/pruning/taylorfo_pruning_with_ddp_torch.py
- nni/compression/pytorch/utils/check_ddp.py
> ddp_example_with_taylorFo

- ts/nni_manager/training_service/v3/compat.ts
> Fix bugs in training service v3 shim layer

- ts/nni_manager/common/command_channel/websocket.ts
- ts/nni_manager/common/globals/arguments.ts
- ts/nni_manager/common/globals/rest.ts
- ts/nni_manager/common/globals/unittest.ts
- ts/nni_manager/test/common/command_channel/websocket.test.ts
> [Remote v3] Stage 0 - WebSocket command channel server

- nni/experiment/experiment.py
experiment.kill_trial_job(trial_job_id)
> add Python API to kill a trail job

- docs/source/compression/compression_config_list.rst
- nni/contrib/compression/base/apply_method.py
- nni/contrib/compression/base/compressor.py
- nni/contrib/compression/base/config.py
- nni/contrib/compression/base/setting.py
- nni/contrib/compression/base/target_space.py
- nni/contrib/compression/base/wrapper.py
- nni/contrib/compression/example/qat_example.py
- nni/contrib/compression/quantization/qat_quantizer.py
- nni/contrib/compression/utils/check_ddp.py
- nni/contrib/compression/utils/evaluator.py
- nni/contrib/compression/utils/scaling.py
- test/algo/compression/v2_5/base/test_compressor.py
- test/algo/compression/v2_5/base/test_wrapper.py
- test/algo/compression/v2_5/utils/test_scaling.py
> [Compression] pruning stage 0: update base class & pruning utils

- nni/compression/pytorch/speedup/v2/model_speedup.py
> [Compression] allow dummy input as dict.

- nni/contrib/compression/utils/evaluator.py
> [Compression] fix bug in evaluator

- ts/nni_manager/test/common/trial_keeper/process.test.ts
https://msrasrg.visualstudio.com/NNIOpenSource/_build/results?buildId=46869&view=logs&jobId=95b93358-fda6-5c72-3eb7-ee58b0085220&j=95b93358-fda6-5c72-3eb7-ee58b0085220&t=aeef548b-dd12-5028-68b1-4892408a214b
> Increase mac os typescript ut time limit

- nni/common/concrete_trace_utils/concrete_proxy.py
- nni/contrib/compression/pruning/slim_pruner.py
1. fix slim pruner metric generation
2. fix DICT_MERGE is new in python 3.9
> [Bugbash] fix bugs in compression

- nni/common/concrete_trace_utils/concrete_tracer.py
- nni/compression/pytorch/speedup/v2/mask_updater.py
- nni/contrib/compression/base/wrapper.py
1. fix target spaces generation
2. support concrete tracer under torch >= 2.0
3. fix clone & detach in speedup
> [Bugbash] bugfix & add support for pytorch 2.0

- examples/model_compress/models/mobilenet.py
- nni/compression/pytorch/pruning/amc_pruner.py
- nni/compression/pytorch/pruning/tools/rl_env/amc_env.py
- test/ut/sdk/models/pytorch_models/mobilenet.py
Hi, thanks for the awesome work and for implementing AMC. 
I'm the first author of the AMC paper (AMC: AutoML for Model Compression and Acceleration on Mobile Devices (ECCV18))
As my project is licensed under the MIT License, I have created this pull request to ensure compliance with the license terms. In this PR, I have Included attribution comments at the top of the relevant source files that use or modify code from my project.
Thank you for your attention to this matter.
> add AMC MIT license

- nni/compression/pytorch/speedup/jit_translate.py
merge if we do not drop python 3.7 in next release.
> [Compatible py37] replace walrus op

- nni/common/concrete_trace_utils/concrete_tracer.py
- nni/common/concrete_trace_utils/utils.py
- nni/compression/pytorch/speedup/v2/model_speedup.py
- nni/compression/pytorch/speedup/v2/replacer.py
- nni/contrib/compression/base/apply_method.py
- nni/contrib/compression/base/config.py
- nni/contrib/compression/pruning/movement_pruner.py
- nni/contrib/compression/pruning/slim_pruner.py
- nni/contrib/compression/pruning/tools/calculate_metrics.py
- nni/contrib/compression/pruning/tools/sparse_gen.py
- nni/contrib/compression/utils/scaling.py
Example:
For a tensor with shape [100, 200, 300], and we want to apply block sparse with pattern [-1, -1, 1].
Previous mask shape [100, 200, 300].
Current mask shape [1, 1, 300], the mask will broadcast to [100, 200, 300] during inference.
> [Compression] optimize masks memory cost & support mask dynamic tensor shape

- nni/compression/pytorch/speedup/compress_modules.py
> [Compression] add conv1d replacer.

- nni/common/concrete_trace_utils/concrete_proxy.py
> [Common] Fix diffusers.Unet trace

- docs/source/nas/exploration_strategy.rst
- docs/source/nas/serialization.rst
> NAS doc update

- nni/experiment/data.py
- ts/nni_manager/common/datastore.ts
- ts/nni_manager/common/trainingService.ts
- ts/nni_manager/common/training_service_v3.ts
- ts/nni_manager/common/trial_keeper/collect_platform_info.ts
- ts/nni_manager/common/trial_keeper/task_scheduler/scheduler.ts
- ts/nni_manager/core/nniDataStore.ts
- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/core/sqlDatabase.ts
- ts/nni_manager/test/training_service_v3/local.test.ts
- ts/nni_manager/training_service/local_v3/local.ts
- ts/nni_manager/training_service/remote_v3/remote.ts
- ts/nni_manager/training_service/remote_v3/ssh.ts
- ts/nni_manager/training_service/remote_v3/worker.ts
- ts/nni_manager/training_service/v3/compat.ts
- ts/webui/package.json
> Fix training service bugs

- pipelines/release.yml
Ubuntu 18.04 image is no longer available.
> Bump release pipeline image

- nni/compression/pytorch/speedup/v2/mask_updater.py
- nni/compression/pytorch/speedup/v2/model_speedup.py
- nni/compression/pytorch/speedup/v2/utils.py
- nni/contrib/compression/base/config.py
> [Bugfix] fix pruning speedup value inplace change issue

- dependencies/required.txt
> Pin filelock version

- README.md
- docs/source/conf.py
- docs/source/release.rst
> Release Note of v3.0 Preview

- nni/common/concrete_trace_utils/concrete_proxy.py
> [Tracer] remove an unused attribute that causes error.

- nni/common/concrete_trace_utils/concrete_proxy.py
> [Tracer] remove an unused attribute that causes error. (#5550)

- README.md
- docs/source/conf.py
- docs/source/release.rst
> Merge v3.0rc1 back to master

- examples/compression/fusion/pd_fuse.py
- examples/compression/fusion/pqd_fuse.py
- examples/compression/pruning/norm_pruning.py
- examples/compression/pruning/scheduled_pruning.py
- examples/compression/pruning/slim_pruning.py
- examples/compression/pruning/taylor_pruning.py
> fix example config list

- ts/nni_manager/extensions/staging.ts
- ts/nni_manager/main.ts
> webui push api staging

- examples/compression/fusion/pd_fuse.py
- examples/compression/fusion/pqd_fuse.py
- examples/compression/pruning/norm_pruning.py
- examples/compression/pruning/scheduled_pruning.py
- examples/compression/pruning/slim_pruning.py
- examples/compression/pruning/taylor_pruning.py
> fix example config list (#5554)

- docs/templates/layout.html
- docs/templates/sidebar.html
The sidebar has two issues that have been fixed in this PR.
1. The logo is missing.
2. Version dropdown is missing.
> Fix several layout issues in sidebar

- nni/common/concrete_trace_utils/concrete_tracer.py
> [Common] deleted redundant GraphModule assign in concrete_tracer.py

- pipelines/cache-dependencies.yml
> Update Ubuntu version for cache dependencies pipeline

- pipelines/templates/install-dependencies.yml
> Add token for cache download pipeline

- dependencies/recommended.txt
- dependencies/recommended_gpu.txt
- dependencies/recommended_gpu_legacy.txt
- dependencies/recommended_legacy.txt
- dependencies/required.txt
- docs/source/compression/setting.rst
- nni/compression/utils/deepspeed_config.py
- nni/compression/utils/evaluator.py
> fix accelerate version bug

- dependencies/recommended.txt
- dependencies/required.txt
- docs/source/conf.py
- docs/source/release.rst
> update draft note

- dependencies/recommended.txt
- dependencies/required.txt
- docs/source/conf.py
- docs/source/release.rst
> update draft note (#5668)
