- Makefile
- src/nni_manager/common/utils.ts
- test/naive/run.py
- undefine PIP_MODE(--user) in Makefile when make in a python virtual environment
- specify the exact python from venv in common/utils
- raise exception if run.py failed so travis CI will not pass
> support travis CI and installing in python virtual environment

- src/nni_manager/common/log.ts
- Remove DeprecationWarning:
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
related to issue: #99
> remove Buffer warning

- Makefile
- src/nni_manager/common/utils.ts
- src/nni_manager/core/nnimanager.ts
> support conda (#90)

- setup.py
- src/nni_manager/core/nnimanager.ts
- src/nni_manager/core/trialJobs.ts
- tools/nnicmd/launcher.py
with this functionality, after the experiment reaches maxDuration or maxTrialNum, users still could extend maxDuration and maxTrialNum to run more trials, and submit customized trials. Restserver, tuner/assessor will not stop even reaches maxDuration or maxTrialNum. The experiment only stops when `nnictl stop` is issued. This functionality is appealing because users may want to submit/run more (customized) trials even after maxDuration or maxTrialNum is reached.
> refactor experiment stopping

- Makefile
- README.md
- docs/GetStarted.md
- docs/RemoteMachineMode.md
- setup.py
- src/sdk/pynni/setup.py
- install requirements.txt under each tuner
- small changes in Makefile on Colorful output
- change pip install to python3 -m pip install to be more robust
> Update setup.py Makefile and documents

- setup.py
- install nni's sdk and trial_tool by add flag install-options='--sdk-only' in pip install
- something like:
pip install ---install-option='--sdk-only' -v git+https://github.com/Microsoft/nni.git@v0.2
> Selectively install through pip

- README.md
- setup.py
- tools/trial_tool/trial_keeper.py
This reverts commit 1d174836d3146a0363e9c9c88094bf9cff865faa. due to potential pip install issue against pyhdfs
> Revert "Selectively install through pip (#139)" due to potential pip install issue

- src/nni_manager/training_service/pai/hdfsClientUtility.ts
- src/nni_manager/training_service/pai/paiTrainingService.ts
right now, we harded PAI container working folder to /root. However, that's not correct for Docker images whose working directory is not root. 
1. This PR is to change hard-coded root directory to $PWD in PAI container
2. Refactor time out logic for HDFSUtility and PAI token retrieval.
> Change hard-coded root directory to $PWD in PAI container

- CONTRIBUTING.md
- README.md
- docs/CONTRIBUTING.md
- docs/HowToContribute.md
- Add a sample Contributing document for new contributors to read and refer from. 
- Linked docs folder with contributing 
- Add CONTRIBUTING and License header in README
- Please suggest any changes. 
- Solves #164 
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
> Add CONTRIBUTING

- Makefile
- pip install also rely on install-node-modules target, whose pwd is uncertain so that cp will fail
> quick fix for Makefile

- docs/ExperimentConfig.md
- src/webui/src/components/Sessionpro.tsx
Typo, 'successed' is not a word.
> fix: Fix typo successed, 'successed' is not a word

- src/webui/src/components/Para.tsx
- src/webui/src/components/Sessionpro.tsx
support more search space;
change maxDuration and still running style.
> Support more search space and maxDuration format

- src/sdk/pynni/nni/README.md
> Typo on paragraph #22

- src/webui/src/components/Overview.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/SuccessTable.tsx
- src/webui/src/components/trial-detail/Para.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/function.ts
- src/webui/src/static/interface.ts
- src/webui/src/static/style/table.scss
1. support default object
2. fix bug of accuracy graph
3. table style: duration right, id left
> Fix bugs for v0.3

- src/webui/src/components/Overview.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/SuccessTable.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/interface.ts
- src/webui/src/static/style/trialsDetail.scss
1. Add more tooltips in default metric graph
2. Fix bug about download experiment in Edge, and down json file
3. Add sort func in default and duration column
4. show more detail error message when user kill job failed
5. Trial Accuracy -> Default Metric
> Add more tooltips in default metric graph

- src/webui/src/components/SlideBar.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/Progress.tsx
- src/webui/src/components/trial-detail/Duration.tsx
- src/webui/src/components/trial-detail/Para.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/interface.ts
- src/webui/src/static/style/logPath.scss
1. fix search trial bug and remaining bug (double check remaining >= 0)
2. add select btn in search space graph color bar
3. click the NNI logo, link to overview page
4. show intermediate results in open row
> Show intermediate results

- src/nni_manager/common/trainingService.ts
- src/nni_manager/common/utils.ts
- src/nni_manager/core/nniDataStore.ts
- src/nni_manager/core/nnimanager.ts
- src/nni_manager/core/test/mockedDatastore.ts
- src/nni_manager/core/test/mockedTrainingService.ts
- src/nni_manager/scripts/metrics_reader.py
- src/nni_manager/training_service/kubeflow/kubeflowTrainingService.ts
- src/nni_manager/training_service/local/localTrainingService.ts
- src/nni_manager/training_service/pai/paiJobInfoCollector.ts
- src/nni_manager/training_service/pai/paiTrainingService.ts
- src/nni_manager/training_service/remote_machine/metricsCollector.ts
- src/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
add one more trial job status 'EARLY_STOPPED' for the trial jobs killed by assessor.
1. modified all the training services, nnimanager, nnidatastore.
2. webui has not been modified accordingly
3. one blocking issue in metrics_reader.py
> Fix trialjobstate

- src/nni_manager/common/manager.ts
- src/nni_manager/core/nnimanager.ts
tuners such as batchtuner, gridsearch have finite configurations, and will send NO_MORE_TRIAL to nnimanager after tried all the configurations. In this pr, nnimanager sets the experiment state to NO_MORE_TRIAL when received command NO_MORE_TRIAL from tuner.
fix catch error in resumeExperiment().
TODO: 1. update webui accordingly; 2. check tuners correctly uses NO_MORE_TRIAL.
> add NO_MORE_TRIAL state in experiment

- docs/ExperimentConfig.md
- docs/KubeflowMode.md
- tools/nni_cmd/config_schema.py
- tools/nni_cmd/constants.py
- tools/nni_cmd/launcher_utils.py
- tools/nni_cmd/nnictl_utils.py
1. move nnictl folder
2. delete kubernetsServer in nnictl
3. refactor aks document
4. add warning information to expand relative path
5. update experiment status when the experiment crashed.
> Update document v0.4

- src/webui/src/components/TrialsDetail.tsx
I changed the name searchTrialNo to searchTrial. Now it checks whether the search value is a substring of one of the "Trail Ids". I chose to do substring so the user doesn't need to remember the whole id string and can get the trial. If that's something you don't want, i can change it to match exactly easily.
One issue I noticed during training is that the table stop updating once I searched something. Originally the table and the chart are updated when the status of a trail is finished or a new trial is started. 
Should I create a new issue?
> added search trial by id function

- src/nni_manager/training_service/kubernetes/kubernetesTrainingService.ts
- src/nni_manager/training_service/pai/paiTrainingService.ts
- src/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
trial job could not be stopped in remote machine when experiment is stopped, because awit/async does not work normally in forEach, refer https://codeburst.io/javascript-async-await-with-foreach-b6ba62bbf404.
fix issue: https://github.com/Microsoft/nni/issues/558
> Fix remote TrainingService bug, change forEach to "for of"

- tools/nni_cmd/launcher.py
- Similar to resolving permissions issues during installation, here we create a folder for every user under.
- So it guarantees that the user has write access to the folder
> fix annotation permission deny

- src/webui/src/components/Overview.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/Progress.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/const.ts
- src/webui/src/static/function.ts
- src/webui/src/static/interface.ts
- src/webui/src/static/style/search.scss
> [WebUI] Fix issue#458 about final result as dict

- src/nni_manager/core/nnimanager.ts
Fix the bug that when a finished experiment (state is DONE) is resumed, its state is always NO_MORE_TRIAL.
> fix experiment state bug

- src/sdk/pynni/nni/smac_tuner/convert_ss_to_scenario.py
- src/sdk/pynni/nni/smac_tuner/smac_tuner.py
in nni 0.5 and higher, mnist-annotation example cannot be tuned by SMAC tuner, because SMAC cannot parse categorical values which include ",() ". In this pr, we fixed this problem.
> fix bug in smac that configspace cannot deal with complex searchspace

- src/nni_manager/common/trainingService.ts
- src/nni_manager/training_service/kubernetes/kubeflow/kubeflowJobInfoCollector.ts
- src/nni_manager/training_service/pai/paiData.ts
- src/nni_manager/training_service/pai/paiJobInfoCollector.ts
- src/nni_manager/training_service/pai/paiTrainingService.ts
- src/nni_manager/training_service/remote_machine/remoteMachineData.ts
- src/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
1. For PAITrainingService, we should rely on the status returned from PAI rest server to change trial job's status, rather than setting it's cancelling status in cancelTrialJob() method, because jobInfoCollector will then reset job's status based on PAI rest server's result. 
2. For RemoteMachineTrainingService, it almost the same, we should not set trial's status in cancelTrialJob() method.
> Fix a race condition bug that does not store Trial Job cancel status correctly

- src/sdk/pynni/nni/hyperband_advisor/hyperband_advisor.py
When we calculate 
`self.s_max = math.floor(math.log(self.R, self.eta))`
in Hyperband, we may cause a scientific calculation errors.
For example, R = 243(3^5), eta = 3, then s_max should be 5, but math.log(243, 3) = 4.999999...... That will make s_max turn to 4.
Solution: add epsilon(=1e-6) behind the expression to carry.
> Solve bug caused by scientific calculation errors

- docs/en_US/PAIMode.md
> Fix typo in doc

- docs/en_US/Contribution.rst
- docs/en_US/Trials.md
- docs/en_US/Tutorials.rst
> Update Trial's doc and move HowToDebug to Tutorial

- src/sdk/pynni/nni/smac_tuner/smac_tuner.py
**fix the bug:** 
Traceback (most recent call last):
File "/data/anaconda/envs/reco_base/lib/python3.6/site-packages/nni/__main__.py", line 189, in main
dispatcher.run()
File "/data/anaconda/envs/reco_base/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 63, in run
self.handle_request((command, data))
File "/data/anaconda/envs/reco_base/lib/python3.6/site-packages/nni/msg_dispatcher_base.py", line 105, in handle_request
return command_handlers[command](data)
File "/data/anaconda/envs/reco_base/lib/python3.6/site-packages/nni/msg_dispatcher.py", line 101, in handle_request_trial_jobs
params_list = self.tuner.generate_multiple_parameters(ids)
File "/data/anaconda/envs/reco_base/lib/python3.6/site-packages/nni/smac_tuner/smac_tuner.py", line 262, in generate_multiple_parameters …
> fix bug in smac search space convert

- src/sdk/pynni/nni/metis_tuner/Regression_GP/CreateModel.py
- src/sdk/pynni/nni/metis_tuner/metis_tuner.py
1. Remove the debug information which can cause error.
2. Increase 'alpha' parameter of GaussianProcessRegressor to make sure a positive definite matrix.
3. Increase the probability of exploration from 0.1 to 0.9 to select from next config.
> Fix for MetisTuner

- Makefile
PR for #709, which is related to an open [https://github.com/pypa/pip/issues/3160](issue) of pypi.
That is, editable install does not work with package_directory (or namespace or sub-package)
Currently we figure out a temporary remedy.
When users want to `dev-install`, we'll firstly create **soft links** to **all python package** and put them all in a newly built directory under the root directory. Then we modify `setup.py` and throw it into that directory and run `pip install` command.
> Fix bugs of dev-install caused by composition of the two packages

- docs/en_US/multiPhase.md
Make multi-phase doc more clear.
> update multi-phase doc

- src/nni_manager/common/utils.ts
- src/nni_manager/package.json
According to [this commit](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/92ee9c22b5740595bc0475008e8ac5952954aa76) (more specifically, this [file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/92ee9c22b5740595bc0475008e8ac5952954aa76/types/node/v10/fs.d.ts#L728)), node's API for mkdir has changed, which causes NNI cannot be compile correctly.
This is because the prototype of fs.mkdir's callback function has changed.
We should further discuss how to fix the previous version of NNI. Maybe it will be better to fix the version of node.
> Fix for master -- Node's API changes

- docs/en_US/NNICTLDOC.md
- src/nni_manager/common/utils.ts
- src/sdk/pynni/nni/bohb_advisor/bohb_advisor.py
- src/sdk/pynni/nni/gridsearch_tuner/gridsearch_tuner.py
- src/sdk/pynni/nni/hyperopt_tuner/hyperopt_tuner.py
- src/sdk/pynni/nni/metis_tuner/metis_tuner.py
1. Fix parenthesis match error in the source code.
2. Fix bug in NNICTL document. The implementation in the code is --filename instead of --file.
> Fix bug in import data feature

- src/sdk/pynni/nni/bohb_advisor/bohb_advisor.py
- src/sdk/pynni/nni/gridsearch_tuner/gridsearch_tuner.py
- src/sdk/pynni/nni/hyperopt_tuner/hyperopt_tuner.py
- src/sdk/pynni/nni/metis_tuner/metis_tuner.py
- tools/nni_cmd/updater.py
Solution: add a conversion function to convert the parameter into an acceptable format in TPE
> Fix bug bash of import data feature

- examples/trials/ga_squad/requirements.txt
- examples/trials/network_morphism/requirements.txt
Tensorflow version before 1.12.2 has security issue which is extracted from here by github:
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=tensorflow
I upgrade Tensorflow version to 1.13.1 and test it successfully in local environment.
> Upgrade tensorflow version in the ga_squad and network_morphism examples.

- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/trial-detail/Para.tsx
#1054 
1. fix bug of table entries. when select "all" and then table message update, table is paging again.
2. when only one succeed trial, {
>. fix bug of color bar max value is 190
>. hyper-parameter top select use Math.ceil() to avoid lost data
}
3. table search case-insensitive
> fix bug of table entries

- src/nni_manager/training_service/local/gpuScheduler.ts
issue #1037 
For Windows, there may be inevitable processes occupying the gpu while gpu utilization is low. The change is to use all gpus in Windows rather than filtering out the gpus that no process running on. The risk is that OOM error may happen due to the gpu memory is not enough for the new job.
> Fix Windows available gpu

- docs/en_US/GeneralNasInterfaces.md
BTW, https://github.com/microsoft/nni/compare/dev-nas-interface...gaocegege:fix?expand=1#diff-54110dc95f0ab52fce522a39c017a505L142 is 404, but I cannot find a copy for it. Actually, all papers in ICML'18 are 404.
PTAL
Signed-off-by: Ce Gao <gaoce@caicloud.io>
> fix: Fix a typo

- src/webui/src/components/trial-detail/Para.tsx
randint(high) -> randint(low, high)
fix issue #1144
> fix bug of randint in hyper-parameter graph

- src/webui/src/components/trial-detail/Para.tsx
- src/webui/src/components/trial-detail/TableList.tsx
1. randint range [lower,upper]
2. duration column do not support to show 0.333s.
fix two problem:
> randint range, duration less than 1

- src/sdk/pynni/nni/bohb_advisor/requirements.txt
- tools/nni_cmd/nnictl_utils.py
issue #1098
incompatability between scipy and statsmodel --> refer to [this issue](https://github.com/statsmodels/statsmodels/issues/5759)
since statsmodel has been updated from 0.9.0 to 0.10.0　
issue #1292
there's a bug about nnictl stop experiment in this PR #1216 .  `all` remains an option in args in `nnictl.py` but is used as a boolean value in `nnictl_utils.py`
> Fix bug of nnictl about stopping experiment and update statsmodels version to v0.9.1.1

- docs/en_US/Release.md
Fixed broken links of Release.md
> issue#1306Fixed broken links of Release.md 

- docs/en_US/Tutorial/Nnictl.md
- docs/zh_CN/Nnictl.md
- test/naive_test.py
- tools/nni_cmd/nnictl.py
- tools/nni_cmd/nnictl_utils.py
Issue #1359 
~~Maybe we should update docs as well.~~
~~But I don't know where.~~
> Let nnictl support stopping by port

- src/webui/src/components/trial-detail/Para.tsx
#1397 
`type: 'log'` doesn't support one line.
so set log distributed when lines' length > 1.
> fix bug of hyper-parameter graph when search space has loguniform type

- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/trial-detail/DefaultMetricPoint.tsx
- src/webui/src/components/trial-detail/Intermeidate.tsx
- src/webui/src/static/interface.ts
- src/webui/src/static/style/para.scss
- src/webui/src/static/style/table.scss
- src/webui/src/static/style/trialsDetail.scss
#1218 
1. when user set `optimize_mode: maximize`, best metric graph is: 
and default metric graph is:
2. when user set `optimize_mode: minimize`, best metric graph is: 
3. the filed `optimize_mode: minimize |  maximize` is from tuner.classArgs.optimize_mode
> [Fixed issue#1218 V2] Show the best metric curve during search progress in webui

- src/webui/src/components/Modal/Compare.tsx
- src/webui/src/components/trial-detail/Intermeidate.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/const.ts
- src/webui/src/static/style/compare.scss
- src/webui/src/static/style/para.scss
- src/webui/src/static/style/progress.scss
- src/webui/src/static/style/table.scss
- src/webui/src/static/style/trialsDetail.scss
related changes:
- ![image](https://user-images.githubusercontent.com/35484733/62422524-96c90300-b6e6-11e9-8801-f91df6c1819a.png)
- ![image](https://user-images.githubusercontent.com/35484733/62422531-a8120f80-b6e6-11e9-8408-165d29654837.png)
- ![image](https://user-images.githubusercontent.com/35484733/62422538-bc560c80-b6e6-11e9-837b-54ceea22eca0.png)
- ![image](https://user-images.githubusercontent.com/35484733/62436585-b279eb00-b772-11e9-8ea8-376614661083.png)
> Add intermediate count column to show trial progress

- src/webui/package.json
- src/webui/yarn.lock
In PR #1412 , I removed most `resolutions` after upgrading dependencies.
Seems one of them is still needed.
> Try to fix security alert

- src/nni_manager/training_service/common/util.ts
- src/nni_manager/training_service/local/gpuScheduler.ts
- src/nni_manager/training_service/local/localTrainingService.ts
This is a hotfix for issue #1433
When NNI runs in local mode, it will create folder `/tmp/nni` with permission 755 or 775.
If then another user uses the same machine as a remote server, NNI will fail because it does not have the permission to create `/tmp/nni/experiments`.
We may consider move experiment directories to `/tmp/$USER/nni` in next version.
> Hotfix for /tmp/nni permission problem

- docs/en_US/Tuner/SmacTuner.md
- docs/zh_CN/Tuner/SmacTuner.md
- src/sdk/pynni/nni/smac_tuner/convert_ss_to_scenario.py
Previous version: SMAC in nni supports quniform only when q=1;
After : use "ordinal" type in SMAC to parse quniform
reference: 
- https://automl.github.io/SMAC3/dev/options.html
- https://www.cs.ubc.ca/labs/beta/Projects/SMAC/v2.10.02/manual.pdf
> fix smac quniform issue

- docs/en_US/TrainingService/LocalMode.md
- docs/en_US/Tutorial/SearchSpaceSpec.md
#1475 
According to @lvybriage , there are still some problems and ambiguities when displaying on hyper-parameter page if we allow users to define a search space of choice like `[null, "128", 256, 512]`. The quick yet elegant solution is to add a "disclaimer" in the documentation that a search space like this might cause undefined behaviors.
This PR also refines the docs of that part by fixing a few issues and typos.
> Rewrite search space documentation for choice

- src/sdk/pynni/nni/nas_utils.py
- src/sdk/pynni/nni/smartparam.py
- src/sdk/pynni/nni/trial.py
Currently, there are a few usage of `trial._params`, which I believe is a bad practice, since the underline is a sign of "don't use it outside this module".
By making tag an optional argument, I can retrieve `trial._params` by using `get_current_parameter`. The main reason I want to do this, instead of refactor it into `has_current_parameter` is that, I'm currently implementing something in NAS that needs to retrieve current parameter multiple times. #1432
> Refactor get_current_parameter to avoid using trial._params

- src/webui/src/static/const.ts
- tools/nni_cmd/launcher_utils.py
When the schema is wrong, nnictl prints nothing useful. Basically, this is due to the mishandling of the error information generated by `schema`.
Before this change, it would look like this:
```
INFO: expand searchSpacePath: search_space.json to /home/xxx/projects/nni/examples/trials/mnist/search_space.json 
INFO: expand codeDir: . to /home/xxx/projects/nni/examples/trials/mnist/. 
ERROR: Your config file is not correct, please check your config file content!
ERROR: Key 'trial' error:
```
After this change, it now looks like this:
```
INFO: expand searchSpacePath: search_space.json to /home/xxx/projects/nni/examples/trials/mnist/search_space.json 
INFO: expand codeDir: . to /home/xxx/projects/nni/examples/trials/mnist/. 
ERROR: Your config file is not correct, please check your config …
```
> Print error detail on schema validation failure

- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/const.ts
- src/webui/src/static/interface.ts
This PR fixed issue #1492
StartTime/EndTime column is hidden by default.
If hasn't the time, will show '--'
> Show startTime and endTime as table additory columns

- src/webui/src/components/trial-detail/Para.tsx
This PR supports the example `mnist-nested-search-space` and fix the issue #1110.
At present, we only support `choice` type for netst search space.
Like this:
> Support netst search space

- src/webui/src/components/Modal/Compare.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/overview/Progress.tsx
- src/webui/src/components/public-child/OpenRow.tsx
- src/webui/src/components/trial-detail/DefaultMetricPoint.tsx
- src/webui/src/components/trial-detail/Intermediate.tsx
- src/webui/src/components/trial-detail/Para.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/const.ts
1.  the column `Intermediate count` rename `Intermediate result`
2.  add `search space` column options
3. add scroll-x with many columns
4. This PR also fix hyper parameter issue.
fixed the `Parameters` style when hover in the default metric graph.
before:
update:
5. 同4， `Parameters` 
before:
update:
> add search space key as table additional column

- tools/nni_annotation/code_generator.py
- tools/nni_annotation/search_space_generator.py
- tools/nni_annotation/specific_code_generator.py
Fix #1560, and prettify some of the codes to conform with PEP 8.
> Add support for @nni.training_update in codegen

- src/webui/src/index.css
Fixed the sequencing of the font attributes to ensure that the parent attributes are not overwritten
> Fixed the sequencing of the font attributes

- src/nni_manager/common/utils.ts
- src/nni_manager/training_service/common/util.ts
- src/nni_manager/training_service/local/localTrainingService.ts
Fix #1367. Trials fail because there is a name called `cmd` produced by Anaconda in environment path. Use `cmd.exe` instead.
> Use cmd.exe to avoid name conflicts of cmd

- src/sdk/pynni/nni/compression/torch/builtin_pruners.py
> fix builtin pruners bug

- tools/nni_cmd/command_utils.py
> Fix package installation in virtualenv and conda

- src/webui/src/App.tsx
- src/webui/src/components/Overview.tsx
`Fix bug`:  当用户从 `detail`页面切回到 `overview`页面时，保留用户的选择
> [webui] Maintain selected status when the page switched

- test/pipelines-it-installation.yml
Only test pip install for now, will add more installation test later.
This test is scheduled daily.
> Installation test pipeline

- README.md
[scikit-nni](https://github.com/ksachdeva/scikit-nni) is an external repo which uses NNI to tune hyper-parameters of scikit-learn pipelines. Thanks for the contribution.
> update readme to reference scikit-nni, an external repo and an article

- src/nni_manager/training_service/common/gpuData.ts
- src/nni_manager/training_service/common/util.ts
- src/nni_manager/training_service/local/gpuScheduler.ts
- src/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
- tools/nni_gpu_tool/gpu_metrics_collector.py
Fix issue #1665 
Solution: Don't create script on Linux, use one-line command instead. Windows routine is not modified.
> fix gpu script permission issue

- src/sdk/pynni/nni/common.py
- src/sdk/pynni/nni/platform/standalone.py
- src/sdk/pynni/nni/trial.py
This is a improved version of PR #1761 , which fixes issue #1740
> Improve logging for standalone mode

- docs/en_US/TrainingService/LocalMode.md
- docs/en_US/TrainingService/PaiMode.md
- docs/en_US/TrainingService/RemoteMachineMode.md
- docs/zh_CN/TrainingService/LocalMode.md
- docs/zh_CN/TrainingService/PaiMode.md
- docs/zh_CN/TrainingService/RemoteMachineMode.md
Added the option `searchSpacePath` in the yaml configuration file of the document. If this option is missing, it will cause nni to report an error.
> modify docs

- docs/en_US/Compressor/SlimPruner.md
- examples/model_compress/slim_pruner_torch_vgg19.py
- src/sdk/pynni/nni/compression/torch/builtin_pruners.py
- src/sdk/pynni/tests/test_compressor.py
add l1filter_pruner and slim_pruner unit test
> add pruner unit test

- src/webui/package.json
- src/webui/src/components/trial-detail/DefaultMetricPoint.tsx
- src/webui/src/components/trial-detail/Duration.tsx
- src/webui/src/components/trial-detail/Intermediate.tsx
- src/webui/src/components/trial-detail/Para.tsx
- src/webui/src/static/interface.ts
- src/webui/yarn.lock
1. default metric graph: 支持鼠标滚轴缩放扩大效果，Y轴变化
2. Trial duration: 支持鼠标滚轴缩放扩大效果，Y轴变化，X轴保持不变
3. Intermediate Result: 支持鼠标滚轴缩放扩大效果，Y轴变化，X轴保持不变
4. Hyper-parameter graph: To Do. I have a issue in echarts, will support in other PR.
5. hyper-parameter graph default metric轴数值实时计算
6. hyper-parameter graph yAxis values should be not bold. [Echarts Issue](https://github.com/apache/incubator-echarts/issues/11685)
Please help review this PR.
> add dataZoom for graph

- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/function.ts
- src/webui/src/static/interface.ts
- src/webui/src/static/model/trial.ts
Fix issue #1764
If a trial haven't any metric, it will always in the final row when we sort these trials.
> Fix table sort issue

- test/pipelines-it-local-windows.yml
- test/unittest.ps1
Unittests fail on IT because of stderr output. Redirect to stdout for now and turn on exitcode check.
> Fix pipeline with workarounds in windows unittests (merge into master)

- docs/en_US/Overview.md
- docs/en_US/TrialExample/Trials.md
- docs/en_US/Tutorial/HowToDebug.md
describe core capacities of NNI, including hyperparameter tuning, neural architecture search, model compression, and feature engineering.
describe standalone mode, in which trial code can run without NNI experiment for easy debug.
> update doc: NNI core capacities in Overview.md, standalone mode in Trials.md

- tools/bash-completion
1. Support bash lower than 4.4 (assuming nobody uses 3.x)
2. Add "view" command
> Fix bash completion bugs

- docs/en_US/Tuner/BuiltinTuner.md
- src/sdk/pynni/nni/smac_tuner/smac_tuner.py
- tools/nni_cmd/config_schema.py
when `config_dedup` is True, a configuration will not be generated more than once
> support trial config deduplication in SMAC tuner

- src/sdk/pynni/nni/nas/pytorch/callbacks.py
- src/sdk/pynni/nni/nas/pytorch/classic_nas/__init__.py
- src/sdk/pynni/nni/nas/pytorch/classic_nas/mutator.py
- src/sdk/pynni/nni/nas/pytorch/mutator.py
- src/sdk/pynni/nni/nas/pytorch/utils.py
- tools/nni_cmd/nnictl_utils.py
1. Use mutator instead of BaseMutator as base class to simplify the code.
2. Add more validation to detect possible errors and give reasonable error messages.
3. Fix bug when search space path is an absolute path.
New utility functions in preparation for SPOS:
1. ModelCheckpoint
2. Add access shortcut for average meters.
> Improve Classic NAS mutator

- src/sdk/pynni/nni/gridsearch_tuner/gridsearch_tuner.py
- src/sdk/pynni/nni/hyperopt_tuner/hyperopt_tuner.py
- src/sdk/pynni/tests/assets/search_space.json
- src/sdk/pynni/tests/test_builtin_tuners.py
> Strengthen builtin tuners UT and fix hyperopt randint

- examples/model_compress/lottery_torch_mnist_fc.py
- examples/model_compress/multi_gpu.py
- src/sdk/pynni/nni/compression/torch/compressor.py
- src/sdk/pynni/nni/compression/torch/pruners.py
1. update lottery ticket pruner based on refactored compression code
2. fix bug: allow users to specify device of the model when exporting mask and model, used to place dummy input tensor for exporting onnx model.
> update lottery ticket pruner based on refactored compression code

- src/sdk/pynni/nni/compression/torch/pruners.py
This fix is straightforward and two developers agree with this fix. So, I think it can be merged into the master branch directly.
> Fix issue #2005 (https://github.com/microsoft/nni/issues/2005)

- docs/en_US/FeatureEngineering/Overview.md
FeatureEngineering/Overview.md
It explains FeatureEngineering and import GradientFeatureSelector.
But GradientFeatureSelector is not existed.
I think it is the typo and I get the following error: 
`ImportError: cannot import name 'GradientFeatureSelector'`
If you look at this document, you'll notice that it's correct `FeatureGradientSelector`.
> Fixed Typo READMD.md

- src/sdk/pynni/nni/compression/torch/compressor.py
fix model compression config validation.
rules:
only check op_types and op_names if they are in config file, skip checking otherwise.
> fix model compression config validation

- src/webui/src/components/NavCon.tsx
- src/webui/src/components/TrialsDetail.tsx
- src/webui/src/components/trial-detail/TableList.tsx
fix issue #2057 
- refresh interval selectors doesn't work
- defatult metric sort is not correctly in details table, it's disordered when latest | final | --
- search trials by id | parameters, tooltip "Unexpected search filter Id" | "...parameters"
this item `点击空白处可以关闭log modal`:
add `isLightDismiss={true}` for Panel , but it doesn't work in the test. will continue to fix it in another PR.
> fix some bugs in v1.4 bug bash

- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/function.ts
Update WebUI for metrics data changing to json string
> Update WebUI for metrics data changing to json string

- src/webui/src/components/Modals/ChangeColumnComponent.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/function.ts
- src/webui/src/static/interface.ts
- src/webui/src/static/model/trial.ts
- src/webui/src/static/style/search.scss
- src/webui/src/static/style/table.scss
final | intermeidate dictionary:
- table show default metrics
- click `addColumn` could show other keys
- intermediate button -> modal shows all intermeidate metrics
> [WebUI] Support dictionary metrics includes table defatule metirc | addcolumn | intermeidate result modal

- src/webui/src/components/trial-detail/TableList.tsx
fix: column list更新不及时，dict column出现随机
dictionary metrics: show origin data
> fix bug of dict column list

- src/nni_manager/config/kubeflow/pytorchjob-crd-v1.json
- src/nni_manager/training_service/kubernetes/kubeflow/kubeflowApiClient.ts
- src/nni_manager/training_service/kubernetes/kubeflow/kubeflowConfig.ts
As supported by kubeflow 0.7,  the new crd version ```v1``` has been added for ```TFJob``` about two month ago via commit #1814 . So the version ```v1```  should be added for ```PyTorchJob```
> add support for pytorchjob crd version 'v1'

- azure-pipelines.yml
Turns out that macOS image has a built-in swig. Removing the soft link.
macOS 10.13 is upgraded to 10.15 by the request of Azure pipeline warning.
> Fix swig version at 3 and upgrade macOS image version

- src/sdk/pynni/nni/curvefitting_assessor/curvefitting_assessor.py
- src/sdk/pynni/nni/medianstop_assessor/medianstop_assessor.py
- src/sdk/pynni/nni/msg_dispatcher.py
- src/sdk/pynni/nni/utils.py
1. make assessors support metric data in dict
2. fix bug when `includeIntermediateResults` is true
> make assessors support metric data in dict

- examples/model_compress/model_prune_torch.py
- examples/trials/mnist-pytorch/mnist.py
- src/sdk/pynni/nni/compression/torch/activation_rank_filter_pruners.py
- src/sdk/pynni/nni/compression/torch/compressor.py
- src/sdk/pynni/nni/compression/torch/pruners.py
- src/sdk/pynni/nni/compression/torch/weight_rank_filter_pruners.py
- src/sdk/pynni/nni/curvefitting_assessor/curvefitting_assessor.py
- src/sdk/pynni/nni/medianstop_assessor/medianstop_assessor.py
- src/sdk/pynni/nni/msg_dispatcher.py
- src/sdk/pynni/nni/utils.py
- src/sdk/pynni/tests/test_compressor.py
- src/webui/src/components/Modals/CustomizedTrial.tsx
- test/generate_ts_config.py
1. Change optimizer to an optional parameter for pruner
2. Fix an pruner example bug
> Compressor updates

- docs/en_US/Assessor/BuiltinAssessor.md
- docs/en_US/Assessor/CurvefittingAssessor.md
- docs/en_US/Assessor/MedianstopAssessor.md
- docs/en_US/NAS/NasGuide.md
- docs/en_US/NAS/Overview.md
- docs/en_US/NAS/QuickStart.md
- docs/en_US/Overview.md
- docs/en_US/TrialExample/Trials.md
- docs/en_US/Tuner/BatchTuner.md
- docs/en_US/Tuner/BohbAdvisor.md
- docs/en_US/Tuner/BuiltinTuner.md
- docs/en_US/Tuner/EvolutionTuner.md
- docs/en_US/Tuner/GPTuner.md
- docs/en_US/Tuner/GridsearchTuner.md
- docs/en_US/Tuner/HyperbandAdvisor.md
- docs/en_US/Tuner/HyperoptTuner.md
- docs/en_US/Tuner/MetisTuner.md
- docs/en_US/Tuner/NetworkmorphismTuner.md
- docs/en_US/Tuner/PPOTuner.md
- docs/en_US/Tuner/SmacTuner.md
- docs/en_US/Tutorial/HowToUseDocker.md
- docs/en_US/Tutorial/InstallationLinux.md
- docs/en_US/Tutorial/InstallationWin.md
- docs/en_US/Tutorial/QuickStart.md
- docs/en_US/Tutorial/WebUI.md
- docs/en_US/builtin_assessor.rst
- docs/en_US/builtin_tuner.rst
- docs/en_US/hyperparameter_tune.rst
- docs/en_US/installation.rst
I found reading through much of the documentation to be pretty frustrating and decided to dedicate some time to fix some of it. This pull request covers the overview, installation, quickstart, most of hyperparameter tuning, and the overview, quickstart, and tutorial for the NAS. Originally, I wanted to cover more, but I lost interest in the face of other, more pressing projects. I figured I'd make a pull request for what's done so that work doesn't go to waste.
I cannot guarantee that every problem is fixed, but the covered docs are far more readable with these changes.
> Improve grammar, spelling, and wording within the English documentation.

- examples/model_compress/model_prune_torch.py
- examples/model_compress/model_speedup.py
- examples/trials/mnist-pytorch/mnist.py
- test/config/examples/mnist-pytorch.yml
- test/config/integration_tests.yml
- test/config/pr_tests.yml
- test/nni_test/nnitest/validators.py
- test/scripts/model_compression.sh
1. Enable / Fix dict metrics test
2. Fix model speedup test
3. Fix mnist-pytorch is too slow on PAI
> Fix integration tests

- examples/nas/darts/search.py
- examples/nas/enas/search.py
- examples/nas/naive/train.py
- src/sdk/pynni/nni/nas/pytorch/darts/trainer.py
- src/sdk/pynni/nni/nas/pytorch/enas/trainer.py
- src/sdk/pynni/nni/nas/pytorch/trainer.py
Users can use `trainer.enable_visualization()` before `train()` to enable visualization.
> Enable visualization in examples

- test/config/naive_trial/naive_trial.py
- test/config/pr_tests.yml
The Memory/CPU resource of azure provided hosts are very limited, it seems 20 intermediate results of each trial is too much, and causing problems on Windows.  It appears changing to 2 intermediate result for each trial solved the problem.
There is no intermediate result in the PR test cases in v1.4 and before,  and 20 intermediate results were added into each trial job in recent test refactoring.
> Update pr test cases for windows (#2267)

- test/nni_test/nnitest/run_tests.py
- test/nni_test/nnitest/utils.py
Fix issue #2290
Show experiment log when:
1.  Failed to retrieve experiment info via rest api
2.  Validator fails.
> Show more log info for failed test cases

- src/webui/src/components/overview/SuccessTable.tsx
- src/webui/src/static/style/succTable.scss
design：https://user-images.githubusercontent.com/44491713/76310664-33e9bb00-630a-11ea-917a-914eee78a6b2.png
> add tooltip when there is no data in overview table

- examples/nas/classic_nas/mnist.py
- examples/nas/darts/model.py
- examples/nas/spos/network.py
- src/sdk/pynni/nni/nas/pytorch/classic_nas/mutator.py
- src/sdk/pynni/nni/nas/pytorch/mutables.py
I'm bringing changes into NAS step by step. For this PR,
API change:
* `op_candidates` support `OrderedDict` now (#2112)
* Modules are stored without a `choices` layer, by directly being added into LayerChoice. For example, `op_choices.choices.0.bn` will be changed into `op_choices.0.bn`. Note that this will be a breaking change to all previously trained checkpoint.
* Add attributed `names` to LayerChoice that stores all the verbose names.
Usability improvement:
* Classic NAS now uses a more friendly naming pattern:
```
{
"first_conv": {
"_type": "layer_choice",
"_value": [
"conv5x5",
"conv3x3"
]
},
"mid_conv": {
"_type": "layer_choice",
"_value": [
"0",
"1"
]
},
"skip": {
"_type": "input_choice",
"_value": {
"candidates": [
"",
""
],
"n_chosen": 1
}
}
}
```
* Expand modules in mutables …
> Support OrderedDict for LayerChoice

- .gitignore
- Makefile
- docs/en_US/Tutorial/SetupNniDeveloperEnvironment.md
- src/nni_manager/package.json
- src/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
- src/nni_manager/training_service/remote_machine/sshClientUtility.ts
- src/webui/yarn.lock
- tools/nni_gpu_tool/gpu_metrics_collector.py
Add shell support for ssh connection, so that remote script can be started with user environment.
Minor fixes,
1. Fix gpu_metrics_collector to support pyenv. As pyenv will create one more process, so that original pgrep code always got extra processes, and cannot start gpu_metrics_collector.
2. Fix NASUI failure on dev-install-node-modules, to create subfolder every time.
3. Fix MakeFile to reduce mis-created links, and other minor issues.
4. Add node --watch for nni_manager for better dev experience.
#1578
> fix #1578 and some improvements

- test/config/integration_tests.yml
- test/nni_test/nnitest/validators.py
- tools/nni_cmd/nnictl_utils.py
fix `nnictl experiment export` with the following error:
```python
Traceback (most recent call last):
File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Program Files\Python37\Scripts\nnictl.exe\__main__.py", line 9, in <module>
File "c:\program files\python37\lib\site-packages\nni_cmd\nnictl.py", line 219, in parse_args
args.func(args)
File "c:\program files\python37\lib\site-packages\nni_cmd\nnictl_utils.py", line 694, in export_trials_data
raise(e)
File "c:\program files\python37\lib\site-packages\nni_cmd\nnictl_utils.py", line 689, in export_trials_data
formated_record = {**record['parameter'], **record['value'], **{'id': …
```
> fix trial export

- src/nni_manager/training_service/dlts/dltsTrainingService.ts
Previously, DLTS training service is using Kubernetes internal network to make to connections between different workers, which is not supported by all deployments.
This PR is switching it into **job endpoints**, which is officially supported by DLTS. Therefore, a manager job should:
1. Expose **container port** of RestServer to public as a **job endpoint**
2. Wait the exposed job endpoint be ready, and than get the **hostname** and **host port** (which is different from the container port) of the job endpoint
3. Start trial job with the hostname and host port as the address of RestServer.
> DLTS: Get NNI manager IP / port from endpoints

- docs/en_US/conf.py
Preview:
Unfortunately it won't link to GitHub, but I think it suffies the need of #2338
> Enable viewcode in readthedocs

- src/sdk/pynni/nni/nas/pytorch/classic_nas/mutator.py
- src/sdk/pynni/nni/nas/pytorch/darts/mutator.py
- src/sdk/pynni/nni/nas/pytorch/enas/mutator.py
- src/sdk/pynni/nni/nas/pytorch/mutables.py
- src/sdk/pynni/nni/nas/pytorch/mutator.py
- src/sdk/pynni/nni/nas/pytorch/pdarts/mutator.py
- src/sdk/pynni/nni/nas/pytorch/proxylessnas/mutator.py
- src/sdk/pynni/nni/nas/pytorch/random/mutator.py
- src/sdk/pynni/tests/models/pytorch_models/__init__.py
- src/sdk/pynni/tests/models/pytorch_models/layer_choice_only.py
- src/sdk/pynni/tests/test_nas.py
IT is broken because of #2336. I forgot that choices and modules are on different devices.
To fix this, I introduced a refactor that deprecates mutators from using choices. `choices` is now an immutable property that can no longer be modified.
> Fix layer choice on IT and deprecate "choices" and "length"

- src/nni_manager/.eslintrc
- src/nni_manager/core/sqlDatabase.ts
- src/nni_manager/rest_server/restHandler.ts
- src/nni_manager/training_service/dlts/dltsTrainingService.ts
- src/nni_manager/training_service/kubernetes/azureStorageClientUtils.ts
- src/nni_manager/training_service/kubernetes/kubernetesJobInfoCollector.ts
- src/nni_manager/training_service/kubernetes/kubernetesTrainingService.ts
- src/nni_manager/training_service/pai/paiConfig.ts
- src/nni_manager/training_service/pai/paiJobInfoCollector.ts
- src/nni_manager/training_service/pai/paiJobRestServer.ts
- src/nni_manager/training_service/pai/paiK8S/paiK8STrainingService.ts
- src/nni_manager/training_service/pai/paiTrainingService.ts
- src/nni_manager/training_service/pai/paiYarn/paiYarnData.ts
- src/nni_manager/training_service/pai/paiYarn/paiYarnTrainingService.ts
- src/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
update nni manager eslint rules.
1. add rule to ignore unused args, and treat other unused as error.
2. add run to treat no explicit function return type as error.
3. fix all errors.
> refactor: update eslint rules to remove warnings during build

- docs/en_US/TrainingService/FrameworkControllerMode.md
Adds the missing documentation for the FrameworkController service account per #2404
> fix documentation for FrameworkController

- src/sdk/pynni/nni/nas/pytorch/mutator.py
- src/sdk/pynni/nni/nas/pytorch/pdarts/mutator.py
Mutator now forces mutable to have the same length as the choice vector during export. PDARTS doesn't conform with such limitation as it deletes elements from layer choice but still return a choice vector with original length. So it needs to implement its own export.
> Update implementation of PDARTS export due to mutator refactor

- docs/en_US/NAS/NasGuide.md
- src/sdk/pynni/nni/nas/pytorch/fixed.py
This should solve the problem #2401 is trying to solve.
> Replace layer choice with selected module after applied fixed architecture

- Makefile
- deployment/deployment-pipelines.yml
- deployment/pypi/Makefile
- deployment/pypi/install.ps1
- src/sdk/pynni/nni/__init__.py
Test PYPI: [linux](https://test.pypi.org/project/nni/0.0.9.2005180212/#files) [windows](https://test.pypi.org/project/nni/0.0.9.2005180241/#files)
I'm confused by the letter "v" problem.
The version string placeholder is "999.0.0-developing", without leading letter "v". But during installation, it's replaced by git tag, which is something like "v1.5".
If the leading letter "v" is desired, we should fix the placeholder; and if it should not be there, we should fix `NNI_VERSION_VALUE` in makefiles. Personally I prefer not to include leading "v" in `NNI_VERSION_VALUE`, because that's Python's common practice as I know. If a module wants the leading "v", it can append it before placeholder and the replacement should work fine.
> Add Python SDK version string

- test/pipelines/pipelines-it-remote-linux-to-linux.yml
- test/pipelines/pipelines-it-remote-windows-to-linux.yml
1. When windows node is supported, current names of the two ITs are confusing. So rename them for clear.
1. Ignore SSH stderr to prevent partial success of windows installation.
Note, I will apply changes to Azure pipeline, once it's merged.
> rename remote IT for clear, and fix partial success of remote-windows

- README.md
- examples/nas/enas-tf/datasets.py
- src/sdk/pynni/nni/nas/tensorflow/enas/trainer.py
TensorFlow does not support `from tensorflow.data import`: [issue](https://github.com/tensorflow/tensorflow/issues/33022).
Despite the issue stating `import tensorflow as tf` is the only supported way for any API, I found `from tensorflow.keras import` is commonly used in [official examples](https://www.tensorflow.org/tutorials/quickstart/advanced).
> Fix tensorflow import

- src/nni_manager/training_service/kubernetes/kubernetesData.ts
- src/nni_manager/training_service/local/localTrainingService.ts
- src/nni_manager/training_service/pai/paiK8S/paiK8SData.ts
- src/nni_manager/training_service/pai/paiK8S/paiK8STrainingService.ts
- src/nni_manager/training_service/remote_machine/extends/linuxCommands.ts
- src/nni_manager/training_service/remote_machine/extends/windowsCommands.ts
1. Revert local storage logic, all trials share a common folder in codeDir
2. User a `code` folder to store codeDir for trials in non-local platforms to avoid `run.sh` conflict
> Fix storage logic

- README.md
1. fix broken link
2. delete nas_cifar10 document link, because nas examples are located in `https://github.com/microsoft/nni/tree/master/examples/nas`
> update README document

- install.ps1
- uninstall.ps1
1. Reduce error message if deleted folder not exists.
1. Reduce unneccessary messages.
1. Organize logic better for reinstall scenario.
> improve windows install scripts

- .github/ISSUE_TEMPLATE/bug-report.md
https://github.com/microsoft/nni/issues/2518
> simplify issue template

- azure-pipelines.yml
- install.sh
- test/pipelines/pipelines-it-frameworkcontroller.yml
- test/pipelines/pipelines-it-kubeflow.yml
- test/pipelines/pipelines-it-local.yml
- test/pipelines/pipelines-it-pai.yml
- test/pipelines/pipelines-it-paiYarn.yml
- test/pipelines/pipelines-it-remote-linux-to-linux.yml
- test/pipelines/pipelines-it-remote-linux-to-windows.yml
- test/scripts/it.sh
https://github.com/microsoft/azure-pipelines-tasks/issues/10125
> Exit when installation failed on pipeline

- docs/en_US/autotune_ref.md
- examples/trials/mnist-pytorch/mnist.py
- src/sdk/pynni/nni/utils.py
> Add shortcut to merge parameter into base setup

- src/webui/src/components/Modals/Compare.tsx
- src/webui/src/components/trial-detail/Duration.tsx
- src/webui/src/components/trial-detail/Para.tsx
fix issue https://github.com/microsoft/nni/issues/2513
now only support ` choice ` type
demo: http://13.77.78.63:9090/detail
> Support nested experiment more friendly

- docs/requirements.txt
These tools have a dependency on the `schema` package and the
`tensorboard` package. When compiling the documents corresponding
to these tools, these packages are required to successfully compile
the document.
Error link:
https://nni.readthedocs.io/en/latest/Compressor/CompressionReference.html#sensitivity-utilities
> Fix the doc building error for the CompressionReference.md

- src/nni_manager/training_service/reusable/trialDispatcher.ts
If nniManagerIp is not filled, the default IP address are not passed to runner. This fix load default IP as other training service.
> TrialDispatcher: missed default nniManagerIp.

- docs/en_US/Tutorial/SearchSpaceSpec.md
Review sentences meaning, clarifying and simplifying them.
Add choice(nested) in the search space types supported by each tuner.
Remove item in known limitations that is now closed.
> Update search space documentation

- docs/en_US/_templates/index.html
> fix typo "vv1.7"

- src/sdk/pynni/nni/compression/torch/pruning/simulated_annealing_pruner.py
self.modules_wrapper is not properly updated, this cause an error when 'export_model' is called
> fix SimulatedAnnealingPruner export mask issue

- docs/en_US/NAS/BenchmarksExample.ipynb
- src/sdk/pynni/nni/nas/benchmarks/nasbench101/model.py
- src/sdk/pynni/nni/nas/benchmarks/nasbench101/query.py
- src/sdk/pynni/nni/nas/benchmarks/nasbench201/model.py
- src/sdk/pynni/nni/nas/benchmarks/nasbench201/query.py
- src/sdk/pynni/nni/nas/benchmarks/nds/model.py
- src/sdk/pynni/nni/nas/benchmarks/nds/query.py
- src/sdk/pynni/nni/nas/benchmarks/utils.py
* Fix #2721 
* Add API to return intermediate results
> Add API to query intermediate results in NAS benchmark

- examples/model_compress/model_prune_torch.py
- src/sdk/pynni/nni/compression/torch/pruning/one_shot.py
- src/sdk/pynni/tests/test_compressor.py
- src/sdk/pynni/tests/test_pruners.py
Parameter 'optimizer '  was removed from Pruners ('level', 'slim', 'fpgm', 'l1', 'l2') in PR https://github.com/microsoft/nni/pull/2676.  This example should be changed accordingly.
> fix IT pruning example issue

- azure-pipelines.yml
- deployment/docker/Dockerfile
- deployment/docker/README.md
- deployment/docker/README_zh_CN.md
- deployment/pypi/setup.py
- docs/requirements.txt
- setup.py
- src/sdk/pynni/nni/feature_engineering/gradient_selector/gradient_selector.py
- src/sdk/pynni/nni/feature_engineering/gradient_selector/requirements.txt
- src/sdk/pynni/nni/metis_tuner/requirments.txt
- src/sdk/pynni/requirements.txt
- test/pipelines/pipelines-it-local-tf2.yml
- test/pipelines/pipelines-it-local-windows.yml
- test/pipelines/pipelines-it-local.yml
- test/pipelines/pipelines-it-pai-windows.yml
- test/pipelines/pipelines-it-remote-windows-to-linux.yml
Add supporting sklearn=0.23.2 for nni, test on python3.6 and python3.8 successfully.
> Add supporting sklearn=0.23.2 for nni

- src/nni_manager/training_service/local/localTrainingService.ts
Powershell reads the path from the registry instead of inheriting from the current environment, so it need to set path manually.
By default, powershell may use UTF-16le encoding, need to set UTF-8 for correctly displaying log in portal.
> Fix bug in local training service under powershell

- src/webui/src/components/Modals/Compare.tsx
- src/webui/src/components/public-child/PaiTrialChild.tsx
- src/webui/src/components/public-child/PaiTrialLog.tsx
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/model/trial.ts
- src/webui/src/static/style/compare.scss
@colorjam 
about table open row `log`
- change `HDFS` to `NFS`
- show `trial stdout` as `Trial stdout` and show Trial stdout as hyperlink on pai mode
@SparkSnail 
- show table default metric `FINAL | LATEST` corectly
about compare modal: 
- update legend style
- add scroll bar for table rather than Modal's scroll-x
some format changes.
> [v1.8 bug-bash] fix webui error 

- src/sdk/pynni/nni/nas/pytorch/mutator.py
> Fix visualization for ENAS micro

- examples/model_compress/models/mobilenet.py
- examples/model_compress/models/mobilenet_v2.py
- src/sdk/pynni/nni/compression/torch/pruning/sensitivity_pruner.py
- src/sdk/pynni/nni/compression/torch/utils/sensitivity_analysis.py
Bug bash for the sensitivity_pruner
> bug bash for sensitivity_pruner

- examples/model_compress/model_prune_tf.py
- src/sdk/pynni/nni/compression/tensorflow/compressor.py
- src/sdk/pynni/nni/compression/tensorflow/pruning/one_shot.py
- src/sdk/pynni/tests/test_compressor_tf.py
`tf.keras.Sequential` is too tricky to compress, removed from v1.8 release.
> TF compression fix and UT

- src/sdk/pynni/nni/package_utils.py
On Windows `site.getsitepackages()[0]` can either be the base directory like `C:\Python38`, or `site-packages`. So all items in that list need to be checked.
The ideal solution is to find a reliable resource packaging machanism. `data_files` is not designed for this use case.
> Hotfix installation problem on Windows without conda/venv

- src/sdk/pynni/nni/compression/torch/speedup/infer_shape.py
- src/sdk/pynni/nni/compression/torch/utils/mask_conflict.py
- src/sdk/pynni/tests/test_model_speedup.py
> [bug bash] issue 2706

- src/sdk/pynni/nni/nas/pytorch/enas/mutator.py
> fix wrong order of hidden and cell state

- test/config/customized_tuners/demotuner-sklearn-classification.yml
- test/config/integration_tests.yml
- test/pipelines/pipelines-it-frameworkcontroller.yml
- test/pipelines/pipelines-it-kubeflow.yml
- test/pipelines/pipelines-it-local-windows.yml
- test/pipelines/pipelines-it-local.yml
- test/pipelines/pipelines-it-pai-windows.yml
- test/pipelines/pipelines-it-pai.yml
- test/pipelines/pipelines-it-remote-linux-to-linux.yml
- test/pipelines/pipelines-it-remote-linux-to-windows.yml
- test/pipelines/pipelines-it-remote-windows-to-linux.yml
Add IT case to test user installed builtin tuner.
> Add IT case: customized-tuners-demotuner

- src/webui/.eslintrc
- `This rule accepts "nofunc" string as an option. "nofunc" is the same as { "functions": false, "classes": true, "variables": true }.`
- It's correct: 
> f();
> function f() {}
- still check `variables and class`
> turn off function no-use-before-define rule

- examples/model_compress/model_prune_tf.py
- src/sdk/pynni/nni/compression/tensorflow/compressor.py
- src/sdk/pynni/tests/test_compressor_tf.py
"A little bit breaking" change: `Compressor.compress()` no longer guarantees to return the original model.
This is because `tf.keras.Sequential` is designed for read-only usage and therefore is too tricky to compress in place. So we create a new `Sequential` with instrumented layers instead.
> Compression support for tf.keras.Sequential

- src/nni_manager/training_service/reusable/aml/amlClient.ts
By default, PythonShell will use py.exe under Windows, but not everyone will install py.exe. And it will not inherit the current python environment but the python specified in the python file, if use py.exe. So modify it.
> modify the pythonPath of PythonShell to support aml mode under Windows

- Makefile
- deployment/pypi/Makefile
- deployment/pypi/install.ps1
- install.ps1
~Makefile in deployment folder still needs to be updated correspondingly.~
~Yarn will use the latest version per @liuzhe-lz 's suggestion.~
Node.js 10.13 -> 10.22
yarn 1.12.1 -> 1.22.5
> Upgrade node and yarn

- docs/requirements.txt
Preview: https://nni.readthedocs.io/en/fix-pygments/
Pygments is downgraded for some reason. The same issue on pipeline has already been fixed in #2888.
> Add pygments as dependency for docs build

- examples/nas/spos/blocks.py
- examples/nas/spos/network.py
- examples/nas/spos/scratch.py
fix SPOS always affine=False bug; change workers to 4 to avoid DALI breaking out; add dump_checkpoint to save the result searched by scratch.py.
I have increased the top1 accuracy from 72.14% to 72.88%, reported in [issue](https://github.com/microsoft/nni/issues/2883#issuecomment-693779116)
> Increase SPOS accuracy

- src/webui/src/static/json_util.ts
`json_utils.ts` somehow doesn't pass the pipeline now.
I don't know how that happened. Maybe we are testing HEAD instead of MERGE?
> Fix eslint for json_utils.ts

- docs/en_US/TrainingService/RemoteMachineMode.md
- docs/en_US/Tutorial/ExperimentConfig.md
- examples/trials/mnist-tfv2/config_remote.yml
- src/nni_manager/rest_server/restValidationSchemas.ts
- src/nni_manager/training_service/remote_machine/extends/linuxCommands.ts
- src/nni_manager/training_service/remote_machine/extends/windowsCommands.ts
- src/nni_manager/training_service/remote_machine/osCommands.ts
- src/nni_manager/training_service/remote_machine/remoteMachineData.ts
- src/nni_manager/training_service/remote_machine/shellExecutor.ts
- src/nni_manager/training_service/remote_machine/test/shellExecutor.test.ts
- src/nni_manager/training_service/test/remoteMachineTrainingService.test.ts
- tools/nni_cmd/config_schema.py
It can be used in remote mode by set preCommand in experiment config. It is an optional key with string value.
An example is as below:
```
...
machineList:
- ip: ${replace_to_your_remote_machine_ip}
username: ${replace_to_your_remote_machine_username}
sshKeyPath: ${replace_to_your_remote_machine_sshKeyPath}
preCommand: export PATH=${replace_to_python_environment_path_in_your_remote_machine}:$PATH
...
```
> Add preCommand option to support configuring experimental environment by user

- docs/en_US/Compressor/DependencyAware.md
The original format of the Dependency-Aware's documentation doesn't look well,  so we put the image on a new line.
> fix format for Dependency-aware doc

- src/sdk/pynni/nni/compression/torch/speedup/compress_modules.py
- src/sdk/pynni/nni/compression/torch/speedup/infer_shape.py
- src/sdk/pynni/nni/compression/torch/utils/mask_conflict.py
Add the support for aten::mul operator.
Signed-off-by: Ningxin <Ningxin.Zheng@microsoft.com>
> Add the support for aten::mul operator.

- src/sdk/pynni/nni/compression/torch/compressor.py
- src/sdk/pynni/nni/compression/torch/quantization/quantizers.py
- src/sdk/pynni/tests/test_compressor_torch.py
Add bias quantization and refactor the code. If this PR was merged, I would submit a new PR to modify the doc.
> Add bias quantization in QAT and refactor the code of weight quantization

- src/sdk/pynni/nni/common.py
`nni.package_utils` imports tuner classes, which activate NNI dispatcher logger, and the logger will redirect stdout of the process.
Luckily nnictl will activate NNI standalone logger for some reason (which it shouldn't) before using package_utils. So this PR detects that if the logger is already setup in standalone mode, do not initialize dispatcher logger.
> Hotfix a problem that package_utils eat nnictl output

- src/sdk/pynni/nni/nas/tensorflow/enas/trainer.py
This PR parameterizes training options for EsTrainer implementation in tensorflow. This makes the implementation similar to that in pytorch and allows users to configure training setup and similar to the implementation in pytorch.
For example, users will be able to reproduce the experiment in the original ENAS paper by setting the training steps for the controller to 2000.
> Parameterized training options for EsTrainer implementation in tensorflow

- src/sdk/pynni/nni/nas/tensorflow/mutator.py
**What would you like to be added:**
The concatenation axis in src/sdk/pynni/nni/nas/tensorflow/mutator.py is fixed to 0 which does not reflect image_data_format setting in keras.json config.
**Why is this needed:**
This will cause the model to concatenate multiple inputs in the skip connections in the wrong dimensions. Users might get Incompatible shapes error if he uses multiple filter sizes.
**Without this feature, how does current nni work：**
nni only allows concatenating in the first dimension. This will fail if image_data_format is channel_last.
**Components that may involve changes:**
src/sdk/pynni/nni/nas/tensorflow/mutator.py
> Udpated concat axis to match image_data_format in keras

- azure-pipelines.yml
- deployment/deployment-pipelines.yml
- test/scripts/unittest.sh
- tools/nni_annotation/test_annotation.py
python3.7 has been removed from mac images:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
upgrade mac pipeline python to 3.8
> Fix mac pipeline

- src/webui/src/components/trial-detail/TableList.tsx
When the current page is not on the first, using index to locate the item in item list is not correct. This PR is to fix the bug.
> Fix bug when expanding rows not on the first page

- src/webui/src/components/modals/CustomizedTrial.tsx
support customize trial's parameter is boolean when type is choice
> fix bug for customized trial

- src/webui/src/components/overview/command/Command1.tsx
- src/webui/src/components/overview/command/Command2.tsx
- src/webui/src/components/overview/count/EditExperimentParam.tsx
- src/webui/src/components/overview/overviewConst.ts
- src/webui/src/components/trial-detail/TableList.tsx
- src/webui/src/static/style/overview/command.scss
- src/webui/src/static/style/overview/config.scss
- src/webui/src/static/style/overview/overviewTitle.scss
fix issue: 
1. table column width
2. command padding
3. duration unit
4. button style
5. modifiy css to fix Trial jobs style
> fix bugs on second bug bash

- ts/nni_manager/core/nnimanager.ts
In the previous situation, experiment duration only timing under `RUNNING` status. But this may be different from the timing expected by the user, i.e. , timing will pause under `NO_MORE_TRIAL` and `TUNER_NO_MORE_TRIAL` status with some trials still running. 
This PR is a quick fix that when the status is `NO_MORE_TRIAL` or `TUNER_NO_MORE_TRIAL`, let the timing continue. But maybe we need give a clearer definition about `execDuration`.
> quick fix exp-duration pause timing under no_more_trial status

- nni/algorithms/nas/pytorch/spos/trainer.py
- nni/nas/pytorch/fixed.py
Related to Issue #3047("Several issues in nni.nas.pytorch") by Heekang Park
> Fix Error in nas SPOS trainer, apply_fixed_architecture

- setup.py
- setup_ts.py
- ts/nni_manager/yarn.lock
setuptools' `develop --user` does not work with conda, so use "global" install when conda or venv/virtualenv is detected.
Also added `--no-user` option in case detection fails.
It was reported that the copied node.js runtime does not have executable permission. Try to fix it by using `shutil.copy()`, which is said to "copies the file data and the file’s permission mode". Not tested on all platforms though.
> Fix installation in conda

- nni/algorithms/nas/pytorch/darts/trainer.py
In Issues#3044，
I report a bug about Pytorch darts in train.py, which is located at 
”_nni\algorithms\nas\pytorch\darts\trainer.py_“
In the darts trainer.py, which function is _compute_hessian, shows :
"_hessian = (dalpha { L_trn(w+, alpha) } - dalpha { L_trn(w-, alpha) }) / (2*eps)_"
but the below is written by this :
hessian = [(p - n) / **2. * eps** for p, n in zip(dalpha_pos, dalpha_neg)] 
I change it to
hessian = [(p - n) / **(2. * eps)** for p, n in zip(dalpha_pos, dalpha_neg)]
Good luck!
> Bug-fixed for _compute_hessian in Pytorch NAS Darts

- nni/tools/nnictl/command_utils.py
- nni/tools/nnictl/launcher.py
- nni/tools/nnictl/nnictl_utils.py
- pipelines/fast-test.yml
- test/ut/sdk/test_model_speedup.py
- test/ut/tools/nnictl/test_common_utils.py
- ts/nni_manager/main.ts
This PR in fact contains 3 updates, sorry...
1. Fix Windows UT
2. Fix a bug that cannot locate node executable
3. Disable pipeline on translation branch. It receives forced push from crowdin bot too often.
> Fix Windows UT

- nni/experiment/nni_client.py
- nni/tools/nnictl/nnictl_utils.py
- nni/tools/nnictl/tensorboard_utils.py
- test/nni_test/nnitest/utils.py
- ts/nni_manager/common/datastore.ts
- ts/nni_manager/core/nniDataStore.ts
- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/core/test/mockedDatastore.ts
- ts/nni_manager/core/test/nnimanager.test.ts
- ts/nni_manager/rest_server/test/mockedNNIManager.ts
- ts/nni_manager/rest_server/test/restserver.test.ts
- ts/webui/src/components/Overview.tsx
- ts/webui/src/static/interface.ts
- ts/webui/src/static/model/trial.ts
- ts/webui/src/static/model/trialmanager.ts
Change `TrialJobInfo.id` -> `TrialJobInfo.trialJobId` in `src/nni_manager/common/datastore.ts`
Change `ExportedDataFormat.id` -> `ExportedDataFormat.trialJobId` in `src/nni_manager/common/datastore.ts`
Change `TrialJobInfo.id` -> `TrialJobInfo.trialJobId` in `src/webui/src/static/interface.ts`
Migrate from #2896
> unify trial job id name

- ts/webui/src/components/overview/command/Command1.tsx
> fix bug of advisor and assesor written backwards

- pipelines/fast-test.yml
Python on macOS failed to find pytest for unknown reason.
I noticed it was using a somewhat strange environment which I don't know how it was installed or configured.
I tried another approach, azure task, to set Python version and luckily it works.
So basically this PR is switching from black magic to white magic 🪄
> Fix macOS unit test pipeline

- docs/en_US/TrainingService/PaiMode.md
typeset pictures and add catalog in PaiMode.md
>  Optimized layout of PaiMode.md

- nni/runtime/msg_dispatcher.py
- ts/nni_manager/core/nnimanager.ts
~It should be noted that this may still cause some errors. The fundamental solution is to send `trialId` or `parameter` together when `ReportMetricData`. Or let dispatcher generate `trialId`.~
~Involves four `JobRestServer`, dlts, kubernetes, pai, remote. Need check if `TrialJobId` exist before emit `metric` event.~
Add trial job id filtering function in `nnimanager`.
> quick fix unknow trial report to resume experiment

- nni/algorithms/compression/pytorch/quantization/quantizers.py
#3119 
When testing QAT in NNI, users would run into these problems
1. checkpoint load fails, which will cause incremental training fail
2. in evaluation stage, parameters of weight quantization and output quantization should not be updated
3. when we load checkpoint and then evaluate immediately, we would see bad model performance because of the reset of inner variable :[steps]
this pr fix these problems
> fix checkpoint load error and stop updating paramters in evaluation stage

- nni/compression/pytorch/compressor.py
#3159 
Quant grad calculation is not correct in current nni's implementation according to [google's whitepaper](https://arxiv.org/pdf/1806.08342.pdf), it should be ![](http://119.3.255.23:8001/issue.jpg)
> fix quant grad function calculation error

- nni/experiment/pipe.py
The open mode of `socket.makefile()` is different from `open()`. "w+" is written as "rw" here.
> Fix nni.experiment bug

- docs/archive_en_US/TrainingService/AdaptDLMode.md
- docs/en_US/TrainingService/AdaptDLMode.rst
- examples/trials/cifar10_pytorch/adl.Dockerfile
- examples/trials/cifar10_pytorch/config_adl.yml
- nni/tools/nnictl/config_schema.py
- ts/nni_manager/rest_server/restValidationSchemas.ts
- ts/nni_manager/training_service/kubernetes/adl/adlApiClient.ts
- ts/nni_manager/training_service/kubernetes/adl/adlConfig.ts
- ts/nni_manager/training_service/kubernetes/adl/adlJobInfoCollector.ts
- ts/nni_manager/training_service/kubernetes/adl/adlTrainingService.ts
- ts/nni_manager/training_service/kubernetes/kubernetesApiClient.ts
- ts/nni_manager/training_service/kubernetes/kubernetesTrainingService.ts
This PR adds the support for launching trials in custom K8s namespace in AdaptDL mode. I have tested my change in our internal training cluster.
Note that other K8s based training services (Kubeflow, framework controller, etc.) still hard-code the default namespace. In long term, I think it is worth supporting this feature in all K8s training services because creating multiple namespaces in the K8s cluster is a common practice.
@SparkSnail @liuzhe-lz Please review when you have time. This should be the last feature we want to add to the AdaptDL integration before the 2.0 release.
> Support Custom Kubernetes Namespace in AdaptDL Mode

- nni/algorithms/compression/pytorch/quantization/quantizers.py
#3213. In my previous implementation of tensor device assignment, there's potential bug when device is not a cpu nor a GPU, such as XLA:CPU or XLA:GPU. so I fix the code to migrate tensor to input tensors' deivce. Sorry for  that QAT. 
this pr is a complement to #3211
> fix potential bug in quantize device

- nni/algorithms/compression/pytorch/quantization/quantizers.py
- nni/compression/pytorch/compressor.py
This pr fixes the problem proposed in issue #3204 and a bug in the previous pr #3160.
> fix QAT ema issue and tensor type error

- nni/retiarii/trainer/pytorch/darts.py
- nni/retiarii/trainer/pytorch/proxyless.py
I somehow missed the softmax part in DARTS, causing it to converge really slowly.
Also adding back the deduplication part (share the same architecture weight across all modules with the same label) for DARTS. Note that for ProxylessNAS this feature is not supported yet (neither in v1.x).
> Adding back the missing softmax in DARTS and support deduplication

- nni/experiment/experiment.py
- ts/nni_manager/common/utils.ts
Fix dispatcher exit before rest main process clean up. This issue due to CTRL BREAK or CTRL C is sent to all console processes that are attached to the console in Windows.
> detached tuner process under windows

- ts/webui/src/App.scss
- ts/webui/src/components/NavCon.tsx
- ts/webui/src/components/TrialsDetail.tsx
- ts/webui/src/components/managementExp/ExperimentManager.tsx
- ts/webui/src/components/managementExp/TrialIdColumn.tsx
- ts/webui/src/static/style/experiment/experiment.scss
- ts/webui/src/static/style/trialsDetail.scss
1. nav: `All experiment` -> `All experiments`
2. 添加子标题：icon All experiments，如图所示： 
3. row hover 以及 focus 时背景颜色
4. ID 超链接 hover 时的颜色（#615f5d，#333231）
5. experiment page 距离 nav 调整为 `24px`，跟其他两个页面 (oview, detail) 保持一致
6. 尽管实验条目不多，依然保持满屏
当有很多条实验时，保持如下展示：
7. add `trim()` for search name `or`(use `or` rather than `and`) ID input
8. 单机 `行` 弹出此实验的 WebUI
> [2.0a2] fix bugs of experiment managerment page on webui

- examples/trials/network_morphism/requirements.txt
- nni/experiment/config/remote.py
- ts/nni_manager/package.json
- ts/nni_manager/yarn.lock
- ts/webui/package.json
- ts/webui/yarn.lock
Added `ssh_key_file`'s default value back. Because I think the error message `Password is not provided and cannot find SSH key file "~/.ssh/id_rsa"` is clear enough, and manually setting it is too inconvenient as "recommended method".
Insecure dependencies which won't be fixed:
- pyyaml: indirectly required by networkmorphism example
- elliptic, object-path: required by NAS UI, which is not commonly used
- http-proxy: Denial of Service is not a problem for NNI
> Fix security policy related issues

- nni/tools/nnictl/nnictl.py
The patch yesterday enables NNI log handler on user log and dependencies' log.
But nnictl does not use logging and doesn't want to print dependencies' log to console.
This PR raise nnictl log level to ERROR.
> Disable logging for nnictl

- examples/model_compress/pruning/auto_pruners_torch.py
This is the update PR of #3264 . Because the problem of flops counter has been solved in #3223 and file structure changed which cause merge conflict. I open a new PR which only improves the print format.
> fix flops counter bug in auto_pruners_torch.py

- nni/compression/pytorch/speedup/infer_shape.py
- nni/compression/pytorch/utils/mask_conflict.py
- test/ut/sdk/test_model_speedup.py
Fix bug for speedup and enhance the UT for speedup.
(1)  The generated mask tensor should be on the same device as the original tensor.
(2) Due to `Cat` operator, the current speedup module may add a full-ones mask for some layers, the second bug will make the speedup module skip this mask(added by fix mask conflict) and lead to a shape mismatch.
> Fix bug for speedup module and enhance the Ut for speedup

- nni/runtime/platform/standalone.py
Bug bash guide: run the trial code of an HPO example, like `examples/trials/mnist-pytorch/mnist.py`; it should print a striking warning with a link to quick start tutorial.
> Make standalone mode warning more obvious

- ts/webui/src/components/overview/command/Command1.tsx
- ts/webui/src/static/model/experiment.ts
- support `tuner/advisor/assessor` name field: `builtinXxxName || className`
- support get `optimize_mode` from `tuner/advisor/assessor`
-  webui will use `tuner` field if tuner and assessor both have `optimize_mode` field.
> Support show customized tuner/assessor name and get optimize_mode from tuner/advisor/assessor

- dependencies/develop.txt
- dependencies/recommended.txt
- dependencies/required.txt
- dependencies/setup.txt
- nni/__init__.py
- nni/experiment/launcher.py
- nni/tools/nnictl/launcher.py
- nni/tools/nnictl/nnictl_utils.py
- pipelines/fast-test.yml
- pylintrc
- setup.py
This PR creates an extra stage that checks lint first before running full tests.
What this PR does:
What this PR will NOT do:
> [CI] Introduce multi-stage pipeline for speedup

- ts/nni_manager/training_service/reusable/environments/amlEnvironmentService.ts
- ts/nni_manager/training_service/reusable/environments/localEnvironmentService.ts
- ts/nni_manager/training_service/reusable/environments/openPaiEnvironmentService.ts
- ts/nni_manager/training_service/reusable/environments/remoteEnvironmentService.ts
- ts/nni_manager/training_service/reusable/trialDispatcher.ts
1. only files in `./outputs` or `./logs` dir, aml will upload them to run history
2. if aml environment status is not in `['WAITING', 'RUNNING', 'UNKNOWN']`, `environment.isAlive == false`, and environment will not be stopped when `cleanup`, but the python process handled `amlUtil` is still alive.
> fix aml outputs and python process not killed

- nni/retiarii/utils.py
Some objects don't return anything for `getmodule()`, e.g., jupyter notebook.
While I am using it on jupyter notebooks, the code throws an Error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-720eba80f94f> in <module>()
87 
88 @register_trainer
---> 89 class Trainer(BaseTrainer):
90     def __init__(self, model,
91                  train_dataloader, val_dataloader, loss_fn, optimizer, device=torch.device('cpu'), trainer_kwargs={'max_epochs': 10}):
~/anaconda3/lib/python3.7/site-packages/nni/retiarii/utils.py in register_trainer(cls)
117     """
118     frm = inspect.stack()[1]
--> 119     module_name = inspect.getmodule(frm[0]).__name__
120     return …
```
> Fix 'NoneType' Error on jupyter notebooks

- nni/retiarii/converter/op_types.py
- nni/retiarii/operation.py
NNI did not parse the `aten::reshape` operation, causing the following code to report an error when calling reshape() in forward:
```
import random
import nni.retiarii.nn.pytorch as nn
import torch.nn.functional as F
from nni.retiarii.experiment import RetiariiExeConfig, RetiariiExperiment
from nni.retiarii.strategies import RandomStrategy
from nni.retiarii.trainer import PyTorchImageClassificationTrainer
class Net(nn.Module):
def __init__(self, hidden_size):
super(Net, self).__init__()
self.conv1 = nn.Conv2d(1, 20, 5, 1)
self.conv2 = nn.Conv2d(20, 50, 5, 1)
self.fc1 = nn.LayerChoice([
nn.Linear(4*4*50, hidden_size),
nn.Linear(4*4*50, hidden_size, bias=False)
])
self.fc2 = nn.Linear(hidden_size, 10)
def forward(self, x):
x = F.relu(self.conv1(x))
x = F.max_pool2d(x, 2, 2)
x = …
```
> Fix KeyError: 'aten::reshape' on calling torch.reshape

- ts/webui/src/components/managementExp/ExperimentManager.tsx
- ts/webui/src/components/managementExp/FilterBtns.tsx
- ts/webui/src/components/managementExp/expFunction.ts
> Support multiple selection for filter status (manage all experiments page)

- nni/retiarii/converter/graph_gen.py
- nni/retiarii/converter/op_types.py
- nni/retiarii/operation.py
NNI did not support the `prim::TupleConstruct` operation, causing the following code to report an error when outputting tuple data in forward:
```
import random
import nni.retiarii.nn.pytorch as nn
import torch.nn.functional as F
from nni.retiarii.experiment import RetiariiExeConfig, RetiariiExperiment
from nni.retiarii.strategies import RandomStrategy
from nni.retiarii.trainer import PyTorchImageClassificationTrainer
class Net(nn.Module):
def __init__(self, hidden_size):
super(Net, self).__init__()
self.conv1 = nn.Conv2d(1, 20, 5, 1)
self.conv2 = nn.Conv2d(20, 50, 5, 1)
self.fc1 = nn.LayerChoice([
nn.Linear(4*4*50, hidden_size),
nn.Linear(4*4*50, hidden_size, bias=False)
])
self.fc2 = nn.Linear(hidden_size, 10)
def forward(self, x):
x = F.relu(self.conv1(x))
x = F.max_pool2d(x, 2, 2)
x = …
```
> Add `TupleConstruct` to allow `(a, b)=SomeModule()`

- docs/en_US/NAS/retiarii/Tutorial.rst
- nni/retiarii/graph.py
- nni/retiarii/nn/pytorch/api.py
- nni/retiarii/nn/pytorch/mutator.py
- nni/retiarii/utils.py
- test/ut/retiarii/test_highlevel_apis.py
```python
self.conv = nn.Conv2d(3, 32, kernel_size=nn.ValueChoice([3, 5, 7]))
```
> [Retiarii] Use ValueChoice inline in a serializable instance

- ts/nni_manager/package.json
- ts/nni_manager/training_service/common/containerJobData.ts
- ts/nni_manager/training_service/reusable/environments/remoteEnvironmentService.ts
- ts/nni_manager/yarn.lock
Current version is too old to support default key format generated by openssh 8.4
> Update ssh2 version and fix minor bugs

- nni/experiment/config/base.py
This PR fixes the following error when the `ruamel.yaml` version is greater than 0.11.4:
```bash
ModuleNotFoundError: No module named 'ruamel'
```
It also makes the code consistent with other code that uses this module.
> fix: Fix ruamel import

- nni/experiment/config/base.py
- nni/experiment/config/common.py
- nni/experiment/config/util.py
- nni/tools/nnictl/launcher.py
Fix a bug found by J-Shang: when reading v2 config file nnictl will use pwd to resolve relative paths, while the correct behavior is to use config file's directory.
> Fix relative path bug in config v2

- ts/webui/src/components/public-child/MonacoEditor.tsx
- this variable `_isMonacoMount` is no use, so delete related code;
- when I put `wordWrap: 'on'` in object `DRAWEROPTION`, met this error, as picture:
- For fix this question, must write this options in `MonacoEditor` directly.
- wrap:
> WebUI dispatcher log / nnimanager log wrap

- nni/algorithms/compression/pytorch/quantization/quantizers.py
- nni/compression/pytorch/compressor.py
- test/ut/sdk/test_compressor_torch.py
Add `export_model` function for quantization algorithm QAT. Users can save quantized weight and calibration parameters to specific path. What' s more, this function will be a prerequisite for #3356 (Support mixed-precision quantization speed up by using tensorrt).
> Add model export for QAT

- .gitignore
- docs/en_US/TrainingService/FrameworkControllerMode.rst
- examples/trials/mnist-pytorch/config_frameworkcontroller_custom.yml
- examples/trials/mnist-pytorch/fc_template.yml
- nni/tools/nnictl/config_schema.py
- nni/tools/nnictl/launcher_utils.py
- ts/nni_manager/rest_server/restValidationSchemas.ts
- ts/nni_manager/training_service/kubernetes/frameworkcontroller/frameworkcontrollerApiClient.ts
- ts/nni_manager/training_service/kubernetes/frameworkcontroller/frameworkcontrollerConfig.ts
- ts/nni_manager/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.ts
- ts/nni_manager/training_service/kubernetes/kubeflow/kubeflowTrainingService.ts
- ts/nni_manager/training_service/kubernetes/kubernetesApiClient.ts
- ts/nni_manager/training_service/kubernetes/kubernetesConfig.ts
- ts/nni_manager/training_service/kubernetes/kubernetesTrainingService.ts
As discussed in #3350, this PR introduces: 
- The option to specify a custom framework controller config for framework controller mode
- A minimum working setup for the mnist-pytorch example (nni config and framework controller config)
- Required changes to the related python parser / webserver logic
In addition, the following changes have been applied:
- Option to specify a k8s namespace for the trials to run 
Currently, the following components have not yet been considered (thus the WIP state):
- documentation for the code and examples
- unit tests covering the changes
> [WIP] Enable optional Pod Spec for FrameworkController platform

- ts/webui/src/components/Overview.tsx
- ts/webui/src/static/style/overview/overview.scss
customer raised issue: https://github.com/microsoft/nni/issues/3484
bug reason: own code uses same className with monaco editor. they all use `wrapper`.
> fix the issue: text is not displayed completely when searching in the search space/config/log monaco editor

- ts/webui/src/components/modals/ChangeColumnComponent.tsx
- ts/webui/src/components/trial-detail/Para.tsx
- ts/webui/src/components/trial-detail/TableList.tsx
description: 
-  this bug is from v2.1
-  when using parameter graph's `Add/Remove axes` together with table's `Add/Remove columns`, it will be confused.
-  bug’s reason: they all use the component `ChangeColumnComponent` and it store localstorage by same key
-  bug fix by `add key to make different modal`
-  use localstorage to store user hyper-parameter yAxis setting
> fix bug of `Add/Remove` modal

- examples/nas/cream/lib/models/structures/supernet.py
- nni/algorithms/nas/pytorch/cream/trainer.py
Two bugs may be fixed for the NAS (Cream of the Crop):
1) in "nni/nni/algorithms/nas/pytorch/cream/trainer.py", line 168: 
I think the prioritized board should be updated with the newest student network, not the teacher. Otherwise, the prioritized board will be filled with the same teacher?
2) in "nni/examples/nas/cream/lib/models/structures/supernet.py", line 126:
In the class method rand_parameters(self, ...), when yielding parameters of the block in mutable, the passed architecture is the dictionary with the type Dict[str, np.array], of which the key is mutable.key, and the value is a one-hot vector. In the original function, the traversed blocks is already a block in the mutable, which can not be indexed by the arch. Therefore, the class method is modified by using (block, arch) to …
> Bug fix for Cream NAS

- docs/en_US/NAS/retiarii/Tutorial.rst
- examples/trials/mnist-pytorch/config.yml
- nni/retiarii/experiment/pytorch.py
- nni/retiarii/strategy/__init__.py
- nni/retiarii/strategy/local_debug_strategy.py
- test/retiarii_test/mnist/test.py
> [Retiarii] support debug mode for easy debuggability

- ts/webui/src/components/overview/count/EditExperimentParam.tsx
- ts/webui/src/static/style/overview/count.scss
(max trial number is still 105, but 120 is shown as maxTrialNum)
> fix update experiment params issue on view mode

- nni/nas/pytorch/mutables.py
This Pull Request fixes a typo on` line 75 of nni/nas/pytorch/mutables.py`.
While I was reading the source code, I wondered whether this is a typo, as shown below:
```
nni/nas/pytorch/mutables.py, line 75
@property
71    def name(self):
72        """
73        After the search space is parsed, it will be the module name of the mutable.
74        """
75        return self._name if hasattr(self, "_name") else "_key"
```
Should `"_key"` be `self._key `because this method is supposed to return a key/name of a mutable?
The Issue seems to be very minor but it improves the readability of the Code and fixes a typo on` line 75 of nni/nas/pytorch/mutables.py `issue in Python 3 which happens to be a standard.
I'm a First-Time Contributor to Microsoft Open-Source so it would be helpful for me …
> Fixed typo on line 75 of nni/nas/pytorch/mutables.py

- nni/compression/pytorch/utils/counter.py
1. bug of kernel_ops calculation https://github.com/microsoft/nni/issues/3344
2. add counters of rnn module
> Fix bug of FLOPs counter 

- ts/webui/src/components/overview/count/EditExperimentParam.tsx
- ts/webui/src/components/slideNav/TrialConfigPanel.tsx
two issue: 
1. fix `maxExperimentDuration` show `NaNm` bug
2. fix another question: change experiment maxDuratioin and then change experiment maxTrialNum, maxDuration on the editable input will change duration unit!
Delete the `AppContext` on the `TrialConfigPanel` because no longer using its value
> fix update experiment parameters bug

- docs/en_US/Compression/AutoPruningUsingTuners.rst
- docs/zh_CN/Compression/AutoPruningUsingTuners.rst
- examples/model_compress/pruning/basic_pruners_torch.py
- examples/model_compress/pruning/config.yml
The bug is about config error, and the specific modification location is as follows:
1. Modify the code in "nni/examples/model_compress/pruning/basic_pruners_torch.py" , 378 line ：args.model = params['model']
2. Modify the code in "nni/examples/model_compress/pruning/config.yml", 18 line ：name: GridSearch
> modify the config bug about Automatic Model Pruning using NNI Tuners

- dependencies/recommended.txt
- nni/retiarii/evaluator/pytorch/lightning.py
- pipelines/full-test-linux.yml
- pipelines/full-test-windows.yml
- test/ut/retiarii/test_lightning_trainer.py
References:
https://pytorch-lightning.readthedocs.io/en/stable/extensions/metrics.html#accuracy
https://github.com/PyTorchLightning/lightning-bolts/issues/587
https://github.com/PyTorchLightning/lightning-bolts/issues/551
https://github.com/PyTorchLightning/lightning-bolts/pull/584
> Unpin `pytorch_lightning<1.2`

- nni/tools/nnictl/launcher.py
- ts/nni_manager/common/log.ts
- ts/nni_manager/common/utils.ts
- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/main.ts
This PR implements following improvements:
1. Allow TS loggers to have "name" like Python counterpart, so it can distinguish log messages from different modules. This will be helpful for 3rd party training service.
2. Correctly format log message to string (rather than array).
3. Automatically stringify JSON objects and arrays, so you won't see `[Object object]` in log.
Before:
```
[2021-04-21 10:37:34] INFO [ 'Datastore initialization done' ]
```
Now:
```
[2021-05-10 12:07:56] INFO (root) Datastore initialization done
```
> Improve NNI manager logging

- nni/runtime/log.py
- nni/runtime/platform/local.py
The problem with log and metric when using torch.utils.data.DataLoader with num_workers>0 on windows is known for a long time. I find that the log and metric file is whipped of its content whenever a DataLoader is enumerated. I reached out to pytorch for this, and they told me it is a issue with the multiprocessing library. It uses on default spawn mode in windows, in which
> unnecessary file descriptors and handles from the parent process will not be inherited (https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods)
This cause the log and metric file which are opened at top level in `__init__.py` and `runtime/platform/local.py`. Thankfully there is a simple workaround on this, that is to change the file to 'a' open mode. I tested it on my local machine and it …
> Fix on log and metric issue on Windows when using pytorch with multithread

- ts/webui/src/components/stateless-component/NNItabs.tsx
- ts/webui/src/index.tsx
- ts/webui/src/static/const.ts
- ts/webui/src/static/function.ts
related issue: #2771 
With this PR merged, you could run an experiment with command `nnictl create --config xx.yml --url_prefix customURL` open webui website look like this : `ip:port/customURL/oview`
（1）`nnictl create --config xx.yml` 起一个实验，观察 ip:port/oview、 /detail、 /experiment 页面是否正常
（2）`nnictl create --config xx.yml --url_prefix customPrefix` 起一个实验，观察 ip:port/customPrefix/oview、/detail、 /experiment 页面是否正常
（3）`nnictl create --config xx.yml --url_prefix /customerURL` 起一个实验，此时会提醒不能以 `/`  开头，路径无效
（4）`nnictl create --config xx.yml --url_prefix customer/xxx` 起一个实验，观察 ip:port/customPrefix/oview、/detail、 /experiment 页面是否正常
> [webui] add basename in router

- nni/compression/pytorch/utils/mask_conflict.py
`merged_channel_mask` is a mask tensor, while `merged_index` is merely an index tensor.
> fix the bug in line no.336 in mask_conflict.py

- nni/retiarii/converter/graph_gen.py
- test/ut/retiarii/test_convert_models.py
> Support nested ModuleList and fix an issue in list append

- dependencies/recommended.txt
- dependencies/recommended_legacy.txt
- docs/requirements.txt
- nni/retiarii/strategy/__init__.py
- nni/retiarii/strategy/_rl_impl.py
- nni/retiarii/strategy/rl.py
- pipelines/full-test-linux.yml
- pipelines/full-test-windows.yml
- test/ut/retiarii/test_strategy.py
This PR supports a family of RL strategy based on tianshou. The default built-in algorithm is PPO.
TODOs:
> [Retiarii] Policy-based RL Strategy

- docs/en_US/NAS/retiarii/Advanced.rst
- nni/retiarii/__init__.py
- nni/retiarii/execution/api.py
- nni/retiarii/execution/base.py
- nni/retiarii/execution/purepython.py
- nni/retiarii/execution/python.py
- nni/retiarii/experiment/pytorch.py
- nni/retiarii/graph.py
- nni/retiarii/integration.py
- nni/retiarii/mutator.py
- nni/retiarii/nn/pytorch/api.py
- nni/retiarii/nn/pytorch/mutator.py
- nni/retiarii/serializer.py
- nni/retiarii/trial_entry.py
- nni/retiarii/utils.py
- test/ut/retiarii/debug_mnist_pytorch.py
- test/ut/retiarii/mnist_pytorch.json
- test/ut/retiarii/test_engine.py
- test/ut/retiarii/test_highlevel_apis.py
- test/ut/retiarii/test_mutator.py
This PR adds an execution engine that can directly execute graph without touching any graph converter and codegen stuff. It is expected to become the default execution engine in version 2.3.
I've also implemented a more useful mutation history tracking tool. This should make the upcoming visualization thing possible.
I tried to refact/damage as little code as possible. Some of the refactoring effort might come in future releases.
~I think a lot of tests are needed before it is ready for review.~
Depending on #3607.
Currently I don't have the confidence to make this execution engine default. Two modifications are needed to (manually) enable the new engine.
1. Add `@model_wrapper` decorator outside the full PyTorch model.
2. Add `config.execution_engine = 'py'` to `RetiariiExeConfig`.
> [Retiarii] Pure-python execution engine

- ts/webui/src/components/public-child/OpenRow.tsx
add `View trial stdout` button only for local mode:
> add trial stdout button on local mode

- docs/en_US/Compression/Quantizer.rst
Op_types requires a list to be passed in it. Raw string caused error.
> Documentation typo fix in DoReFa compression 

- docs/en_US/hpo_benchmark.rst
- examples/trials/benchmarking/automlbenchmark/setup.sh
This pr contains two fixes:
1. Add more descriptions to the report statistics (discussed last time, unable to add before merge)
2. Remove the company comment in the setup script so that the shebang can be read out correctly
> HPO Benchmark doc and setup script fix 

- nni/algorithms/hpo/dngo_tuner.py
- test/ut/sdk/test_builtin_tuners.py
Fixed an issue that DNGO tuner name is not consistent in python file and yaml.
> Fix DNGO tuner class name

- nni/tools/nnictl/algo_management.py
- nni/tools/nnictl/common_utils.py
- nni/tools/nnictl/config_schema.py
- nni/tools/nnictl/config_utils.py
- nni/tools/nnictl/launcher.py
- nni/tools/nnictl/nnictl_utils.py
- nni/tools/nnictl/url_utils.py
I manually triggered pylint and fixed most issues.
There remains several "line too long".
> Fix bugs and lints in nnictl

- docs/en_US/hpo_benchmark.rst
- examples/trials/benchmarking/automlbenchmark/nni/frameworks.yaml
This pr adds support for running HPO Benchmark on DNGOTuner as a built-in tuner. 
Note: this pr is a superset of the pr #3716
> Add benchmark support for DNGOTuner

- Dockerfile
- docs/en_US/NAS/retiarii/Advanced.rst
- examples/nas/multi-trial/mnist/search.py
- nni/retiarii/codegen/pytorch.py
- nni/retiarii/execution/python.py
- nni/retiarii/experiment/pytorch.py
- nni/retiarii/strategy/_rl_impl.py
- nni/retiarii/strategy/rl.py
- test/ut/retiarii/debug_mnist_pytorch.py
- test/ut/retiarii/test_strategy.py
1. Upgrade dependencies in Dockerfile and include pytorch-lightning.
2. Support export in pure-python execution engine, update docs and examples.
3. Fix an issue that `nni.retiarii.nn` cannot be imported in generated code.
4. Change the RL implementation to multithreading because multiprocessing doesn't work with current execution engine implementation. As a result, we don't support AsyncCollector for now.
This PR should unblock #3700.
> Fix a few bugs in Retiarii and upgrade Dockerfile

- nni/tools/nnictl/ts_management.py
- nni/tools/trial_tool/trial_runner.py
- ts/nni_manager/common/experimentStartupInfo.ts
- ts/nni_manager/common/pythonScript.ts
- ts/nni_manager/common/utils.ts
- ts/nni_manager/training_service/reusable/environments/amlEnvironmentService.ts
- ts/nni_manager/training_service/reusable/environments/environmentServiceFactory.ts
- ts/nni_manager/training_service/reusable/environments/localEnvironmentService.ts
- ts/nni_manager/training_service/reusable/environments/openPaiEnvironmentService.ts
- ts/nni_manager/training_service/reusable/environments/remoteEnvironmentService.ts
Environment service with web command channel needs to know the port. Otherwise it only supports 8080.
To fix this, pass whole ExperimentStartupInfo to environment service.
The template / example training service: https://github.com/liuzhe-lz/nni-training-service-template
> Fix 3rd-party training service bug

- nni/retiarii/nn/pytorch/component.py
- nni/retiarii/nn/pytorch/mutator.py
- nni/retiarii/strategy/_rl_impl.py
- nni/retiarii/strategy/bruteforce.py
- nni/retiarii/strategy/tpe_strategy.py
1. Fix a data race issue on Retiarii RL that induces unexpected result for models within the same iteration.
2. Add docstring to TPE strategy.
3. Fix the key name in mutators created in BaseExecutionEngine.
4. Fix an issue that causes budget to be negative. Thanks @hzhua for pointing out.
> Fix a few issues in Retiarii

- nni/experiment/pipe.py
Named pipe can sometimes fall into extremely sophisticated states and there is very little benefit to handle them. So when strange things happen, just wait the OS to recycle resources.
The only potential problem is, if the user stops and resumes an experiment in one process, then resuming might fail. I believe this use case is too rare to worth a fix.
> Catch clean up error to prevent crash

- docs/en_US/ResearchPublications.rst
- examples/trials/systems_auto_tuning/rocksdb-fillrandom/config_smac.yml
- examples/trials/systems_auto_tuning/rocksdb-fillrandom/config_tpe.yml
This PR adapts config files of RocksDB example to NNI V2, and updates the citation information of OpEvo paper. I do not adapt the configuration files of OpEvo to NNI V2, since they run in a docker in which NNI 1.5 is installed and I would like to keep all setup same as that of experiments in our paper.
> Adapt system auto tuning examples to NNI V2

- ts/nni_manager/common/utils.ts
- ts/nni_manager/training_service/common/util.ts
How to test: Use spaces and special characters in trial code's file names. There should be a warning message in nnimanager.log.
How to fully test: Use spaces and special characters in file names. Then run each training service once. (Consider add an IT test case)
> Change file name validation to warning

- nni/compression/pytorch/utils/counter.py
Fix a minor formatting issue. Previously the counter prints out the FLOPs as a tensor directly.
before:
after:
> flops counter formatting fix

- docs/en_US/Compression/QuantizationSpeedup.rst
- nni/compression/pytorch/quantization_speedup/integrated_tensorrt.py
This PR is for fixing data's device type which has to be "cpu". Otherwise, it can not convert to numpy directly and will raise errors.
> [quantization speedup]fix data device type bug

- dependencies/required.txt
- nni/tools/nnictl/config_schema.py
- ts/nni_manager/common/utils.ts
This method will get the IP address of default router, which means, when anyone creates connection and sends packets via standard library, it will use this address.
The method is platform independent and is irrelative to "eth0", so at Python side it does not need `netifaces` to do validation.
> Change NNI manager IP detection method and remove `netifaces` dependency

- nni/algorithms/hpo/batch_tuner.py
- nni/algorithms/hpo/dngo_tuner.py
- nni/algorithms/hpo/gp_tuner/gp_tuner.py
- nni/algorithms/hpo/gridsearch_tuner.py
- nni/algorithms/hpo/hyperband_advisor.py
- nni/algorithms/hpo/hyperopt_tuner.py
- nni/algorithms/hpo/metis_tuner/metis_tuner.py
- nni/algorithms/hpo/smac_tuner/smac_tuner.py
- nni/common/hpo_utils.py
- test/ut/sdk/test_hpo_utils.py
There are multiple issues caused by invalid user search space.
Add a simple validation to make these errors more obvious.
I'm not confident about current implementation, so it only prints an error log and does not interrupt tuner.
> Add simple HPO search space validation

- nni/algorithms/compression/pytorch/quantization/quantizers.py
@chenbohua3 points out that bias shouldn't be quantized during training process as QAT paper claims. I have checked the paper and decide to delete the bias quantization after discussion.
> [Simulated Quantization] Delete bias to be aligned with paper

- nni/compression/pytorch/speedup/compress_modules.py
- nni/compression/pytorch/speedup/infer_shape.py
support PReLU symbol in pytorch when speeding up the model.
> support prelu to speedup model

- docs/en_US/Compression/QuantizationSpeedup.rst
- nni/compression/pytorch/quantization_speedup/integrated_tensorrt.py
This PR aims to support the latest TensorRT version. Current quantization speedup tool is implemented based on TensorRT7.0. However, the latest tensorrt python api has changed which separates network definition and configuration after version 8.0. All configuration of low precision have been moved to IBuilderConfig and our current implementation can't work on it (the problem raised in issue #3857 ). This PR supports the new TensorRT version and the new api.
> [Quantization speedup]support TensorRT8.0.0

- nni/compression/pytorch/quantization_speedup/integrated_tensorrt.py
This pr fixes issue #3882 . The type of 8bit should be `trt.int8` in `Precision_Dict`.
> https://github.com/microsoft/nni/blob/009722a67ba034734ca4f488f537f933788fd910/nni/compression/pytorch/quantization_speedup/integrated_tensorrt.py#L25-L29
> [Quantization Speedup]fix precision type

- docs/en_US/Tutorial/Nnictl.rst
- nni/tools/nnictl/launcher.py
- nni/tools/nnictl/nnictl.py
- nni/tools/nnictl/nnictl_utils.py
1. support view experiment from external folder
2. support resume experiment from external folder
3. fix `nnictl experiment delete`
> Support view/resume experiment from external folder

- docs/en_US/NAS/QuickStart.rst
- docs/en_US/NAS/WriteTrainer.rst
- nni/experiment/launcher.py
- nni/retiarii/evaluator/pytorch/lightning.py
- test/.gitignore
- test/ut/tools/nnictl/mock/restful_server.py
- ts/nni_manager/common/manager.ts
- ts/nni_manager/common/trainingService.ts
- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/core/test/mockedTrainingService.ts
- ts/nni_manager/package.json
- ts/nni_manager/rest_server/nniRestServer.ts
- ts/nni_manager/rest_server/restHandler.ts
- ts/nni_manager/rest_server/test/mockedNNIManager.ts
- ts/nni_manager/training_service/kubernetes/kubernetesTrainingService.ts
- ts/nni_manager/training_service/local/localTrainingService.ts
- ts/nni_manager/training_service/pai/paiTrainingService.ts
- ts/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
- ts/nni_manager/training_service/reusable/routerTrainingService.ts
- ts/nni_manager/training_service/reusable/trialDispatcher.ts
- ts/nni_manager/training_service/test/localTrainingService.test.ts
- ts/nni_manager/yarn.lock
- ts/webui/src/components/public-child/OpenRow.tsx
- ts/webui/src/static/interface.ts
- ts/webui/src/static/model/experiment.ts
- ts/webui/src/static/style/openRow.scss
This is the first working example of Retiarii visualization.
TODOs:
> [Retiarii] Visualization

- docs/en_US/FeatureEngineering/GradientFeatureSelector.rst
if you pass in python lists, you will get an AttributeError.
```text
File "feature_to_vec.py", line 209, in train
fgs.fit(total_x, total_y)
File "/.../anaconda3/lib/python3.8/site-packages/nni/algorithms/feature_engineering/gradient_selector/gradient_selector.py", line 260, in fit
self._fit(X, y, groups=groups)
File "/.../anaconda3/lib/python3.8/site-packages/nni/algorithms/feature_engineering/gradient_selector/gradient_selector.py", line 290, in _fit
data_train = self._prepare_data(X, y)
File "/.../anaconda3/lib/python3.8/site-packages/nni/algorithms/feature_engineering/gradient_selector/gradient_selector.py", line 275, in _prepare_data
return PrepareData(X=X.values if isinstance(X, pd.DataFrame) else X,
File "/.../anaconda3/lib/python3.8/site-packages/nni/algorithms/feature_engineering/g …
```
> add recommend type for selector

- ts/nni_manager/training_service/reusable/trialDispatcher.ts
Because `trial.environment` is first released, it is always `undefined`.
https://github.com/microsoft/nni/blob/5eb43ea7815d8a0cf93d0a4bb6f29faf57ae6553/ts/nni_manager/training_service/reusable/trialDispatcher.ts#L734-L746
The `gpuScheduler` will never release it because it requires `trial.environment !== undefined `
https://github.com/microsoft/nni/blob/5eb43ea7815d8a0cf93d0a4bb6f29faf57ae6553/ts/nni_manager/training_service/reusable/gpuScheduler.ts#L99-L104
To fix this bug, `this.gpuScheduler.removeGpuReservation(trial)` should be executed at the beginning of `releaseEnvironment`
> Fix bug: GPUs are not released in Reusable Training Service

- docs/en_US/Tutorial/HowToLaunchFromPython.rst
- docs/en_US/sdk_reference.rst
> In `autoclass`, for module data members and class attributes, documentation can either be put into a comment with special formatting (using a #: to start the comment instead of just #), or in a docstring after the definition.
>.. autoattribute::
>These work exactly like autoclass etc., but do not offer the options used for automatic member documentation.
refer [here](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html), so I can only list all the class attributes one by one... or we can add comments to every line in the code?
> Update Python API doc

- docs/en_US/Compression/Quantizer.rst
- nni/algorithms/compression/pytorch/quantization/quantizers.py
- nni/compression/pytorch/compressor.py
This pr adds batch normalization folding to the QAT quantizer, the core ideas are described in #3890
> Add batch normalization folding to QAT quantizer

- nni/retiarii/oneshot/pytorch/darts.py
- nni/retiarii/oneshot/pytorch/proxyless.py
- nni/retiarii/oneshot/pytorch/random.py
Change `.to()` to `to_device()` for all one-shot Trainers in `nni.retiarii.oneshot.pytorch`, as requested by #3957.
> Change .to() to to_device()

- nni/compression/pytorch/compressor.py
> [Model Compression] Expand export_model arguments: dummy input and onnx opset_version

- docs/en_US/NAS/ApiReference.rst
- docs/en_US/NAS/OneshotTrainer.rst
- docs/en_US/NAS/WriteOneshot.rst
- examples/nas/oneshot/darts/model.py
- examples/nas/oneshot/darts/retrain.py
- nni/retiarii/__init__.py
- nni/retiarii/fixed.py
- nni/retiarii/oneshot/pytorch/darts.py
Fix #3969.
Added an API called `fixed_arch` to enable users to quickly use the exported architecture.
I haven't tested on other trainers because their retraining code looks over complex. I'll do that as a follow-up task.
> Enable `fixed_arch` on Retiarii

- examples/model_compress/quantization/observer_quantizer.py
- nni/algorithms/compression/pytorch/quantization/observers.py
- nni/algorithms/compression/pytorch/quantization/quantizers.py
- test/ut/sdk/test_compressor_torch.py
This PR adds a post training quantizer `ObserverQuantizer`. It uses PyTorch official `HistogramObserver` to calculate quantization information of activation and uses `MinMaxObserver` for weight. This quantizer has two advantages:
1. Users can directly get quantization information of a pre-trained model with a little calibration data. Training is not needed.
2. The quantization information generated by this quantizer can be used to initialize the scale and zero point of QAT quantizer, which will lead to a faster convergence and a better accuracy.
Also, users can easily customize their own observer, as long as the usage of the observer is consistent with that of PyTorch. I will upload our implementation of a classic post-training quantizer (e.g. Kullback-Leibler observer, used by TensorRT) …
> Add post training observer_quantizer

- nni/retiarii/experiment/pytorch.py
- ts/nni_manager/core/nnimanager.ts
> fix multi-thread event handling issue

- test/config/integration_tests.yml
- ts/nni_manager/core/nniTensorboardManager.ts
1. mount point in local may late to umount when stop experiment in `shared-storage-remote-azureblob`, so keep two shared storage tests away from each other.
2. hide tensorboard not installed error in `nnictl_stderr`
> fix sharedstorage it

- test/ut/sdk/test_model_speedup.py
because vgg16 is too big and usually breaks fast test...
> remove vgg16 from speedup test

- nni/compression/pytorch/utils/mask_conflict.py
- nni/compression/pytorch/utils/shape_dependency.py
Speedup does not support Slim pruners at the beginning(v1.6). Slim pruner prunes the BN layers which is not supported in the
mask_conflict utils, in this PR, we support the BN layers in mask_conflict so that Slim pruner is supported in speedup.
> Support Speedup for Slim Pruner.

- docs/en_US/Tutorial/InstallationLinux.rst
- docs/en_US/Tutorial/InstallationWin.rst
- docs/en_US/Tutorial/SetupNniDeveloperEnvironment.rst
- setup.py
To avoid introducing new problems, it does not touch scripts or code.
> Update docs of building from source

- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/training_service/local/localTrainingService.ts
Caused: the trial status was update when the trial process is exit completely(e.g. from RUNING to EARLY_STOPPED), but process exiting will cost some times which could cause status not match. 
Resue mode do not have this issue.
> fix trial status not correct when trial is early stoped

- ts/nni_manager/test/training_service/localTrainingService.test.ts
Currently the UT will not exit if the machine has GPU. This is because local training service test case will open GPU metric file and will never close it. We could add closing logic to fix it, but I think it's not the right way.
Our default UT environment is CPU-only, and by design an experiment with GPU number > 1 should fail on this type of machine. The test case was passing by accident because the error of GPU scheduler is silently ignored. And since it failed to generate GPU metric file, there is no closing issue.
This does not harm real experiments because they are stopped by `process.exit()`, which will not be blocked by file handlers.
> Disable GPU in unit test

- ts/webui/src/components/modals/tensorboard/TensorboardDialog.tsx
- ts/webui/src/components/modals/tensorboard/TensorboardUI.tsx
user use tensorboard function in webui with uninstalled tensorboard, page will broken...
if user don't install tensorboard, and he uses tensorboard function in webui, will prompt this message
api is:
> fix tensorboard catch error code bug

- nni/tools/nnictl/launcher.py
- ts/nni_manager/rest_server/restHandler.ts
1. nnictl view —experiment path/to/exp-id/ (with backslash) does not work
2. log files have content type “json”
> Fix 2 bugs found in bug bash

- nni/retiarii/utils.py
Absolute path does not equal to relative path, even if they point to same location, at least in Python 3.9 and Linux.
And I really don't like the restriction that script must be run at specific location...
> Fix a bug in retiarii

- examples/model_compress/quantization/mixed_precision_speedup_mnist.py
- nni/algorithms/compression/pytorch/quantization/quantizers.py
- nni/compression/pytorch/compressor.py
- nni/compression/pytorch/quantization_speedup/frontend_to_onnx.py
- nni/compression/pytorch/quantization_speedup/integrated_tensorrt.py
- test/ut/sdk/test_compressor_torch.py
This pr targets unifying two variable names in quantization code. They are too messy for developer and code reader. The first is `output`.`activation` -> `output`. The second is `bits`, `bit` -> `bits`. This pr also fixes a bug in quantization speedup conveniently ( [bug](https://github.com/microsoft/nni/blob/master/nni/compression/pytorch/quantization_speedup/integrated_tensorrt.py#L227) ) and adds warning for not setting optimizer in quantizer.
> [Model Compression Quantization] Unify variable name

- nni/algorithms/compression/pytorch/quantization/quantizers.py
- nni/compression/pytorch/compressor.py
As described [here](https://pytorch.org/docs/stable/notes/extending.html#extending-torch-autograd):
**Note that this logic won’t traverse lists/dicts/any other data structures and will only consider Tensor s that are direct arguments to the call**
So if we directly pass `inputs` (should be a tuple) to `quant_grad`, `inputs` will not appear in the training graph.
> change signature of quantize_input

- nni/compression/pytorch/utils/mask_conflict.py
We set the strict to false in the graph_utils, therefore
we need to align to the graph_utils.
> Set the strict to false in mask conflict utils.

- ts/nni_manager/common/shellUtils.ts
- ts/nni_manager/training_service/local/localTrainingService.ts
- ts/nni_manager/training_service/reusable/environments/localEnvironmentService.ts
I once tried to fix all similar problems together. But it looks too dangerous.
> Escape environment variable PATH for Windows scripts

- examples/model_compress/pruning/amc/utils.py
When running amc example `amc_search.py`, error `RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.` will be raised. Adding `contiguous()` to tensor can fix this bug.
> [Model Compression] fix data contiguous bug in amc example

- dependencies/recommended.txt
- nni/retiarii/evaluator/pytorch/cgo/accelerator.py
- nni/retiarii/evaluator/pytorch/cgo/trainer.py
Pytorch-lightning updates its interface of TrainingTypePlugin and AcceleratorConnector.
This PR includes:
> Fix interface of CGO's accelerator to support pytorch-lightning 1.4.2

- nni/algorithms/compression/pytorch/quantization/quantizers.py
By default, the type of `weight` will change from `torch.nn.Parameter` to `torch.Tensor(buffer)`. This will make its weight unable  to be accessed by functions like `named_parameters()`. So I think it is better to restore it by default.
> restore weight by default for qat quantizer

- docs/en_US/TrainingService/DLCMode.rst
- docs/en_US/TrainingService/Overview.rst
- docs/en_US/reference/experiment_config.rst
- docs/en_US/training_services.rst
- examples/trials/mnist-pytorch/config_dlc.yml
- nni/experiment/config/__init__.py
- nni/experiment/config/dlc.py
- nni/tools/nnictl/config_schema.py
- nni/tools/nnictl/config_utils.py
- nni/tools/nnictl/ts_management.py
- ts/nni_manager/common/experimentConfig.ts
- ts/nni_manager/config/dlc/dlcUtil.py
- ts/nni_manager/main.ts
- ts/nni_manager/training_service/reusable/dlc/dlcClient.ts
- ts/nni_manager/training_service/reusable/dlc/dlcConfig.ts
- ts/nni_manager/training_service/reusable/environments/dlcEnvironmentService.ts
- ts/nni_manager/training_service/reusable/environments/environmentServiceFactory.ts
HPO: DSW(DataScienceWorkShop) as client and DLC(DeepLearningContainers) as computing resources.
please find config in /nni/examples/trials/mnist-pytorch/config_dlc.yml
> HPO: Alibaba DSW+DLC support

- nni/algorithms/compression/pytorch/quantization/quantizers.py
- nni/compression/pytorch/compressor.py
- test/ut/sdk/test_compressor_torch.py
This pr contains two things:
1. When bn fold is enable, the folded weight is assign to `module.weight`, QAT quantizer should quantize `module.weight` instead of `module.old_weight`
2. pass the weight that should be quantized to each quantizer directly to make the training graph more clearly.
> fix wrong quantization target in weight quantization

- ts/nni_manager/common/log.ts
We should not use Date().toLocaleString() to get a formatted time string since it uses the local time format on user's machine and the format is different across platforms (windows, linux, mac) even node versions. This will lead to a failure when starting the rest server. Instead, we construct the time format by ourselves (since using libraries like `strftime` require extra dependences) which should be consistent across different platforms.
BTW, not sure why we add a ' UTC' to a local time and convert it to a UTC time. This will lead to a incorrect time if you are not in +0000.
> hotfix: fix time format issue

- examples/trials/auto-gbdt/config_windows.yml
- examples/trials/cifar10_pytorch/config_windows.yml
- examples/trials/efficientnet/config_windows.yml
- examples/trials/ga_squad/config_windows.yml
- examples/trials/kaggle-tgs-salt/config_windows.yml
- examples/trials/mnist-annotation/config_windows.yml
- examples/trials/mnist-batch-tune-keras/config_windows.yml
- examples/trials/mnist-keras/config_windows.yml
- examples/trials/mnist-nested-search-space/config_windows.yml
- examples/trials/mnist-pbt-tuner-pytorch/config_windows.yml
- examples/trials/mnist-pytorch/config_windows.yml
- examples/trials/mnist-tfv2/config_windows.yml
Added `config_windows.yml` to the examples at `/examples/trials`
`config.yml` is copied as is, but `python3` is changed to `python` for Windows systems
@liuzhe-lz
> added config_windows.yml for examples in /examples/trials

- nni/compression/pytorch/speedup/compressor.py
support directly loading the mask
> support directly loading the mask

- nni/algorithms/compression/pytorch/quantization/quantizers.py
- nni/compression/pytorch/compressor.py
Error will be raised when using observer_quantizer since tensor assigned to parameter.
Change `self.module.weight` to `self.module.weight.data` in line 562 can resolve such problem.
> [Quantization] fix parameter assign problem of weight

- nni/algorithms/hpo/random_tuner.py
- nni/common/hpo_utils/__init__.py
- nni/common/hpo_utils/formatting.py
- nni/common/hpo_utils/validation.py
- nni/runtime/default_config/registered_algorithms.yml
- test/ut/sdk/test_hpo_format_space.py
The ultimate goal is to get rid of hyperopt dependency. The code which convert formats between nni and hyperopt is nearly impossible to understand.
4 months ago issue 3534 reported a bug about TPE tuner, but I have absolutely no idea how to debug since then.
> Refactor Hyperopt Tuners (Stage 1) - random tuner

- ts/webui/src/components/modals/Compare.tsx
- ts/webui/src/components/trial-detail/TableList.tsx
**This PR is for trial detail -- `intermediate` modal, look like this picture. we don't think out this status that trial doesn't have `default` key in its intermediate result in `nni<=2.4`**
if trial doesn't have `default` key in intermediate result, the graph is liking this:
the dropdown didn't show the selected key, the graph also is null.
if trial doesn't have `default` key, we'll show this trial's other key(number type), such as `other`.
> Improve trial intermediate result graph: trials have not intermediate default key

- ts/webui/src/components/overview/count/EditExperimentParam.tsx
fix issue: https://github.com/microsoft/nni/issues/4015
maxExperimentDuration is more than execDuration by design.
webui will prompt error message now if user set maxExperimentDuration < execDuration.
> [fix issue#4015] webui prompts error message if user set maxExperimentDuration < execDuration

- dependencies/recommended.txt
- pipelines/fast-test.yml
There is a conflict between typing-extension required by pylint and required by tensorflow. I don't think tensorflow has a reasonable version request to pin typing-extension at 3.7. I'll respect pylint's dependency requirement.
> Upgrade typing extension version

- nni/compression/pytorch/speedup/compress_modules.py
- nni/compression/pytorch/speedup/compressor.py
- nni/compression/pytorch/speedup/error_code.py
Add Error code for speedup module.
> Error code for Speedup Module

- ts/jupyter_extension/src/index.ts
Jupyter-ext plus will display empty when here is no nni restful service started, which will confuse users. This PR enables to reminder to tell user to kick off experiment first
> jupyter_ext: Added reminding information when there isn't nni kicked off

- dependencies/required_extra.txt
As described in #3909, there is a missing dependency in ConfigSpace 0.4.7, which is fixed in 0.4.11
> Update ConfigSpace to 0.4.11

- README.md
- docs/en_US/Release.rst
- docs/en_US/Tutorial/InstallationLinux.rst
- docs/en_US/Tutorial/InstallationWin.rst
- docs/en_US/conf.py
Link to QAT doc will be added when it get merged.
@ultmaster Please help review the syntax. I don't know how to preview the result.
> Release Note

- ts/jupyter_extension/README.md
It's for NNI developers and will not be visible to normal user.
It does not need to merge into v2.5 branch.
> Add development README for JupyterLab extension

- ts/webui/src/App.scss
- ts/webui/src/components/overview/params/BasicInfo.tsx
- ts/webui/src/static/style/overview/command.scss
- ts/webui/src/static/style/overview/overview.scss
- fix overveiw page blank issue and set the bottom value `24px`
- add `--`  for experiment name null value
`nnictl create --config` and then see the overview page bottom.
> [webui] Improve overview page: remove blank at the bottom

- dependencies/required.txt
- docs/en_US/Compression/QuickStart.rst
- docs/en_US/model_compression.rst
- pipelines/fast-test.yml
The tutorial page is under quick start now, raise it under Compression doc.
Pin websockets <= 10.0 if python version < 3.7
Doc structure before:
Doc structure after:
Review the compression doc title level.
> [Doc & Pipeline] Fix page level & upgrade python verison in fast-test-legacy

- dependencies/recommended_gpu.txt
- examples/nas/oneshot/enas/macro.py
1. I don't know why ENAS search space breaks for PyTorch 1.10. Maybe some mechanisms about inplace add changes.
2. Inconsistent version of PyTorch-lightning between recommended and recommended_gpu, as pointed out by @hzhua.
Run pipeline.
> Fix Retiarii version issues on full test

- pipelines/integration-test-remote-l2l.yml
Because pipeline l2l time out...
> [Pipeline] extend l2l time out

- nni/retiarii/nn/pytorch/api.py
- nni/retiarii/nn/pytorch/component.py
- nni/retiarii/nn/pytorch/nasbench101.py
- nni/retiarii/nn/pytorch/utils.py
- test/ut/retiarii/test_highlevel_apis.py
This can be merged into v2.6.
Fix issues that prevents layer choices from being deep-copied.
```python
self.blocks = nn.Repeat(nn.LayerChoice([...]), (1, 3))
```
> Fix deepcopy of mutables

- nni/algorithms/hpo/gridsearch_tuner.py
When converting “vector” to final parameter format, it mistakenly included skipped dimensions.
I have tested with “else: assert self.vector[i] == 0”.
- ~~doc~~
> Fix grid search bug

- nni/experiment/config/algorithm.py
- nni/experiment/config/exp_config.py
- test/ut/experiment/test_exp_config.py
To support usage like this:
```python
config = ExperimentConfig("local")
config.tuner.class_args['seed'] = 1
```
> Fix backward incompatible config behavior

- dependencies/required.txt
filelock has just updated and dropped support for Python 3.6, which broke pipelines.
> Fix filelock imcompatible with python 3.6 issue

- nni/experiment/config/convert.py
- nni/experiment/experiment.py
- nni/runtime/log.py
- nni/tools/nnictl/launcher.py
The config converting script uses logging.warning to inform ignored config fields (authorName, multiPhase, etc).
But nnictl raises logging level to error to block random log messages from 3rd party libraries.
This PR fixes the issue, and uses Quanlu's more informative error message for config converting failure.
> Fix and improve nnictl warning message

- docs/en_US/NAS/Serialization.rst
- nni/common/serializer.py
- nni/retiarii/evaluator/functional.py
- nni/retiarii/evaluator/pytorch/lightning.py
- nni/retiarii/execution/base.py
- nni/retiarii/execution/python.py
- nni/retiarii/experiment/pytorch.py
- nni/retiarii/graph.py
- nni/retiarii/integration.py
- nni/retiarii/nn/pytorch/mutator.py
- test/ut/retiarii/mnist-tensorflow.json
- test/ut/retiarii/test_graph.py
1. Check `model_wrapped` in Retiarii experiment.
2. Throw error when pickling size is too large and update related document.
3. Fix issues in serialization of evaluator to suppress the warning: "Callstack exhausted but main module not found".
- ~test case~
Same as #4390.
> Retiarii serializer user experience improvements

- nni/experiment/experiment.py
- nni/tools/nnictl/updater.py
- ts/nni_manager/core/nnimanager.ts
Fix the bug in updating search space, the bug is incorrect json dump, details in #4398 
run mnist pytorch example with tpe tuner, update search space to a new one during experiment running, update search space is successfully updated, stop the experiment. Then resume this experiment to check whether the resume is successful and whether new trial jobs are created.
as this pr is also related to retiarii example, need to run a multi-trial nas example to check whether it works.
> [bug fix] fix the bug in update search space

- nni/experiment/config/experiment_config.py
- test/ut/experiment/assets/ss.yaml
- test/ut/experiment/assets/ss_comma.json
- test/ut/experiment/assets/ss_tab.json
- test/ut/experiment/assets/ss_tab_comma.json
- test/ut/experiment/assets/ss_yaml12.yaml
- test/ut/experiment/test_search_space.py
As of now the latest version of PyYAML (6.0) [does not support YAML 1.2](https://github.com/yaml/pyyaml/issues/116), which means it is not fully compatible with JSON.
This has caused multiple problems for NNI: #4450 #4452
The PR partially fixed this bug by trying YAML and JSON loaders consecutively. However if a user uses comment and scientific notation at same time, NNI will still fail.
Since PyYAML has already been working on [YAML 1.2 support](https://github.com/yaml/pyyaml/pull/555), I prefer to wait for its update for a perfect fix.
As a reminder, ruamel.yaml supports YAML 1.2, but according to our previous experience it's pip package and conda package have inconsistent APIs, which caused even more problems.
- ~~doc~~
Create tricky JSON search space file and make sure it's loaded …
> Fix search space compatibility with JSON

- nni/algorithms/compression/v2/pytorch/pruning/tools/task_generator.py
e.g. `origin_masks` of `op_name_1` is [1, 1, 1, 0, 0, 0], and
`config_list = [{'op_names': ['op_name_1'], 'total_sparsity': 0.5}, ...]`,
then the generated `config_list` will not contain `op_name_1`, because `op_name_1` have already masked 50%.
But it is not true because we define the `config_list` should cover the preset sparsity(masks), we expect the `config_list` to contain `op_name_1` with `sparsity=0.5`
> fix SA task generator bug

- nni/algorithms/hpo/dngo_tuner.py
- pipelines/fast-test.yml
```
2022-01-14T07:46:47.0355624Z _______________________ BuiltinTunersTestCase.test_dngo ________________________
2022-01-14T07:46:47.0356414Z 
2022-01-14T07:46:47.0356903Z self = <ut.sdk.test_builtin_tuners.BuiltinTunersTestCase testMethod=test_dngo>
2022-01-14T07:46:47.0357241Z 
2022-01-14T07:46:47.0357640Z     def test_dngo(self):
2022-01-14T07:46:47.0358171Z         tuner_fn = lambda: DNGOTuner(trials_per_update=100, num_epochs_per_training=1)
2022-01-14T07:46:47.0358811Z >       self.search_space_test_all(tuner_fn, fail_types=["choice_str", "choice_mixed",
2022-01-14T07:46:47.0359478Z                                                          "normal", "lognormal", "qnormal", "qlognormal"])
2022-01-14T07:46:47.0359863Z 
2022-01-14T07:46:47.0360277Z ut/sdk/test_builtin_tuners.py:397: …
```
> Fix SVD error for `numpy >= 1.21` in DNGO

- examples/model_compress/pruning/v2/simulated_anealing_pruning_torch.py
- nni/algorithms/compression/v2/pytorch/pruning/auto_compress_pruner.py
- nni/algorithms/compression/v2/pytorch/pruning/iterative_pruner.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/task_generator.py
- test/ut/compression/v2/test_iterative_pruner_torch.py
Add warning to SA and auto compress pruner if user set `sparsity` or `sparsity_per_layer`.
Fix example & ut bug.
Fix op_names not expand in SA task generator.
> fix total sparsity in sa & auto compress pruner bug

- README.md
- dependencies/recommended.txt
- dependencies/recommended_gpu.txt
- dependencies/recommended_legacy.txt
- dependencies/required.txt
- dependencies/required_extra.txt
- dependencies/setup.txt
- pipelines/fast-test.yml
- setup.py
Python 3.6 is dead.
PyTorch has not yet supported Python 3.10.
Need to upgrade Python on k8s IT client node.
Version resolving of Python packages on ubuntu-legacy is a complete mess now.
This will be fixed with [cache refactor](https://github.com/microsoft/nni/tree/dev-pipeline-cache).
- ~~doc~~
No need.
> Bump Python version to 3.7~3.9

- ts/webui/src/components/TrialsDetail.tsx
- ts/webui/src/static/style/trialsDetail.scss
rename Pivot's className inside `TrialsDetail` to `detail-title`
1. create a local trial example: `nnictl create --config nni/examples/trials/mnist-pytorch/config.yml`
2. go to http://127.0.0.1:8080/detail
3. check component style
> fix TrialsDetail className typo

- nni/common/serializer.py
- test/ut/sdk/imported/_test_serializer_py38.py
- test/ut/sdk/test_serializer.py
The previous trace doesn't work for `*args` and `**kwargs`. It did work in some cases, but I think it's just too lucky.
I'm trying to handle all the cases systematically in this PR.
One of the tests rely on Python 3.7+. Depends on #4475.
Fix #4483.
> Fix serializer for complex kinds of arguments

- nni/tools/nnictl/ts_management.py
* Add missing comma in `_builtin_training_services`
> fix: Missing comma

- nni/algorithms/compression/v2/pytorch/pruning/basic_pruner.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/__init__.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/sparsity_allocator.py
- test/ut/compression/v2/test_pruner_torch.py
This pr aims to support level pruner with bank feature. Bank pruning means finegrained pruning will be done in granularity of bank. For instance, if user set number of values in per bank to 4 and sparsity to 50%, level pruner will generate the same sparse pattern with [NVIDIA Sparse TensorCore](https://developer.nvidia.com/blog/exploiting-ampere-structured-sparsity-with-cusparselt/).
> [Model Compression] Add bank pruning for level pruner

- nni/algorithms/hpo/tpe_tuner.py
- test/ut/sdk/test_builtin_tuners.py
Reported by a user.
`nni.report_final_result()` accepts "a dict with key 'default'" and it's tuner's responsibility to extract the value. The refactored TPE did not implement this logic.
TODO: Add type hints and check in pipeline so "protocol mismatch" bugs like this can be reliably detected.
- ~~doc~~
Run an HPO experiment using TPE tuner and pass dict metrics to `report_final_result()`.
> Fix a bug that new TPE does not support dict metrics

- pipelines/fast-test.yml
- test/ut/compression/v2/test_iterative_pruner_torch.py
- test/ut/compression/v2/test_pruner_torch.py
Based on pruning by the threshold, we may have this situation, metrics = [0, 0, 1, 1, 2, 2], pruning 50%, then threshold=1 and 4 position will be masked, the real sparsity is 66.7%.
Apoz is easy to have repeated values in metrics when layer weight size is small.
To fix this issue by fixing seed.
TODO: Pruner needs to handle the metric equal to threshold more carefully.
> Fix seed when test apoz pruner

- ts/nni_manager/training_service/reusable/trialDispatcher.ts
liveEnvironmentsCount failed to reduce after existing live environment is stopped.
Create a reuseable training service and set the reuseMode=False.
Environments will be created and stop after use, new environment will be created.
> Bug: reduce liveEnvironmentsCount after environment is stopped

- nni/retiarii/codegen/pytorch.py
- nni/retiarii/nn/pytorch/api.py
- nni/retiarii/nn/pytorch/component.py
- nni/retiarii/nn/pytorch/nasbench101.py
- nni/retiarii/utils.py
- test/ut/retiarii/debug_mnist_pytorch.py
- test/ut/retiarii/test_convert.py
- test/ut/retiarii/test_convert_basic.py
- test/ut/retiarii/test_convert_models.py
- test/ut/retiarii/test_convert_operators.py
- test/ut/retiarii/test_convert_pytorch.py
- test/ut/retiarii/test_highlevel_apis.py
Support a state dict hook to load from supernet's state-dict.
> Support loading from `state_dict` of supernet

- nni/compression/pytorch/speedup/infer_mask.py
- nni/compression/pytorch/utils/shape_dependency.py
- test/ut/compression/v1/test_model_speedup.py
Support the issue mentioned 4540
> issue 4540

- examples/nas/multi-trial/mnist/search.py
The nas example of minist has a bug that when user choose to use GPU.
Model has not been synced to GPU device（or TPU and others), so PyTorch will fail when compute  net(input).
This problem will not occur if user choose to use CPU. 
change: exp_config.training_service.use_active_gpu = False to :
```
exp_config.training_service.use_active_gpu = True
exp_config.trial_gpu_number = 1
```
> fix: model is not synced to device when not using CPU

- nni/experiment/data.py
Add a member to TrialJob, and add a default value to TrialJob.logPath.
Details:
After experiment started by nnictl, 
1. before environment is ready, `logPath` field is missing from '/trial-jobs' response
fix: add default value for logPath, to allow the list_trial_jobs() return results
2. after environments are created, `message` field is returned from  '/trial-jobs' response, however, TrialJob does NOT have this field.
fix: add a message field for TrialJob, to align with TrialJobInfo in *.ts code.
from nni.experiment import Experiment
experiment = Experiment.connect(8080)
// before environment is ready
experiment.list_trial_jobs()
// after environments are created
experiment.list_trial_jobs()
> Fix: experiment.list_trial_jobs requires logPath & message

- examples/nas/oneshot/pfld/train.py
- nni/algorithms/nas/pytorch/fbnet/utils.py
To enable the feature, prepare a latency lookup table file lut.txt on the path ./, and add following arguments to the command:
python train.py --dev_id "0,1" --snapshot "./ckpt_save" --data_root "./data/106points" --perf_metric "latency" --lut_load True --mode "add"
Following is the format of lut.txt file:
{'op_name': operator_name,
'op_data_shape': (input_w, input_h, C_in, C_out, stride),
'op_dtype': data_type,
'op_latency': latency}
{...}
{...}
> Add a feature of reading latencies of operators with different data shapes from lut.txt file

- nni/tools/nnictl/nnictl_utils.py
Sometimes, `nnictl stop --all` failed in the unit test.
https://msrasrg.visualstudio.com/NNIOpenSource/_build/results?buildId=32629&view=logs&jobId=95b93358-fda6-5c72-3eb7-ee58b0085220&j=95b93358-fda6-5c72-3eb7-ee58b0085220&t=6d99b3d4-eb6f-53b7-dead-77c8a6940a44&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e
Two reasons may cause getting experiment metadata failed from `~/nni-experiments/.experiment`.
1. metadata does not exist
2. read `.experiment` failed
This issue is hard to reproduce, so just retry for now.
Create several experiments and `nnictl stop --all`.
> Retry logic for getting experiment metadata failed

- nni/__init__.py
- nni/algorithms/hpo/gridsearch_tuner.py
- nni/algorithms/hpo/random_tuner.py
- nni/algorithms/hpo/tpe_tuner.py
- nni/common/hpo_utils/__init__.py
- nni/common/hpo_utils/dedup.py
- nni/common/hpo_utils/formatting.py
- test/ut/sdk/test_builtin_tuners.py
- test/ut/sdk/test_hpo_dedup.py
Users have complained about new TPE generating duplicate parameters.
This PR ensures that TPE and Random will never generate same params. When the search space is exhausted, they raise no more trial.
Run HPO experiment with TPE and Random tuner on small search space. Check the parameters are different.
> Deduplicate generated parameters for TPE and Random

- pipelines/fast-test.yml
- pipelines/templates/install-dependencies.yml
- test/pytest.ini
One major complaint about pipelines is: there are too much useless information in logs. As a result, we have trouble finding the root cause of failure; we might even miss out important warnings because they are flooded by tons of messages.
This PR cleans up useless information on pipelines, and highlight the important ones:
1. Suppress major (but useless) warnings. These warnings are mainly DeprecationWarning. It doesn't really matter, because pipelines will raise error anyway in case of API change.
2. Mute the documentation building progress bar.
3. List pip dependencies so that we can easily inspect the python environment on pipeline machines.
> Cleanup useless messages on pipeline

- nni/tools/nnictl/legacy_launcher.py
- ts/nni_manager/common/globals/arguments.ts
The NNI manager command line args for v1 config is incorrect. An underscore was forgotten to change to hyphen.
And the error handling is problematic. Exception thrown in callback cannot be caught.
It was originally designed to invoke `ShutdownManager.criticalError()`, but that PR has not been merged.
- ~~doc~~
IT will test it.
> Fix NNI manager argparse bug for v1 config

- examples/nas/multi-trial/mnist/search.py
- nni/common/version.py
- nni/retiarii/integration.py
- nni/retiarii/integration_api.py
- test/ut/sdk/test_version.py
Sometimes, inconsistent version between manager side and trial side causes problems that are not straightforward to debug.
This PR adds a warning message for inconsistent package versions detected.
Try to make NNI manager run in a different env from the trial.
> Enable trial version check in Retiarii

- nni/retiarii/experiment/pytorch.py
- nni/retiarii/nn/pytorch/api.py
- nni/retiarii/nn/pytorch/mutator.py
- test/ut/retiarii/test_highlevel_apis.py
There's a bug when mutating parameters on architectures and hyper-parameters (evaluators) simultaneously. I made a mistake of writing `mutator.name` rather than `mutator.label`, and tests didn't cover this part.
This PR also adds a recursive inspection of evaluator arguments, so that you can do this:
```python
FunctionalEvaluator(
foo,
t=Foo(some_argument=ValueChoice([1, 2, 3], label='t')),
v=ValueChoice([1, 2, 3], label='t') + ValueChoice([10, 20, 30])
)
```
> Bug fix of mutating architectures and hparams simultaneously

- nni/common/serializer.py
- nni/retiarii/execution/api.py
- nni/retiarii/nn/pytorch/mutator.py
- test/ut/retiarii/test_highlevel_apis.py
- test/ut/sdk/test_serializer.py
This is a collection of bug fixes in v2.7 bug bash.
1. Calling `get()` is needed after `trace_copy()` because sometimes we need functions from the original class.
2. Fix the case when ValueChoice only appears in the deep recursion. In this case, all ancester objects need to be updated.
3. Add a warning about Python version when cloudpickle fails to de-serialize.
4. Make error message more informative when execution engine is set multiple times.
> Bug fix of Retiarii hyperparameter mutation

- nni/retiarii/nn/pytorch/mutator.py
- test/ut/retiarii/test_highlevel_apis.py
Fixed a bug of evaluator mutation. When traced keyword argument is a traced type (e.g., nn.Conv2d) rather than a traced instance (e.g., nn.Conv2d()), it will be incorrectly considered as an object that requires further inspection.
> Fix bug when traced kwargs are traced type

- ts/nni_manager/common/experimentStartupInfo.ts
- ts/nni_manager/common/globals/index.ts
- ts/nni_manager/common/globals/paths.ts
- ts/nni_manager/common/globals/unittest.ts
- ts/nni_manager/common/utils.ts
- ts/nni_manager/main.ts
- ts/nni_manager/rest_server/index.ts
- ts/nni_manager/test/core/dataStore.test.ts
- ts/nni_manager/test/core/sqlDatabase.test.ts
- ts/nni_manager/test/rest_server/rest_server.test.ts
Introduce a `globals` module to collect all global variables in `global.nni`.
This is essential for 3rd-party training service to become practical.
Unlike Python, each Node.js package has its own dependency directory. If package `A` and `B` both depends on package `C`, there will be 2 copies of `C`. This causes problems when `C` has singletons like logger stream, port listener, etc.
The simplest solution is to utilize `global`, the special singleton offered by Node.js runtime. This namespace object is shared by all modules, no matter where they are. So we will use it to share singletons and constant information between NNI manager core and training services.
This is the first PR and it initiates the infrastructure. Now the globals module contains command line args and experiment paths. …
> Refactor NNI manager globals (step 3) - globals module

- docs/source/conf.py
Some links often fail on pipeline.
> Ignore some links that often fail

- nni/algorithms/hpo/medianstop_assessor.py
- nni/algorithms/hpo/tpe_tuner.py
- nni/retiarii/strategy/_rl_impl.py
- nni/tools/package_utils/common.py
- nni/tools/package_utils/tuner_factory.py
- nni/typehint.py
We have made `typing_extensions` required dependency, so `nni.typehint` does not need to help importing annotation types any more.
No need.
No release note.
> Replace nni.typehint with typing_extensions

- nni/common/serializer.py
- test/.gitignore
- test/ut/sdk/imported/_test_serializer_main.py
- test/ut/sdk/test_serializer.py
cloudpickle is unhappy with SerializableObject extending Generic. Have to sacrifice some typings and make cloudpickle work first.
- ~doc~
Try `examples/nas/multi-trial/search.py`. It was broken.
> Remove Generic from SerializableObject typings

- nni/compression/pytorch/speedup/compress_modules.py
supported the output_padding argument of torch.nn.ConvTranspose2d in model speedup, which is mentioned in #4798.
call torch.nn.ConvTranspose2d with output_padding and do model speedup
> supported output_padding for convtranspose2d in model speedup

- nni/algorithms/hpo/gridsearch_tuner.py
- nni/algorithms/hpo/random_tuner.py
Add optional arguments `optimize_mode` to random tuner and grid search tuner.
The value will be used by web portal to sort trials: #4839
- ~~doc~~
Create experiment with random tuner in different optimize modes. Check that web portal sorts the trials in correct order.
> Add args optimize_mode to random and grid search tuner

- nni/common/graph_utils.py
fix #4785
~- [ ] test case~
~- [ ] doc~
Try to prune and speedup the following model.
```
class TestModule(torch.nn.Module):
def __init__(self):
super().__init__()
self.fc = torch.nn.Linear(10, 10)
def forward(self, x):
return self.fc(x)
@torch.jit.export
def helper(self, x):
return x + 5 
```
> [Compression] pruning speedup support RecursiveScriptModule

- nni/utils.py
Fix a `merge_parameter()` type check failure issue.
I don't really know what's the exact type checking rule here.
For example is it acceptable to assign `numpy.float32` to `float`?
- ~~doc~~
> Loose merge_parameter() type checking

- nni/algorithms/hpo/tpe_tuner.py
- nni/common/serializer.py
- nni/runtime/platform/local.py
- test/ut/sdk/test_serializer.py
Issue 4810 reported a bug. The user said it's about TPE nested search space.
It was in fact caused by parameter deserialization. For some reason the trial code requires the parameter to be a plain dict, but in current version it will be `OrderedDict`.
During investigating this problem, however, I did find a bug in TPE nested search space. 🤔
- ~~doc~~
Check the search space and trial code in issue 4810.
> Fix issue 4810

- nni/common/graph_utils.py
- nni/compression/pytorch/speedup/jit_translate.py
- nni/compression/pytorch/utils/shape_dependency.py
The following problem has done.
~This can work but infer mask might lead an unexcepted masks (the dependence between fc1 and expand_as outputs).~
~The following can reproduce this situation. `fc1.weight` cannot replace to a smaller one during speedup, but actually it should replace.~
```
import torch
from nni.compression.pytorch.pruning import L1NormPruner
from nni.compression.pytorch.speedup import ModelSpeedup
class TestModel(torch.nn.Module):
def __init__(self) -> None:
super().__init__()
self.fc1 = torch.nn.Linear(10, 5)
self.fc2 = torch.nn.Linear(10, 1)
self.fc3 = torch.nn.Linear(5, 2)
def forward(self, x):
a = self.fc1(x)
b = self.fc2(x).expand_as(a)
return self.fc3(a + b)
model = TestModel()
pruner = L1NormPruner(model, [{'op_names': ['fc1'], 'sparsity': 0.5}])
_, masks = …
```
> [Compression] support expand_as

- nni/algorithms/hpo/tpe_tuner.py
The exported data format and/or resuming metrics format has changed sometime before and they are mismatch now.
I really don't want to investigate into those messy stuffs. So make TPE tolerate any metrics format.
It seems this problem applies to other tuners as well. But I don't want to touch them before a systematic refactor.
- ~~doc~~
Run an HPO experiment. Export then import.
> Make TPE import data more robust

- nni/experiment/experiment.py
- nni/tools/nnictl/launcher.py
- ts/nni_manager/common/utils.ts
- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/extensions/nniTensorboardManager.ts
- ts/nni_manager/test/core/ipcInterface.test.ts
- ts/nni_manager/test/core/ipcInterfaceTerminate.test.ts
Bug 1: `sys.executable` can include spaces. NNI manager cannot handle this type of commands before.
Bug 2: Forgot to wait completion in `nnictl create --foreground`.
> Fix two bugs introduced in this sprint

- nni/tools/nnictl/command_utils.py
- test/pytest.ini
- test/ut/tools/nnictl/test_kill_command.py
There is a long-known issue that the node could be still on even after experiment stops / nnictl stop exits. This causes many issues including port not available, experiment status incorrect (could be STOPPING).
This PR attempts to fix this issue by adding a wait of 60 seconds, for the kill command to be successfully executed. It also adds a twice-Ctrl-C to refrain users from killing the cleanup process by accident.
> Refactor integration test (step 1) - wait for kill

- ts/nni_manager/training_service/reusable/shared_storages/azureblobStorageService.ts
The mount fails when there is stderr. This is definitely incorrect, because dpkg itself can produce some stderr but it doesn't mean that it has failed.
I don't know the correct fix for this issue, but the changes are necessary to make pipelines work.
> Refactor integration test (step 3) - Azure blob mount robustness

- pipelines/build-vm-image-linux.yml
- pipelines/build-vm-image-windows.yml
- pipelines/templates/build-vm-image-template.yml
- test/vso_tools/build_vm/change_ssh_port.sh
- test/vso_tools/build_vm/change_winrm_port.ps1
- test/vso_tools/build_vm/config_linux.json
- test/vso_tools/build_vm/config_windows.json
- test/vso_tools/build_vm/packer_build_windows.py
- test/vso_tools/build_vm/setup_linux.sh
- test/vso_tools/build_vm/setup_windows.ps1
- test/vso_tools/build_vm/setup_windows_finalize.ps1
Add a VM image builder, that builds Linux and Windows VM images, used in VMSS pipeline agents.
All technical details can be found in the scripts. I think it's well-commented.
GPU support is not complete. As a result, in follow-up PRs, I won't enable GPU on remote (both w&l), local w, and hybrid, because,
1. I didn't install nvidia-docker on linux with GPUs.
2. There are no GPU tests on remote and hybrid's remote part.
3. (for windows) Singapore's GPUs has been sold out. The VM builder (packer) can't even create a single VM with GPUs. When the image is built upon a machine without GPU, the driver fails to install.
4. (for windows) We can't install driver on-the-fly because there is no administrative rights.
> Refactor integration test (step 5) - VM image builder

- pipelines/integration-test-local-windows.yml
- pipelines/integration-test-remote-l2w.yml
- pipelines/integration-test-remote-w2l.yml
- pipelines/integration-test-remote-w2w.yml
- test/vso_tools/ssl_patch.py
Upgrade windows pipelines to the latest.
Adds a remote windows to windows pipeline that connects to 127.0.0.1 via ssh.
The VM image has some flaws with its credential. I think it might be somewhat related to WinRM. I don't want to debug it now. A patch is used to disable SSL check globally.
l2w and w2l pipelines are deprecated now.
> Refactor integration test (step 8) - pipeline updates (windows part)

- nni/common/version.py
- nni/experiment/experiment.py
All logs appear twice after this:
```python
import nni
import logging
logging.info('hello')
_logger = logging.getLogger('nni.logger')
_logger.info('hello')
```
`logging.info` will automatically register a root handler in case there is none. NNI's log will propagate to the root logger and processed by this default handler. The easiest solution here is avoid using `logging.info` at all.
> Replace `logging.info` with `logger.info`

- docs/source/conf.py
- nni/experiment/config/experiment_config.py
If the experiment config contains a bad field in tuner section, the error message will not be correctly shown.
Example:
```yaml
tuner:
name: tpe
kwargs:  # it should be "class_args"
optimize_mode: maximize
......
```
The error message should be something like "AlgorithmConfig does not have field kwargs".
> Fix error message for incorrect tuner config

- ts/nni_manager/core/tuner_command_channel/websocket_channel.ts
The tuner class is initialized before dispatcher connecting to NNI manager. If the initialization failed, dispatcher will never connect to NNI manager.
Therefore, NNI manager cannot detect such failure with PING. This PR adds a timeout on waiting connection to detect this kind of error.
This is a quick fix. In future `setupTuner()` should monitor the process' status.
- ~~doc~~
> Fix the bug that tuner init error does not cause ERROR state

- nni/experiment/config/base.py
- nni/experiment/config/training_service.py
- nni/experiment/config/training_services/aml.py
- nni/experiment/config/training_services/dlc.py
- nni/experiment/config/training_services/frameworkcontroller.py
- nni/experiment/config/training_services/k8s_storage.py
- nni/experiment/config/training_services/kubeflow.py
- nni/experiment/config/training_services/local.py
- nni/experiment/config/training_services/openpai.py
- nni/experiment/config/training_services/remote.py
- nni/experiment/config/utils/internal.py
Previously config classes do not support `from __future__ import annotations`, in which case `Field.type` will be strings and cannot be checked by `typeguard`.
Other changes:
- Add type hints to an internal util module
- Use `Literal` for training service platform type hints.
> Allow postponed annotations for config classes

- nni/common/serializer.py
- test/ut/sdk/test_serializer.py
`_nni_symbol` gets unexpectedly modified after calling nni.dump / pickle.dump / torch.save. cc @J-shang
> Fix unintended modification of trace symbol after dump

- nni/retiarii/hub/pytorch/autoformer.py
- nni/retiarii/hub/pytorch/utils/pretrained.py
- nni/retiarii/oneshot/pytorch/supermodule/_operation_utils.py
- nni/retiarii/oneshot/pytorch/supermodule/operation.py
- test/algo/nas/test_oneshot_supermodules.py
- test/algo/nas/test_space_hub_oneshot.py
A new code of [pull#4965](https://github.com/microsoft/nni/pull/4965). Refactoring autoformer's search space to make it compatible with enas, darts, randomoneshot strategy.
Major changes:
- Add `MixedLayerNorm` in `nni/nni/retiarii/oneshot/pytorch/supermodule/operation.py` and unit test.
- Support fixed head_dim(64) in `RelativePositionAttention` of `nni/nni/retiarii/hub/pytorch/autoformer.py`.
- Use split QKV linear layer rather than one  linear layer.
- Add `ClsToken` and `AbsPosEmbed` to replace `ModelParameterChoice`, which is not compatible with RandomOneShot strategy. Use mixed operation.
- Add `load_searched_model` to load searched model and weights from official code. The result is align.
evaluate on imagenet val set
```
import os
from tqdm import tqdm
import torch
import torch.nn …
```
> Fix Autoformer to compatible with RandomOneShot strategy

- nni/algorithms/hpo/gp_tuner/util.py
See [Issue](https://github.com/microsoft/nni/issues/4974). When using GP tuner, it will pass wrong search space bound to scipy, which will fail bound check. Previous code is:
```
bounds_minmax = np.array(
[[bound['_value'][0], bound['_value'][-1]] for bound in bounds])
```
But GP tuner should support both quniform and qloguniform, which is [low, high, q]. `bound['_value'][-1]` will visit q instead of higher bound.
> Add condition control when passing parameters bounds to scipy.minimize.

- nni/algorithms/hpo/tpe_tuner.py
- nni/common/hpo_utils/dedup.py
- nni/runtime/msg_dispatcher.py
- nni/tuner.py
- test/ut/sdk/test_builtin_tuners.py
- ts/nni_manager/common/datastore.ts
- ts/nni_manager/common/trainingService.ts
- ts/nni_manager/core/nnimanager.ts
- ts/nni_manager/test/mock/datastore.ts
- ts/nni_manager/training_service/kubernetes/adl/adlTrainingService.ts
- ts/nni_manager/training_service/kubernetes/frameworkcontroller/frameworkcontrollerTrainingService.ts
- ts/nni_manager/training_service/kubernetes/kubeflow/kubeflowTrainingService.ts
- ts/nni_manager/training_service/local/localTrainingService.ts
- ts/nni_manager/training_service/pai/paiTrainingService.ts
- ts/nni_manager/training_service/remote_machine/remoteMachineTrainingService.ts
- ts/nni_manager/training_service/reusable/trialDispatcher.ts
update resume logic, change RUNNING/WAITING to WAITING (was FAILED).
send resume parameters to the tuner side, to allow deduplication logic work.
NOTE: currently only TPE tuner implemented the import_customized_data function.
1. run the case: nnictl create --config examples/trials/mnist-pytorch/config.yml 
2. nnictl stop
3. nnictl resume xxx
4. check the status(waiting for the not finished trials), check the "Trial No."(keep original sequenceId/parameter_index)
5. after all trials done, no duplicate params.
> [FEAT]: resume waiting/running, dedup on tuner side (TPE-only)

- examples/nas/multi-trial/nasbench101/network.py
- examples/nas/multi-trial/nasbench201/network.py
- nni/nas/benchmarks/utils.py
- nni/nas/evaluator/pytorch/cgo/evaluator.py
- nni/nas/evaluator/pytorch/lightning.py
- nni/nas/execution/common/graph.py
- nni/nas/nn/pytorch/layers.py
- test/algo/nas/test_cgo_engine.py
This needs to be merged before #5049 and #5050.
* Fix LR scheduler in benchmark example.
* Add a friendly message when benchmark is not downloaded.
* Support `fit_kwargs` in lightning evaluator.
* Make evaluator modules non-private API.
* Fix type-checking import in graph.
* Add prompt of imports for nas.nn.layers.
> Miscellaneous fixes of NAS (v2.9)

- dependencies/required.txt
- nni/experiment/management.py
Generate experiment id with ~shortuuid~ Random. This fixes the issue that when `random.seed` is called, experiment id is always the same.
> Use Random to generate experiment id

- nni/algorithms/compression/v2/pytorch/pruning/tools/base.py
- nni/common/graph_utils.py
- nni/compression/pytorch/speedup/compress_modules.py
- nni/compression/pytorch/speedup/infer_mask.py
- nni/compression/pytorch/utils/shape_dependency.py
Add Group Norm support for model pruning.
I am not sure if this algorithm works for GroupNorm 
--> Need to do experiments to recheck the algorithm.
There are two main ways to prune GroupNorm (one is pruning group (reduce the number of groups, keep the number of channels per group the same, finally the module will become `LayerNorm`), the other is pruning the channel per group (finally the module will become `InstanceNorm`).
This implementation is the second approach as I saw that for `Conv2d`, we keep the number of groups the same.
But personally, I prefer the first approach as LayerNorm is more widely accepted and outperforms `InstanceNorm` according to `GroupNorm` original paper.
p.s: Lacking the infrastructure to do these test :(
```python
from nni.compression.pytorch.pruning import …
```
> Add Group Norm support for Pruning model

- nni/algorithms/compression/v2/pytorch/pruning/basic_pruner.py
- nni/algorithms/compression/v2/pytorch/pruning/basic_scheduler.py
- nni/algorithms/compression/v2/pytorch/pruning/tools/task_generator.py
- nni/algorithms/compression/v2/pytorch/utils/__init__.py
- nni/algorithms/compression/v2/pytorch/utils/pruning.py
- nni/compression/pytorch/compressor.py
Fix some bugs found by @QuanluZhang
1. let pruner raise `unexpected keyword argument` error before raise `required positional argument` error.
2. disable evaluation in functional based scheduled pruners.
3. fix activation-based pruner collected module output on two devices in DP training.
4. fix activation-based pruner always reduce activation dim on 0 (now dynamically adapt reduce dims to different module types)
> [Bugbash] fix some pruner bugs

- nni/common/blob_utils.py
- nni/nas/hub/pytorch/autoformer.py
- nni/nas/hub/pytorch/utils/pretrained.py
- test/algo/nas/test_space_hub.py
Add subnet and supernet weights from offical repo for autoformer. Add interface for official model space config.
```
from nni.retiarii.hub.pytorch import AutoformerSpace
for name in ['tiny', 'small', 'base']:
AutoformerSpace.load_searched_model(name, pretrained = True, download = True)
AutoformerSpace.load_strategy_checkpoint(name)
```
> Add official pretrained weights for Autoformer

- README.md
- docs/source/conf.py
- docs/source/release.rst
Release note and update versions.
> Release note (v2.9)

- nni/compression/pytorch/speedup/compressor.py
- nni/compression/pytorch/speedup/infer_mask.py
- test/algo/compression/v2/test_auto_conv.py
when randomizing, if the tensor is not contiguous, we cannot use torch.nn.init.uniform_ to randomize it.
so we should detect and make it contiguous.
> fix(speedup): make the tensor contiguous before randomizing

- nni/compression/pytorch/speedup/jit_translate.py
- test/algo/compression/v2/test_schema_parser.py
reason:
the official aten schema parser of python lost the 'kwarg_only' info in python versions <1.9.0.
and schema is not simple enough to use some regex to parser.
solution:
so I translated the schema parser code from pytorch 1.12 c++ code to python and adapted some deleted syntaxes in pytorch 1.8.
tested in pytorch versions 1.8, 1.9, 1.10, 1.11 and 1.12.
note:
`torch._C.Node` supports `schema` function since version 1.8. so speedup cannot use on pytorch 1.7 now.
#5131 can be solved.
> fix(speedup): re-write aten schema parser to support pytorch versions < 1.9.0

- dependencies/required.txt
- dependencies/required_extra.txt
- docs/source/hpo/tuners.rst
- nni/algorithms/hpo/hyperopt_tuner.py
- setup.py
It does not affect users who upgrade from 2.9-
Use a new environment, run `pip install nni[Anneal]` and create HPO experiment with Anneal tuner.
> Make anneal tuner optional

- nni/__main__.py
- nni/runtime/msg_dispatcher_base.py
- nni/runtime/tuner_command_channel/channel.py
- nni/runtime/tuner_command_channel/command_type.py
- nni/runtime/tuner_command_channel/websocket.py
- ts/nni_manager/common/deferred.ts
- ts/nni_manager/core/tuner_command_channel/shim.ts
- ts/nni_manager/core/tuner_command_channel/websocket_channel.ts
- ts/nni_manager/test/core/tuner_command_channel.test.ts
Dispatcher now tries to reconnect when it loses connection to NNI manager.
For one command it only retries once. If it fails twice for the same message then dispatcher crashes.
Because the reconnect is raised by client (dispatcher) side, dispatcher to manager messages will be resent on connection loss, but manager to dispatcher messages during the reconnect (~5s) will loss. I think it's okay because it only hurts tuner's accuracy.
Because connection error is now "expected", we add a new tuner command `ER` (error) to report real tuner error.
When the outermost function of dispatcher catches an exception, it tries to send the content with error command.
In NNI manager side, the shim layer of IPC channel is modified to report `ER` content to NNI manager and hide connection errors.
- ~~doc~~ …
> Let tuner auto reconnect to NNI manager

- nni/algorithms/compression/v2/pytorch/pruning/basic_pruner.py
- nni/compression/pytorch/utils/utils.py
If tensor.dtype is torch.bool, the range of it should be [0, 2)
> [Compression] fix speedup randomize bool

- nni/nas/oneshot/pytorch/base_lightning.py
- nni/nas/oneshot/pytorch/differentiable.py
Fix type annotation to be compatible with PyTorch-Lightning v1.8.
> Fix typecheck for pytorch lightning v1.8

- nni/runtime/tuner_command_channel/channel.py
According to Lijiao's test the exception is not always `ConnectionClosed`.
> Catch broader exceptions in websocket reconnect

- nni/runtime/command_channel/__init__.py
- nni/runtime/command_channel/base.py
- nni/runtime/command_channel/http.py
- ts/nni_manager/common/command_channel/http.ts
- ts/nni_manager/common/command_channel/interface.ts
- ts/nni_manager/common/globals/index.ts
- ts/nni_manager/common/globals/rest.ts
- ts/nni_manager/common/globals/unittest.ts
- ts/nni_manager/main.ts
- ts/nni_manager/rest_server/index.ts
- ts/nni_manager/test/common/command_channel/http.test.ts
- ts/nni_manager/test/register.js
- ts/nni_manager/test/rest_server/nni_manager_handlers.test.ts
- ts/nni_manager/test/rest_server/rest_server.test.ts
A simple command channel based on HTTP and polling.
It will be used by the new trial keeper to interact with trials.
The HTTP protocol is chosen because:
1. The channel client is user's trial code. So it is good to keep the client as simple as possible.
2. There are not many commands and only one of them is issued by the server. For each trial there is only 1 request parameter, 1 send parameter (from server), N send intermediate metrics, and 1 send final metric. Therefore the performance does not matter, especially the server to client performance.
Note: Trial logs (stdout and stderr) are not sent by command channel.
The RestServer is modified to support register REST API handlers on the fly.
Previously the RestServer is created after all other components and register all handlers during …
> Training service util: HTTP command channel

- pipelines/fast-test.yml
- setup_ts.py
Adding support for legacy glibc back.
It's becoming more and more difficult to find a machine to build those binaries, especially after ubuntu 18.04 are removed from pipelines in the coming December. I think we won't upgrade them for at least a few months unless necessary.
> Add legacy build for node.js v18

- nni/experiment/experiment.py
- nni/tools/nnictl/updater.py
Description
fix exp update_max_experiment_duration bug && nnictl update duration bug
Test Options
nnictl update duration --value 300000m
exp.update_max_experiment_duration('200000m')
> fix exp update_max_experiment_duration bug && nnictl update duration bug

- nni/compression/pytorch/speedup/jit_translate.py
- test/algo/compression/pruning/test_auto_conv.py
the jit translation of 'aten::to.dtype_layout' in pytorch 1.10 will cause some error.
fix it by adding a check.
> fix(speedup): fix the error on jit translation of 'aten::to.dtype_layout' in pytorch <= 1.10

- dependencies/develop.txt
- docs/source/conf.py
- docs/templates/layout.html
Jquery is no longer an auto-injected dependency as of the latest version of sphinx.
Added sphinx-comment for easier documentation annotation and review.
> Fix jquery dependency in docs and add sphinx-comment

- docs/templates/header.html
Fix `logo_url`.
https://www.sphinx-doc.org/en/master/extdev/deprecated.html#dev-deprecated-apis
> Fix logo for documentation

- nni/compression/pytorch/speedup/infer_mask.py
#5299 encountered some trivial user warnings. `retain_grad()` does not affect numerical results, but will allow access to `.grad` field of non-leaf activations without warning.
> Fix issue #5299.

- nni/__init__.py
- nni/mutable/_notimplemented.py
- nni/mutable/exception.py
- nni/mutable/frozen.py
- nni/mutable/mutable.py
- nni/mutable/shortcut.py
- nni/mutable/symbol.py
- nni/mutable/utils.py
- pipelines/fast-test.yml
- test/ut/sdk/mutable/test_frozen.py
- test/ut/sdk/mutable/test_mutable.py
- test/ut/sdk/mutable/test_shortcut.py
- test/ut/sdk/mutable/test_symbol.py
- test/ut/tools/nnictl/test_kill_command.py
- ts/nni_manager/test/training_service_v3/local.test.ts
This PR brings the following enhancements to mutable APIs.
- Shortcuts to create mutables via functions like `nni.choice`, `nni.uniform` and `nni.randint`.
- Add a strict flag to control whether to raise error when context is missing in `ensure_frozen`.
- Add `case` and `switch_case` to MutableExpression, in preparation for hardware-aware NAS.
- `as_legacy_dict` to convert the new mutables into legacy search space JSON.
- Improved representation string for mutables.
- Fix the case of numpy.array in mutable_equal.
- Miscellenous bug fixes and test enhancements.
It should be merged prior to #5279.
> Mutable shortcut and enhancements

- nni/compression/pytorch/speedup/v2/model_speedup.py
- nni/compression/pytorch/speedup/v2/utils.py
- nni/compression/pytorch/utils/mask_conflict.py
- test/algo/compression/pruning/test_speedup_v2_init_mask.py
Support input/output masks in pruning speedup, more test cases are needed.
> [Compression] pruning speedup: support input/output masks

- nni/common/concrete_trace_utils/concrete_proxy.py
- nni/common/concrete_trace_utils/concrete_tracer.py
Consider the following code with the inappropriate assignment of parameters and buffers during forward().
```python
class A(torch.nn.Module):
def __init__(self):
super().__init__()
x = torch.tensor([1.0])
buf = torch.tensor([1])
self.register_parameter('x', torch.nn.Parameter(x))
self.register_buffer('buf', buf)
def forward(self):
self.x = self.x.to(torch.float32)
self.buf = self.buf + 1
return self.x, self.buf
```
Here we raise a warning and recover the module.
```bash
[2023-03-14 04:40:14] WARNING: Parameter x of A() is a ConcreteProxy. Some weight may be modified inplace within forward().
[2023-03-14 04:40:14] WARNING: Buffer buf of A() is a ConcreteProxy. Some buffer may be modified inplace within forward().
[2023-03-14 04:40:14] WARNING: Some weight or buffer is modified inplace …
```
> [Common] add warnings and retain the module after inappropriate weight assignment

- ts/nni_manager/core/nnimanager.ts
The polling APIs of v3 training services are trivial. So it's safe to reduce the interval.
> Reduce NNI manager's poll interval when using v3 training services

- docs/source/hpo/assessors.rst
- nni/algorithms/hpo/curvefitting_assessor/curvefitting_assessor.py
- nni/algorithms/hpo/medianstop_assessor.py
From examples in assessor,
```python
config.assessor.name = 'Medianstop'
config.tuner.class_args = {
'optimize_mode': 'maximize',
'start_step': 5
}
```
these code cause error like this:
```
Traceback (most recent call last):
File "/home/dof/anaconda3/envs/optune/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/dof/anaconda3/envs/optune/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/dof/anaconda3/envs/optune/lib/python3.9/site-packages/nni/__main__.py", line 85, in <module>
main()
File "/home/dof/anaconda3/envs/optune/lib/python3.9/site-packages/nni/__main__.py", line 42, in main
tuner = _create_algo(exp_params['tuner'], 'tuner')
File …
```
> Fix wrong examples in assessor docs

- nni/tools/nnictl/common_utils.py
- ts/webui/package-lock.json
NNI is using an internal attribute of filelock, and it has changed in the latest version.
The webui lock file is updated because I forgot to commit it in last PR.
> Fix compatibility with filelock 3.12.0

- nni/experiment/experiment.py
- ts/nni_manager/common/trial_keeper/keeper.ts
> Fix local IT

- dependencies/develop.txt
- docs/static/img/nni-icon.svg
- docs/templates/header.html
~Temporarily pin sphinx < 7.0 to resolve the icon issue and avoid blocking release.~
Turns out `html_logo` setting is broken a long time ago.
> Fix `html_logo` for sphinx docs

- nni/nas/profiler/pytorch/utils/shape_formula.py
- test/ut/nas/profiler/test_shape.py
> add avgpool2_formula to shape_formula.py

- nni/common/concrete_trace_utils/concrete_tracer.py
- nni/common/concrete_trace_utils/utils.py
- test/algo/compression/pruning/test_concrete_trace_dce.py
This PR mainly contains:
- fix dce: the new concrete_trace_utils makes use of pytorch official `Graph.eliminate_dead_code()` but adds more checks to avoid  already known mistakes by official dce. This is done by adding a `node_is_impure_wrapper`.
- add Scope: `Scope` is a new feature introduced since Pytorch2.0. The new concrete_trace_utils makes use of official `Scope` to record nodes' module path information(hierarchy) and makes it backward compatible with older version of Pytorch.
- add `trace_twice` api: make it default to trace once.
- fix other bugs.
added a test file nni/test/algo/compression/pruning/test_concrete_trace_dce.py
> [Common] fix dce and add Scope
